### ISSUE TITLE
Adding foreign keys without specifying the referenced column crashes the backend

### ISSUE THREAD

**Issue by onderkalaci** [citusdata/citus#1209]
Steps to reproduce:
```SQL

CREATE TABLE main_table (key int PRIMARY KEY, value int);
SELECT create_distributed_table('main_table', 'key');

CREATE TABLE ref_table (key int, value int);
SELECT create_distributed_table('ref_table', 'key');

ALTER TABLE ref_table ADD CONSTRAINT f_key FOREIGN KEY (key) 
REFERENCES main_table ON DELETE CASCADE;

-- if we were to write the same statement with the referencing column as well, it'd work
-- ALTER TABLE ref_table ADD CONSTRAINT f_key FOREIGN KEY (key)
-- REFERENCES main_table(key) ON DELETE CASCADE;
```

The backtrace:
```
Program received signal EXC_BAD_ACCESS, Could not access memory.
Reason: KERN_INVALID_ADDRESS at address: 0x0000000000000004
ErrorIfUnsupportedAlterTableStmt (alterTableStatement=0x7f959201b868) at executor/multi_utility.c:1598
1598					if (constraint->fk_attrs->length != constraint->pk_attrs->length)
(gdb) bt
#0  ErrorIfUnsupportedAlterTableStmt (alterTableStatement=0x7f959201b868) at executor/multi_utility.c:1598
#1  0x0000000101ac9039 in ProcessAlterTableStmt (alterTableStatement=0x7f959201b868, alterTableCommand=0x7f959201aa38 "ALTER TABLE ref_table ADD CONSTRAINT f_key FOREIGN KEY (key) REFERENCES main_table ON DELETE CASCADE;", isTopLevel=1 '\001') at executor/multi_utility.c:860
#2  0x0000000101ac7d9d in multi_ProcessUtility (parsetree=0x7f959201b868, queryString=0x7f959201aa38 "ALTER TABLE ref_table ADD CONSTRAINT f_key FOREIGN KEY (key) REFERENCES main_table ON DELETE CASCADE;", context=PROCESS_UTILITY_TOPLEVEL, params=0x0, dest=0x7f959201bbf0, completionTag=0x7fff5ed7a370 "") at executor/multi_utility.c:282
#3  0x00000001012af36c in ProcessUtility (parsetree=0x7f959201b868, queryString=0x7f959201aa38 "ALTER TABLE ref_table ADD CONSTRAINT f_key FOREIGN KEY (key) REFERENCES main_table ON DELETE CASCADE;", context=PROCESS_UTILITY_TOPLEVEL, params=0x0, dest=0x7f959201bbf0, completionTag=0x7fff5ed7a370 "") at utility.c:330
#4  0x00000001012aed08 in PortalRunUtility (portal=0x7f959109a038, utilityStmt=0x7f959201b868, isTopLevel=1 '\001', dest=0x7f959201bbf0, completionTag=0x7fff5ed7a370 "") at pquery.c:1183
#5  0x00000001012adf4c in PortalRunMulti (portal=0x7f959109a038, isTopLevel=1 '\001', dest=0x7f959201bbf0, altdest=0x7f959201bbf0, completionTag=0x7fff5ed7a370 "") at pquery.c:1314
#6  0x00000001012ad55d in PortalRun (portal=0x7f959109a038, count=9223372036854775807, isTopLevel=1 '\001', dest=0x7f959201bbf0, altdest=0x7f959201bbf0, completionTag=0x7fff5ed7a370 "") at pquery.c:812
#7  0x00000001012a8e27 in exec_simple_query (query_string=0x7f959201aa38 "ALTER TABLE ref_table ADD CONSTRAINT f_key FOREIGN KEY (key) REFERENCES main_table ON DELETE CASCADE;") at postgres.c:1104
#8  0x00000001012a8000 in PostgresMain (argc=1, argv=0x7f959181ac60, dbname=0x7f959181aac0 "postgres", username=0x7f95908025f0 "onderkalaci") at postgres.c:4030
#9  0x000000010120ff72 in BackendRun (port=0x7f9590602920) at postmaster.c:4239
#10 0x000000010120f22d in BackendStartup (port=0x7f9590602920) at postmaster.c:3913
#11 0x000000010120e305 in ServerLoop () at postmaster.c:1684
#12 0x000000010120bc09 in PostmasterMain (argc=3, argv=0x7f9590400d50) at postmaster.c:1292
#13 0x000000010114ca5f in main (argc=3, argv=0x7f9590400d50) at main.c:223

```

Citus should either error out (trivial) or behave similar to postgresql which is using the primary key of the referenced table automatically (slightly harder).

**Comment by ozgune** [comment]
@onderkalaci -- If we changed this to simply error out rather than crash, how quick would be the fix? (We'd still keep this issue open, but at least it wouldn't be a crash.)

**Comment by metdos** [comment]
> @onderkalaci -- If we changed this to simply error out rather than crash, how quick would be the fix? (We'd still keep this issue open, but at least it wouldn't be a crash.)

For the sake of being fast, I'm typing this :) 
It is very short (We talked about this with @onderkalaci) Though a suggestion about the error message would be nice!

**Comment by metdos** [comment]
@ozgune, @samay-sharma we closed this issue by adding an error message. From the product perspective, do you think to support this usage without requiring referenced column list is useful? Shall we reopen or create another issue for that?
