### ISSUE TITLE
check-vanilla in test suite crashes Citus

### ISSUE THREAD

**Issue by byucesoy** [citusdata/citus#1337]
Running `make check-vanilla` in `citus/src/test/regression` causes Citus to crash. You need to compile postgresql from source to be able run these tests.

It seems that this #1268 breaks the tests, but I did not dig into it.

**Comment by metdos** [comment]
Related to #1034.

**Comment by anarazel** [comment]
@onderkalaci looks like uninitialized memory usage, possibly due to memory context resets:
```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51                                                                                                                                            
#1  0x00007fdcc107c3fa in __GI_abort () at abort.c:89                                                                                                                                                                
#2  0x000000000092a387 in ExceptionalCondition (conditionName=0xae4eb8 "!(((list) == ((List *) ((void *)0)) || ((((const Node*)((list)))->type) == T_List)))", errorType=0xae4d99 "FailedAssertion",                 
    fileName=0xae4d60 "/home/andres/src/postgresql-9.5/src/backend/nodes/list.c", lineNumber=133) at /home/andres/src/postgresql-9.5/src/backend/utils/error/assert.c:54                                             
#3  0x00000000006c4644 in lappend (list=0x1159ee8, datum=0x1159ed8) at /home/andres/src/postgresql-9.5/src/backend/nodes/list.c:133                                                                                  
#4  0x00007fdcc0abb098 in multi_join_restriction_hook (root=0x11983d0, joinrel=0x1159698, outerrel=0x119e890, innerrel=0x119ebb8, jointype=JOIN_INNER, extra=0x7ffebbb889d0)                                         
    at /home/andres/src/citusdb/src/backend/distributed/planner/multi_planner.c:674                                                                                                                                  
#5  0x000000000070f0be in add_paths_to_joinrel (root=0x11983d0, joinrel=0x1159698, outerrel=0x119e890, innerrel=0x119ebb8, jointype=JOIN_INNER, sjinfo=0x7ffebbb88a60, restrictlist=0x1159a18)                       
    at /home/andres/src/postgresql-9.5/src/backend/optimizer/path/joinpath.c:222                                                                                                                                     
#6  0x00000000007116e6 in make_join_rel (root=0x11983d0, rel1=0x119e890, rel2=0x119ebb8) at /home/andres/src/postgresql-9.5/src/backend/optimizer/path/joinrels.c:754                                                
#7  0x00000000006f82ce in merge_clump (root=0x11983d0, clumps=0x1159578, new_clump=0x1159670, force=0 '\000') at /home/andres/src/postgresql-9.5/src/backend/optimizer/geqo/geqo_eval.c:262                          
#8  0x00000000006f8197 in gimme_tree (root=0x11983d0, tour=0x11a3bf0, num_gene=5) at /home/andres/src/postgresql-9.5/src/backend/optimizer/geqo/geqo_eval.c:201                                                      
#9  0x00000000006f8074 in geqo_eval (root=0x11983d0, tour=0x11a3bf0, num_gene=5) at /home/andres/src/postgresql-9.5/src/backend/optimizer/geqo/geqo_eval.c:104
#10 0x00000000006f8b14 in random_init_pool (root=0x11983d0, pool=0x11a3778) at /home/andres/src/postgresql-9.5/src/backend/optimizer/geqo/geqo_pool.c:109
#11 0x00000000006f8508 in geqo (root=0x11983d0, number_of_rels=5, initial_rels=0x11a36a0) at /home/andres/src/postgresql-9.5/src/backend/optimizer/geqo/geqo_main.c:114
#12 0x00000000006fd44c in make_rel_from_joinlist (root=0x11983d0, joinlist=0x119d578) at /home/andres/src/postgresql-9.5/src/backend/optimizer/path/allpaths.c:1739
#13 0x00000000006fb196 in make_one_rel (root=0x11983d0, joinlist=0x119d578) at /home/andres/src/postgresql-9.5/src/backend/optimizer/path/allpaths.c:169
#14 0x0000000000722940 in query_planner (root=0x11983d0, tlist=0x0, qp_callback=0x728249 <standard_qp_callback>, qp_extra=0x7ffebbb88ee0)
    at /home/andres/src/postgresql-9.5/src/backend/optimizer/plan/planmain.c:234
#15 0x000000000072522a in grouping_planner (root=0x11983d0, tuple_fraction=0) at /home/andres/src/postgresql-9.5/src/backend/optimizer/plan/planner.c:1553
#16 0x00000000007238b2 in subquery_planner (glob=0x11981d0, parse=0x11679e8, parent_root=0x0, hasRecursion=0 '\000', tuple_fraction=0, subroot=0x7ffebbb89258)
    at /home/andres/src/postgresql-9.5/src/backend/optimizer/plan/planner.c:630
#17 0x0000000000722bf2 in standard_planner (parse=0x11679e8, cursorOptions=0, boundParams=0x0) at /home/andres/src/postgresql-9.5/src/backend/optimizer/plan/planner.c:230
#18 0x00007fdcc0aba3aa in multi_planner (parse=0x11679e8, cursorOptions=0, boundParams=0x0) at /home/andres/src/citusdb/src/backend/distributed/planner/multi_planner.c:111
#19 0x0000000000722a31 in planner (parse=0x11679e8, cursorOptions=0, boundParams=0x0) at /home/andres/src/postgresql-9.5/src/backend/optimizer/plan/planner.c:156
#20 0x00000000007e528d in pg_plan_query (querytree=0x11679e8, cursorOptions=0, boundParams=0x0) at /home/andres/src/postgresql-9.5/src/backend/tcop/postgres.c:809
#21 0x00000000007e534d in pg_plan_queries (querytrees=0x1197f40, cursorOptions=0, boundParams=0x0) at /home/andres/src/postgresql-9.5/src/backend/tcop/postgres.c:868
#22 0x00000000007e55f2 in exec_simple_query (
    query_string=0x111bac8 "select count(*) from tenk1 x where\n  x.unique1 in (select a.f1 from int4_tbl a,float8_tbl b where a.f1=b.f1) and\n  x.unique1 = 0 and\n  x.unique1 in (select aa.f1 from int4_tbl aa,float8_tbl bb where a"...) at /home/andres/src/postgresql-9.5/src/backend/tcop/postgres.c:1033
#23 0x00000000007e980e in PostgresMain (argc=1, argv=0x108f270, dbname=0x108efd0 "regression", username=0x108efa8 "postgres") at /home/andres/src/postgresql-9.5/src/backend/tcop/postgres.c:4051
#24 0x0000000000768338 in BackendRun (port=0x10bc8e0) at /home/andres/src/postgresql-9.5/src/backend/postmaster/postmaster.c:4254
#25 0x0000000000767a9c in BackendStartup (port=0x10bc8e0) at /home/andres/src/postgresql-9.5/src/backend/postmaster/postmaster.c:3928
#26 0x00000000007642f2 in ServerLoop () at /home/andres/src/postgresql-9.5/src/backend/postmaster/postmaster.c:1698
#27 0x0000000000763927 in PostmasterMain (argc=25, argv=0x108d5d0) at /home/andres/src/postgresql-9.5/src/backend/postmaster/postmaster.c:1306
#28 0x00000000006bc2fa in main (argc=25, argv=0x108d5d0) at /home/andres/src/postgresql-9.5/src/backend/main/main.c:228

(gdb) up 4
#4  0x00007fdcc0abb098 in multi_join_restriction_hook (root=0x11983d0, joinrel=0x1159698, outerrel=0x119e890, innerrel=0x119ebb8, jointype=JOIN_INNER, extra=0x7ffebbb889d0)
    at /home/andres/src/citusdb/src/backend/distributed/planner/multi_planner.c:674
674                     lappend(joinContext->joinRestrictionList, joinRestriction);
(gdb) p joinContext->joinRestrictionList
$1 = (List *) 0x1159ee8
(gdb) p *joinContext->joinRestrictionList
$2 = {type = 18449360, length = 0, head = 0x7f7f7f7f7f7f7f7e, tail = 0x7f7f7f7f7f7f7f7f}
```

(note 0x7f is what postgres sets uninitialized & freed memory too, and 0x7e is the "end" marker of an allocation)

**Comment by anarazel** [comment]
@onderkalaci Assigning to you, since it's been triggered by one of your PRs.  This is blocking some other, not super urgent, work...
