### ISSUE TITLE
master_create_empty_shard without existing nodes crashes.

### ISSUE THREAD

**Issue by anarazel** [citusdata/citus#1367]
```
(gdb) bt
#0  0x00007fbe44bdf02e in WorkerGetLiveNodeCount () at /home/andres/src/citusdb/src/backend/distributed/master/worker_node_manager.c:306
#1  0x00007fbe44bdd5e2 in master_create_empty_shard (fcinfo=0x164c910)
    at /home/andres/src/citusdb/src/backend/distributed/master/master_stage_protocol.c:144
#2  0x000000000066f2f1 in ExecMakeFunctionResultNoSets (fcache=0x164c8a0, econtext=0x164c678, 
    isNull=0x164d2e8 "\177~\177\177\177\177\177\177\370\252d\001", isDone=0x164d428)
    at /home/andres/src/postgresql-9.5/src/backend/executor/execQual.c:2019
#3  0x000000000066fc0d in ExecEvalFunc (fcache=0x164c8a0, econtext=0x164c678, 
    isNull=0x164d2e8 "\177~\177\177\177\177\177\177\370\252d\001", isDone=0x164d428)
    at /home/andres/src/postgresql-9.5/src/backend/executor/execQual.c:2410
#4  0x0000000000676229 in ExecTargetList (targetlist=0x164d3f0, tupdesc=0x164d1b0, econtext=0x164c678, values=0x164d2c8, 
    isnull=0x164d2e8 "\177~\177\177\177\177\177\177\370\252d\001", itemIsDone=0x164d428, isDone=0x7ffd11474fa4)
    at /home/andres/src/postgresql-9.5/src/backend/executor/execQual.c:5416
#5  0x000000000067696e in ExecProject (projInfo=0x164d308, isDone=0x7ffd11474fa4)
    at /home/andres/src/postgresql-9.5/src/backend/executor/execQual.c:5640
#6  0x0000000000694498 in ExecResult (node=0x164c560) at /home/andres/src/postgresql-9.5/src/backend/executor/nodeResult.c:155
#7  0x000000000066b92c in ExecProcNode (node=0x164c560) at /home/andres/src/postgresql-9.5/src/backend/executor/execProcnode.c:385
#8  0x0000000000668ee6 in ExecutePlan (estate=0x164c448, planstate=0x164c560, operation=CMD_SELECT, sendTuples=1 '\001', numberTuples=0, 
    direction=ForwardScanDirection, dest=0x1663fc8) at /home/andres/src/postgresql-9.5/src/backend/executor/execMain.c:1549
#9  0x0000000000666fd1 in standard_ExecutorRun (queryDesc=0x1642358, direction=ForwardScanDirection, count=0)
    at /home/andres/src/postgresql-9.5/src/backend/executor/execMain.c:337
#10 0x00007fbe44763641 in pgss_ExecutorRun (queryDesc=0x1642358, direction=ForwardScanDirection, count=0)
    at /home/andres/src/postgresql-9.5/contrib/pg_stat_statements/pg_stat_statements.c:881
#11 0x0000000000666e4c in ExecutorRun (queryDesc=0x1642358, direction=ForwardScanDirection, count=0)
    at /home/andres/src/postgresql-9.5/src/backend/executor/execMain.c:283
#12 0x00000000007eb81f in PortalRunSelect (portal=0x1567db8, forward=1 '\001', count=0, dest=0x1663fc8)
---Type <return> to continue, or q <return> to quit---
    at /home/andres/src/postgresql-9.5/src/backend/tcop/pquery.c:942
#13 0x00000000007eb4cf in PortalRun (portal=0x1567db8, count=9223372036854775807, isTopLevel=1 '\001', dest=0x1663fc8, altdest=0x1663fc8, 
    completionTag=0x7ffd114753e0 "") at /home/andres/src/postgresql-9.5/src/backend/tcop/pquery.c:786
#14 0x00000000007e574e in exec_simple_query (query_string=0x15f1a78 "SELECT master_create_empty_shard('lineitem_subquery') AS new_shard_id")
    at /home/andres/src/postgresql-9.5/src/backend/tcop/postgres.c:1104
#15 0x00000000007e980e in PostgresMain (argc=1, argv=0x1549e58, dbname=0x1549cb8 "postgres", username=0x1549c90 "postgres")
    at /home/andres/src/postgresql-9.5/src/backend/tcop/postgres.c:4051
#16 0x0000000000768338 in BackendRun (port=0x1577950) at /home/andres/src/postgresql-9.5/src/backend/postmaster/postmaster.c:4254
#17 0x0000000000767a9c in BackendStartup (port=0x1577950) at /home/andres/src/postgresql-9.5/src/backend/postmaster/postmaster.c:3928
#18 0x00000000007642f2 in ServerLoop () at /home/andres/src/postgresql-9.5/src/backend/postmaster/postmaster.c:1698
#19 0x0000000000763927 in PostmasterMain (argc=17, argv=0x15483c0)
    at /home/andres/src/postgresql-9.5/src/backend/postmaster/postmaster.c:1306
#20 0x00000000006bc2fa in main (argc=17, argv=0x15483c0) at /home/andres/src/postgresql-9.5/src/backend/main/main.c:228

#0  0x00007fbe44bdf02e in WorkerGetLiveNodeCount () at /home/andres/src/citusdb/src/backend/distributed/master/worker_node_manager.c:306
306             uint32 liveWorkerCount = workerNodeList->length;
(gdb) p workerNodeList
$2 = (List *) 0x0
```

**Comment by anarazel** [comment]
(assignees chosen by my memory of who touched the relevant code last, might be completely inaccurate)

**Comment by onderkalaci** [comment]
Seems #1283 @byucesoy.
