### ISSUE TITLE
intermittent crashes possibly related to stats commit

### ISSUE THREAD

**Issue by mtuncer** [citusdata/citus#1697]
Observing postmaster crashes after running few queries.
Easiest repro is to run ```\dx``` . Postmaster crashes after few runs.

It looks like it started happening after #1656 . 
setting citus.enable_statistics_collection to false seem to fix it.

**Comment by onderkalaci** [comment]
Verified that related to statistics collection:

backtrace:
```
#0  0x00007fff9564c8c8 in curl_slist_free_all ()
(gdb) bt
#0  0x00007fff9564c8c8 in curl_slist_free_all ()
#1  0x000000010e0ce686 in SendHttpPostJsonRequest (url=0x10e0eddf9 "https://citus-statistics.herokuapp.com/v1/usage_reports", jsonObj=0x7f9a8b893a70 "{\"citus_version\": \"7.1devel\",\"table_count\": 4,\"cluster_size\": 2097152,\"worker_node_count\": 3,\"os_name\": \"Darwin\",\"os_release\": \"15.6.0\",\"hwid\": \"x86_64\"}", timeoutSeconds=5) at utils/statistics_collection.c:203
#2  0x000000010e0ce187 in CollectBasicUsageStatistics () at utils/statistics_collection.c:88
#3  0x000000010e0afd1c in CitusMaintenanceDaemonMain ()
#4  0x000000010d749b64 in StartBackgroundWorker () at bgworker.c:725
#5  0x000000010d75ff77 in do_start_bgworker (rw=0x7f9a89e009d0) at postmaster.c:5537
#6  0x000000010d75ae7b in maybe_start_bgworker () at postmaster.c:5712
#7  0x000000010d7595be in sigusr1_handler (postgres_signal_arg=30) at postmaster.c:4959
#8  <signal handler called>
#9  0x00007fff8d50607a in select$DARWIN_EXTSN ()
#10 0x000000010d75affc in ServerLoop () at postmaster.c:1665
#11 0x000000010d758966 in PostmasterMain (argc=3, argv=0x7f9a89c036d0) at postmaster.c:1309
#12 0x000000010d68959f in main (argc=3, argv=0x7f9a89c036d0) at main.c:228

```
