### ISSUE TITLE
Assert failure in FinishRemoteTransactionAbort in cancellation test

### ISSUE THREAD

**Issue by marcocitus** [citusdata/citus#1966]
I'm setting up a CentOS 7.4 VM for development.

When I run `make check` on the `master` branch, I get the following assert failure: 
```
TRAP: FailedAssertion("!(!result)", File: "transaction/remote_transaction.c", Line: 439)
```
Line: https://github.com/citusdata/citus/blob/master/src/backend/distributed/transaction/remote_transaction.c#L439  

It's triggered by a cancellation test in `multi_real_time_transaction.sql`:

```
BEGIN;
SELECT id, pg_advisory_lock(15) FROM test_table;
ERROR:  canceling the transaction since it was involved in a distributed deadlock
ROLLBACK;
BEGIN;
SELECT id, pg_advisory_lock(15) FROM test_table;
ERROR:  canceling the transaction since it was involved in a distributed deadlock
ROLLBACK;
BEGIN;
SELECT id, pg_advisory_lock(15) FROM test_table;
ERROR:  canceling the transaction since it was involved in a distributed deadlock
ROLLBACK;
BEGIN;
SELECT id, pg_advisory_lock(15) FROM test_table;
ERROR:  canceling the transaction since it was involved in a distributed deadlock
ROLLBACK;
BEGIN;
SELECT id, pg_advisory_lock(15) FROM test_table;
ERROR:  canceling the transaction since it was involved in a distributed deadlock
server closed the connection unexpectedly
    This probably means the server terminated abnormally
    before or while processing the request.
connection to server was lost
```

**Comment by onderkalaci** [comment]
I've seen this on travis as well

**Comment by onderkalaci** [comment]
Hit this again on Travis

**Comment by jasonmp85** [comment]
I think I'm still seeing this (maybe in Windows?)

**Comment by onderkalaci** [comment]
I've seen this came-up in `tpcb-like` pgbench on 1+8 c4.4xlarge cluster, with the following command ` pssh  -t 0  -h all_workers.txt -A -i -l ec2-user "pg-latest/bin/pgbench -T 4800 -j32 -c32 -n  -b tpcb-like" `. 

The bt:
```
#0  0x00007f981a747277 in raise () from /lib64/libc.so.6
#1  0x00007f981a748968 in abort () from /lib64/libc.so.6
#2  0x0000000000872526 in ExceptionalCondition (conditionName=conditionName@entry=0x7f9812bf230a "!(!result)", errorType=errorType@entry=0x7f9812be0b37 "FailedAssertion", fileName=fileName@entry=0x7f9812bf2318 "transaction/remote_transaction.c", 
    lineNumber=lineNumber@entry=532) at assert.c:54
#3  0x00007f9812bb872b in FinishRemoteTransactionPrepare (connection=connection@entry=0x2c18a68) at transaction/remote_transaction.c:532
#4  0x00007f9812bb8b2b in CoordinatedRemoteTransactionsPrepare () at transaction/remote_transaction.c:817
#5  0x00007f9812bb9376 in CoordinatedTransactionCallback (event=<optimized out>, arg=<optimized out>) at transaction/transaction_management.c:316
#6  0x0000000000509191 in CallXactCallbacks (event=XACT_EVENT_PRE_COMMIT) at xact.c:3347
#7  0x000000000050ce2e in CommitTransaction () at xact.c:1984
#8  0x000000000050da64 in CommitTransactionCommand () at xact.c:2802
#9  0x000000000076c50f in finish_xact_command () at postgres.c:2459
#10 0x000000000076e4de in exec_simple_query (query_string=query_string@entry=0x2b4e3b0 "END;") at postgres.c:1117
#11 0x00000000007705a0 in PostgresMain (argc=<optimized out>, argv=argv@entry=0x2acddb0, dbname=<optimized out>, username=<optimized out>) at postgres.c:4088
#12 0x00000000006f66a0 in BackendRun (port=port@entry=0x2ac7870) at postmaster.c:4405
#13 0x00000000006f85d1 in BackendStartup (port=port@entry=0x2ac7870) at postmaster.c:4077
#14 0x00000000006f889f in ServerLoop () at postmaster.c:1755
#15 0x00000000006f9b5c in PostmasterMain (argc=argc@entry=3, argv=argv@entry=0x2a628c0) at postmaster.c:1363
#16 0x000000000066dce9 in main (argc=3, argv=0x2a628c0) at main.c:228

```
Note that the transation state is `REMOTE_TRANS_ABORTED `:
```
(gdb) p *(MultiConnection *)0x18c5750
$4 = {hostname = "10.192.0.97", '\000' <repeats 243 times>, port = 5432, user = "ec2-user", '\000' <repeats 55 times>, database = "ec2-user", '\000' <repeats 55 times>, pgConn = 0x187ae00, sessionLifespan = 1 '\001', claimedExclusively = 0 '\000', 
  connectionStart = 589972887296507, connectionNode = {prev = 0x18a88d0, next = 0x18a88d0}, remoteTransaction = {transactionState = REMOTE_TRANS_ABORTED, transactionCritical = 0 '\000', transactionFailed = 1 '\001', lastSuccessfulSubXact = 1, lastQueuedSubXact = 1, 
    transactionRecovering = 0 '\000', preparedName = "citus_4_61671_14864_62", '\000' <repeats 41 times>}, transactionNode = {prev = 0x7f2787933680 <InProgressTransactions>, next = 0x18a7040}, referencedPlacements = {head = {prev = 0x1756e18, next = 0x1756e18}}, 
  copyBytesWrittenSinceLastFlush = 0}
```


And, the logs:
```
TRAP: FailedAssertion("!(!result)", File: "transaction/remote_transaction.c", Line: 532)
TRAP: FailedAssertion("!(!result)", File: "transaction/remote_transaction.c", Line: 532)
TRAP: FailedAssertion("!(!result)", File: "transaction/remote_transaction.c", Line: 532)
TRAP: FailedAssertion("!(!result)", File: "transaction/remote_transaction.c", Line: 532)
TRAP: FailedAssertion("!(!result)", File: "transaction/remote_transaction.c", Line: 532)
```
