### ISSUE TITLE
cartesian product joins that comes after dual/single repartition joins crashes the server

### ISSUE THREAD

**Issue by onderkalaci** [citusdata/citus#2074]
Probably not a realistic/interesting use-case. But, still worth opening an issue.

Steps to re-produce. Could be re-produced with range partitioned tables with single re-partitioning as well.

```SQL
CREATE TABLE single_hash_repartition_first (id int, sum int, avg float);
CREATE TABLE single_hash_repartition_second (id int, sum int, avg float);

SET citus.shard_count TO 4;

SELECT create_distributed_table('single_hash_repartition_first', 'id');
SELECT create_distributed_table('single_hash_repartition_second', 'id');

SET citus.log_multi_join_order TO ON;
SET client_min_messages TO DEBUG2;

EXPLAIN SELECT 
	count(*) 
FROM
	single_hash_repartition_first t1, single_hash_repartition_first t2, single_hash_repartition_second t3
WHERE
	t1.sum = t2.sum AND t1.avg = t3.id;

DEBUG:  dual partition column types do not match
DEBUG:  dual partition column types do not match
DEBUG:  dual partition column types do not match
DEBUG:  dual partition column types do not match
LOG:  join order: [ "single_hash_repartition_first" ][ dual partition join "single_hash_repartition_first" ][ cartesian product "single_hash_repartition_second" ]
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
!> 
```

And the bt:
```
Program received signal SIGABRT, Aborted.
0x00007fff96084f06 in __pthread_kill ()
(gdb) bt
#0  0x00007fff96084f06 in __pthread_kill ()
#1  0x00007fff92f4a4ec in pthread_kill ()
#2  0x00007fff9d7746df in abort ()
#3  0x0000000104190900 in ExceptionalCondition (conditionName=0x10496fe65 "!(list_length(projectNodeList) > 0)", errorType=0x1049641d3 "FailedAssertion", fileName=0x10496fb0a "planner/multi_physical_planner.c", lineNumber=921) at assert.c:54
#4  0x000000010490d627 in QueryTargetList (multiNode=0x7f96dc03f1d8) at planner/multi_physical_planner.c:921
#5  0x000000010490a26b in BuildJobQuery (multiNode=0x7f96dc03f1d8, dependedJobList=0x0) at planner/multi_physical_planner.c:636
#6  0x0000000104909b4f in BuildJobTree (multiTree=0x7f96dc046998) at planner/multi_physical_planner.c:369
#7  0x00000001049098a9 in CreatePhysicalDistributedPlan (multiTree=0x7f96dc046998, plannerRestrictionContext=0x7f96db81c440) at planner/multi_physical_planner.c:216
#8  0x00000001048f504c in CreateDistributedSelectPlan (planId=1, originalQuery=0x7f96dc01bfb0, query=0x7f96dc004858, boundParams=0x0, hasUnresolvedParams=0 '\0', plannerRestrictionContext=0x7f96db81c440) at planner/distributed_planner.c:726
#9  0x00000001048f3c48 in CreateDistributedPlan (planId=1, localPlan=0x7f96dc03b850, originalQuery=0x7f96dc01bfb0, query=0x7f96dc004858, boundParams=0x0, plannerRestrictionContext=0x7f96db81c440) at planner/distributed_planner.c:513
#10 0x00000001048f3740 in distributed_planner (parse=0x7f96dc004858, cursorOptions=256, boundParams=0x0) at planner/distributed_planner.c:149
#11 0x0000000103ec63f5 in planner (parse=0x7f96dc004858, cursorOptions=256, boundParams=0x0) at planner.c:208
#12 0x0000000103fd5949 in pg_plan_query (querytree=0x7f96dc004858, cursorOptions=256, boundParams=0x0) at postgres.c:796
#13 0x0000000103d32a8e in ExplainOneQuery (query=0x7f96dc004858, cursorOptions=256, into=0x0, es=0x7f96dc007928, queryString=0x7f96db020a40 "EXPLAIN SELECT \ncount(*) \nFROM\nsingle_hash_repartition_first t1, single_hash_repartition_first t2, single_hash_repartition_second t3\nWHERE\nt1.sum = t2.sum AND t1.avg = t3.id;", params=0x0, queryEnv=0x0) at explain.c:367
#14 0x0000000103d326ec in ExplainQuery (pstate=0x7f96dc007810, stmt=0x7f96db022350, queryString=0x7f96db020a40 "EXPLAIN SELECT \ncount(*) \nFROM\nsingle_hash_repartition_first t1, single_hash_repartition_first t2, single_hash_repartition_second t3\nWHERE\nt1.sum = t2.sum AND t1.avg = t3.id;", params=0x0, queryEnv=0x0, dest=0x7f96dc007778) at explain.c:256
#15 0x0000000103fdf7c8 in standard_ProcessUtility (pstmt=0x7f96dc0101e8, queryString=0x7f96db020a40 "EXPLAIN SELECT \ncount(*) \nFROM\nsingle_hash_repartition_first t1, single_hash_repartition_first t2, single_hash_repartition_second t3\nWHERE\nt1.sum = t2.sum AND t1.avg = t3.id;", context=PROCESS_UTILITY_TOPLEVEL, params=0x0, queryEnv=0x0, dest=0x7f96dc007778, completionTag=0x7fff5c0e30f0 "") at utility.c:680
#16 0x00000001048ddd10 in multi_ProcessUtility (pstmt=0x7f96dc0101e8, queryString=0x7f96db020a40 "EXPLAIN SELECT \ncount(*) \nFROM\nsingle_hash_repartition_first t1, single_hash_repartition_first t2, single_hash_repartition_second t3\nWHERE\nt1.sum = t2.sum AND t1.avg = t3.id;", context=PROCESS_UTILITY_TOPLEVEL, params=0x0, queryEnv=0x0, dest=0x7f96dc007778, completionTag=0x7fff5c0e30f0 "") at executor/multi_utility.c:483
#17 0x0000000104a6bb78 in pgss_ProcessUtility (pstmt=0x7f96dc0101e8, queryString=0x7f96db020a40 "EXPLAIN SELECT \ncount(*) \nFROM\nsingle_hash_repartition_first t1, single_hash_repartition_first t2, single_hash_repartition_second t3\nWHERE\nt1.sum = t2.sum AND t1.avg = t3.id;", context=PROCESS_UTILITY_TOPLEVEL, params=0x0, queryEnv=0x0, dest=0x7f96dc007778, completionTag=0x7fff5c0e30f0 "") at pg_stat_statements.c:998
#18 0x0000000103fdef6c in ProcessUtility (pstmt=0x7f96dc0101e8, queryString=0x7f96db020a40 "EXPLAIN SELECT \ncount(*) \nFROM\nsingle_hash_repartition_first t1, single_hash_repartition_first t2, single_hash_repartition_second t3\nWHERE\nt1.sum = t2.sum AND t1.avg = t3.id;", context=PROCESS_UTILITY_TOPLEVEL, params=0x0, queryEnv=0x0, dest=0x7f96dc007778, completionTag=0x7fff5c0e30f0 "") at utility.c:353
#19 0x0000000103fde868 in PortalRunUtility (portal=0x7f96db05f240, pstmt=0x7f96dc0101e8, isTopLevel=1 '\001', setHoldSnapshot=1 '\001', dest=0x7f96dc007778, completionTag=0x7fff5c0e30f0 "") at pquery.c:1178
#20 0x0000000103fdd412 in FillPortalStore (portal=0x7f96db05f240, isTopLevel=1 '\001') at pquery.c:1038
#21 0x0000000103fdcf8b in PortalRun (portal=0x7f96db05f240, count=9223372036854775807, isTopLevel=1 '\001', run_once=1 '\001', dest=0x7f96dc00ec40, altdest=0x7f96dc00ec40, completionTag=0x7fff5c0e33c0 "") at pquery.c:768
#22 0x0000000103fd892c in exec_simple_query (query_string=0x7f96db020a40 "EXPLAIN SELECT \ncount(*) \nFROM\nsingle_hash_repartition_first t1, single_hash_repartition_first t2, single_hash_repartition_second t3\nWHERE\nt1.sum = t2.sum AND t1.avg = t3.id;") at postgres.c:1099
#23 0x0000000103fd7b37 in PostgresMain (argc=1, argv=0x7f96dc00b288, dbname=0x7f96dc00b0e8 "postgres", username=0x7f96dc00b0c0 "onderkalaci") at postgres.c:4088
#24 0x0000000103f1e50e in BackendRun (port=0x7f96dae072d0) at postmaster.c:4405
#25 0x0000000103f1d893 in BackendStartup (port=0x7f96dae072d0) at postmaster.c:4077
#26 0x0000000103f1c885 in ServerLoop () at postmaster.c:1755
#27 0x0000000103f1a041 in PostmasterMain (argc=3, argv=0x7f96dac022c0) at postmaster.c:1363
#28 0x0000000103e3df89 in main (argc=3, argv=0x7f96dac022c0) at main.c:228
```

**Comment by marcocitus** [comment]
This no longer seems to be an issue, the query errors out with:
```
ERROR:  cannot perform distributed planning on this query
DETAIL:  Cartesian products are currently unsupported
```
