### ISSUE TITLE
Error when passing aggregate to set-returning function

### ISSUE THREAD

**Issue by marcocitus** [citusdata/citus#2076]
In a distributed query, we give an odd syntax error when passing an aggregate as a parameter to a set-returning function.

```
CREATE TABLE test (x int, y int);                                                                                                                       
INSERT INTO test VALUES (1,2);
SELECT generate_series(1,count(*)) FROM test;
 generate_series 
─────────────────
               1
(1 row)

SELECT create_distributed_table('test', 'x');
SELECT generate_series(1,count(*)) FROM test;
ERROR:  set-valued function called in context that cannot accept a set
LINE 1: SELECT generate_series(1,count(*)) FROM test;
               ^
```

**Comment by marcocitus** [comment]
Stack trace: 
```
#1  0x00000000005de737 in ExecInitFunc (scratch=scratch@entry=0x7ffce240dec0, node=node@entry=0x1045c80, args=0x1045cd0, funcid=1069, inputcollid=0, 
    parent=parent@entry=0xe21db8, state=state@entry=0xe22f58) at execExpr.c:2119
#2  0x00000000005dc96d in ExecInitExprRec (node=0x1045c80, parent=parent@entry=0xe21db8, state=state@entry=0xe22f58, resv=resv@entry=0xe22f60, 
    resnull=resnull@entry=0xe22f5d "") at execExpr.c:806
#3  0x00000000005ded2b in ExecBuildProjectionInfo (targetList=<optimized out>, econtext=<optimized out>, slot=<optimized out>, parent=parent@entry=0xe21db8, 
    inputDesc=inputDesc@entry=0x0) at execExpr.c:401
#4  0x00000000005ece99 in ExecAssignProjectionInfo (planstate=planstate@entry=0xe21db8, inputDesc=inputDesc@entry=0x0) at execUtils.c:498
#5  0x00000000005f2e9d in ExecInitAgg (node=node@entry=0x1047eb0, estate=estate@entry=0xe21ba8, eflags=eflags@entry=16) at nodeAgg.c:2874
#6  0x00000000005e95a1 in ExecInitNode (node=node@entry=0x1047eb0, estate=estate@entry=0xe21ba8, eflags=eflags@entry=16) at execProcnode.c:323
#7  0x00000000005e6610 in InitPlan (queryDesc=queryDesc@entry=0xe63a88, eflags=eflags@entry=16) at execMain.c:1045
#8  0x00000000005e67f5 in standard_ExecutorStart (queryDesc=0xe63a88, eflags=16) at execMain.c:264
#9  0x00000000005e6825 in ExecutorStart (queryDesc=queryDesc@entry=0xe63a88, eflags=eflags@entry=0) at execMain.c:152
#10 0x000000000070c897 in PortalStart (portal=portal@entry=0xe64718, params=params@entry=0x0, eflags=eflags@entry=0, snapshot=snapshot@entry=0x0) at pquery.c:520
#11 0x0000000000709713 in exec_simple_query (query_string=query_string@entry=0xdba8d8 "SELECT generate_series(1,count(*)) FROM test;") at postgres.c:1060
#12 0x000000000070b2da in PostgresMain (argc=<optimized out>, argv=argv@entry=0xd58118, dbname=0xd57ff8 "postgres", username=<optimized out>) at postgres.c:4088
#13 0x00000000006a32ac in BackendRun (port=port@entry=0xd4e780) at postmaster.c:4405
#14 0x00000000006a4d93 in BackendStartup (port=port@entry=0xd4e780) at postmaster.c:4077
#15 0x00000000006a503c in ServerLoop () at postmaster.c:1755
#16 0x00000000006a621a in PostmasterMain (argc=argc@entry=3, argv=argv@entry=0xd07ab0) at postmaster.c:1363
#17 0x0000000000623c88 in main (argc=3, argv=0xd07ab0) at main.c:228
```
