### ISSUE TITLE
Creating primary key on partitioned table fails if Citus extension is installed on PG 11

### ISSUE THREAD

**Issue by onderkalaci** [citusdata/citus#2390]
Seems like a must have for 8.0.

Without Citus being installed:

```SQL
SELECT version();
                                                     version                                                      
------------------------------------------------------------------------------------------------------------------
 PostgreSQL 11beta3 on x86_64-apple-darwin15.6.0, compiled by Apple LLVM version 8.0.0 (clang-800.0.42.1), 64-bit
(1 row)

-- citus is not installed
-- both tables are created successfully
\dx
                                     List of installed extensions
        Name        | Version |   Schema   |                        Description                        
--------------------+---------+------------+-----------------------------------------------------------
 pg_stat_statements | 1.5     | public     | track execution statistics of all SQL statements executed
 plpgsql            | 1.0     | pg_catalog | PL/pgSQL procedural language
(2 rows)

CREATE TABLE collections_list (
	key bigint,
	ts timestamptz,
	collection_id integer,
	value numeric,
	PRIMARY KEY(collection_id)
) PARTITION BY LIST ( collection_id );

CREATE TABLE collections_list_1 
	PARTITION OF collections_list (key, ts, collection_id, value)
	FOR VALUES IN ( 1 );
```

With Citus being installed:
```SQL
CREATE EXTENSION citus;
SELECT citus_version();
                                                citus_version                                                 
--------------------------------------------------------------------------------------------------------------
 Citus 8.0devel on x86_64-apple-darwin15.6.0, compiled by Apple LLVM version 8.0.0 (clang-800.0.42.1), 64-bit

CREATE TABLE collections_list (
	key bigint,
	ts timestamptz,
	collection_id integer,
	value numeric,
	PRIMARY KEY(collection_id)
) PARTITION BY LIST ( collection_id );


CREATE TABLE collections_list_1 
	PARTITION OF collections_list (key, ts, collection_id, value)
	FOR VALUES IN ( 1 );
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
!> 
```

The backtrace:
```
Program received signal EXC_BAD_ACCESS, Could not access memory.
Reason: KERN_INVALID_ADDRESS at address: 0x0000000000000010
EventTriggerAlterTableRelid (objectId=32768) at event_trigger.c:1745
1745		currentEventTriggerState->currentCommand->d.alterTable.objectId = objectId;
(gdb) bt
#0  EventTriggerAlterTableRelid (objectId=32768) at event_trigger.c:1745
#1  0x0000000106a467e9 in AlterTableInternal (relid=32768, cmds=0x7fe9128be418, recurse=true) at tablecmds.c:3328
#2  0x000000010690c046 in index_check_primary_key (heapRel=0x1074668e0, indexInfo=0x7fe9128bd588, is_alter_table=false) at index.c:283
#3  0x0000000106a1b073 in DefineIndex (relationId=32768, stmt=0x7fe912051350, indexRelationId=0, parentIndexId=24579, parentConstraintId=24580, is_alter_table=false, check_rights=false, check_not_in_use=false, skip_build=false, quiet=false) at indexcmds.c:669
#4  0x0000000106a400d9 in DefineRelation (stmt=0x7fe912001430, relkind=114 'r', ownerId=10, typaddress=0x0, queryString=0x7fe912018b18 "CREATE TABLE collections_1 \nPARTITION OF collections (key, ts, collection_id, value)\nFOR VALUES IN ( 1 );") at tablecmds.c:946
#5  0x0000000106cdfb94 in ProcessUtilitySlow (pstate=0x7fe912001318, pstmt=0x7fe912019d18, queryString=0x7fe912018b18 "CREATE TABLE collections_1 \nPARTITION OF collections (key, ts, collection_id, value)\nFOR VALUES IN ( 1 );", context=PROCESS_UTILITY_TOPLEVEL, params=0x0, queryEnv=0x0, dest=0x7fe91201a008, completionTag=0x7fff59426350 "") at utility.c:1000
#6  0x0000000106cdf3f7 in standard_ProcessUtility (pstmt=0x7fe912019d18, queryString=0x7fe912018b18 "CREATE TABLE collections_1 \nPARTITION OF collections (key, ts, collection_id, value)\nFOR VALUES IN ( 1 );", context=PROCESS_UTILITY_TOPLEVEL, params=0x0, queryEnv=0x0, dest=0x7fe91201a008, completionTag=0x7fff59426350 "") at utility.c:920
#7  0x0000000107625b90 in multi_ProcessUtility (pstmt=0x7fe912019d18, queryString=0x7fe912018b18 "CREATE TABLE collections_1 \nPARTITION OF collections (key, ts, collection_id, value)\nFOR VALUES IN ( 1 );", context=PROCESS_UTILITY_TOPLEVEL, params=0x0, queryEnv=0x0, dest=0x7fe91201a008, completionTag=0x7fff59426350 "") at executor/multi_utility.c:552
#8  0x00000001077d9c05 in pgss_ProcessUtility (pstmt=0x7fe912019d18, queryString=0x7fe912018b18 "CREATE TABLE collections_1 \nPARTITION OF collections (key, ts, collection_id, value)\nFOR VALUES IN ( 1 );", context=PROCESS_UTILITY_TOPLEVEL, params=0x0, queryEnv=0x0, dest=0x7fe91201a008, completionTag=0x7fff59426350 "") at pg_stat_statements.c:1001
#9  0x0000000106cde39c in ProcessUtility (pstmt=0x7fe912019d18, queryString=0x7fe912018b18 "CREATE TABLE collections_1 \nPARTITION OF collections (key, ts, collection_id, value)\nFOR VALUES IN ( 1 );", context=PROCESS_UTILITY_TOPLEVEL, params=0x0, queryEnv=0x0, dest=0x7fe91201a008, completionTag=0x7fff59426350 "") at utility.c:356
#10 0x0000000106cddc7d in PortalRunUtility (portal=0x7fe912846518, pstmt=0x7fe912019d18, isTopLevel=true, setHoldSnapshot=false, dest=0x7fe91201a008, completionTag=0x7fff59426350 "") at pquery.c:1178
#11 0x0000000106cdce9e in PortalRunMulti (portal=0x7fe912846518, isTopLevel=true, setHoldSnapshot=false, dest=0x7fe91201a008, altdest=0x7fe91201a008, completionTag=0x7fff59426350 "") at pquery.c:1324
#12 0x0000000106cdc4d1 in PortalRun (portal=0x7fe912846518, count=9223372036854775807, isTopLevel=true, run_once=true, dest=0x7fe91201a008, altdest=0x7fe91201a008, completionTag=0x7fff59426350 "") at pquery.c:799
#13 0x0000000106cd79c8 in exec_simple_query (query_string=0x7fe912018b18 "CREATE TABLE collections_1 \nPARTITION OF collections (key, ts, collection_id, value)\nFOR VALUES IN ( 1 );") at postgres.c:1122
#14 0x0000000106cd6b65 in PostgresMain (argc=1, argv=0x7fe912810900, dbname=0x7fe912810798 "postgres", username=0x7fe912810770 "onderkalaci") at postgres.c:4159
#15 0x0000000106c161ad in BackendRun (port=0x7fe911e05d10) at postmaster.c:4361
#16 0x0000000106c15518 in BackendStartup (port=0x7fe911e05d10) at postmaster.c:4033
#17 0x0000000106c1448a in ServerLoop () at postmaster.c:1706
#18 0x0000000106c11eb2 in PostmasterMain (argc=3, argv=0x7fe911c03620) at postmaster.c:1379
#19 0x0000000106b1d6e9 in main (argc=3, argv=0x7fe911c03620) at main.c:228
Current language:  auto; currently minimal
```

This happens for other type of distribution methods (e.g., range and hash). 

Note that other syntax for creating partitions (e.g., `CREATE TABLE` followed by `ATTACH PARTITION`) doesn't lead to this situation.

**Comment by marcocitus** [comment]
That seems like a postgres bug.

**Comment by onderkalaci** [comment]
> That seems like a postgres bug.

Marco sent an email to the hackers list about the issue:
https://www.postgresql.org/message-id/CANNhMLCpi%2BHQ7M36uPfGbJZEQLyTy7XvX%3D5EFkpR-b1bo0uJew%40mail.gmail.com

**Comment by lfittl** [comment]
This should be fixed with Postgres 11 rc1 ([1a852f7c1e27eef563cf0577c2604baec1be5512](https://git.postgresql.org/gitweb/?p=postgresql.git;a=commit;h=1a852f7c1e27eef563cf0577c2604baec1be5512) pushed on October 7th) - @onderkalaci @marcocitus could you re-test this?
