### ISSUE TITLE
Citus may crash due to wrong memory access while reading worker tuples from metadata

### ISSUE THREAD

**Issue by onderkalaci** [citusdata/citus#2552]
We got this stack trace during Valgrind memory tests. This is the back trace:

```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00000000008e75d2 in strlcpy (dst=dst@entry=0x63ff98c "", src=0x1 <error: Cannot access memory at address 0x1>, siz=siz@entry=64) at strlcpy.c:56
56				if ((*d++ = *s++) == '\0')
(gdb) bt
#0  0x00000000008e75d2 in strlcpy (dst=dst@entry=0x63ff98c "", src=0x1 <error: Cannot access memory at address 0x1>, siz=siz@entry=64) at strlcpy.c:56
#1  0x000000000666120a in TupleToWorkerNode (tupleDescriptor=tupleDescriptor@entry=0x6471c68, heapTuple=<optimized out>) at utils/node_metadata.c:1523
#2  0x0000000006662283 in ReadWorkerNodes (includeNodesFromOtherClusters=includeNodesFromOtherClusters@entry=false) at utils/node_metadata.c:799
#3  0x000000000665d18b in InitializeWorkerNodeCache () at utils/metadata_cache.c:2715
#4  0x000000000665d6de in PrepareWorkerNodeCache () at utils/metadata_cache.c:2671
#5  0x000000000665f094 in GetWorkerNodeHash () at utils/metadata_cache.c:2642
#6  0x000000000662d9f2 in ActiveReadableNodeList () at master/worker_node_manager.c:361
#7  0x000000000664f73c in CheckForDistributedDeadlocks () at transaction/distributed_deadlock_detection.c:111
#8  0x000000000665c01f in CitusMaintenanceDaemonMain (main_arg=<optimized out>) at utils/maintenanced.c:438
#9  0x000000000070b7be in StartBackgroundWorker () at bgworker.c:834
#10 0x00000000007185ff in do_start_bgworker (rw=rw@entry=0x62f6120) at postmaster.c:5698
#11 0x000000000071877d in maybe_start_bgworkers () at postmaster.c:5911
#12 0x0000000000719a2c in ServerLoop () at postmaster.c:1783
#13 0x000000000071aaf7 in PostmasterMain (argc=argc@entry=31, argv=argv@entry=0x61e5830) at postmaster.c:1379
#14 0x000000000068311c in main (argc=31, argv=0x61e5830) at main.c:228
```

The corresponding code is [here](https://github.com/citusdata/citus/blame/a378a11da029ff66b01aa7fe2899e81be98b9ed3/src/backend/distributed/utils/node_metadata.c#L1510-L1525). Instead of checking `if (nodeClusterString != NULL)` we should probably check `isNullArray` beforehand.

**Comment by onderkalaci** [comment]
Fixed by #2816
