### ISSUE TITLE
Segmentation fault during copy because of autovacuum

### ISSUE THREAD

**Issue by louiseGrandjonc** [citusdata/citus#2686]
A user, on their own servers with the following hardware 

```
OS: CentOS Linux release 7.6.1810 (Core);
Memory: 8 GB;
CPU Threads: 8 Intel Core i7 9xx (Nehalem Class Core i7);
CPU MHz: 2266.746;
Samsung SSD
```

Created a table in which they ingest data. After ingesting 20-40M rows, during autovacuum they experience a crash with a segmentation fault:

```
Unhandled Exception: Npgsql.PostgresException: 58030: failed to COPY to shard xxxx on xxxxx:5432
   at Npgsql.NpgsqlConnector.<>c__DisplayClass161_0.<<ReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Npgsql.NpgsqlConnector.<>c__DisplayClass161_0.<<ReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.NpgsqlConnector.ReadMessage(DataRowLoadingMode dataRowLoadingMode)
   at Npgsql.NpgsqlBinaryImporter.Complete()
   at ConsoleApp1.Program.Work(String sourceTable, String table)
   at ConsoleApp1.Program.Main(String[] args)

Apr 12 09:52:21 citusdb-passthrough-data-2 kernel: postmaster[19258]: segfault at 13de5548 ip 0000000000489c70 sp 00007fffec6b99b0 error 4 in postgres[400000+6ed000]
```

In the logs of the coordinator there is the following error 

```
2019-04-16 09:36:05.522 UTC [11670] ERROR:  failed to COPY to shard xxx on xxxx:5432
2019-04-16 09:36:05.522 UTC [11670] DETAIL:  failed to send 1218 bytes 
2019-04-16 09:36:05.522 UTC [11670] CONTEXT:  COPY CSV_1M, line 7314
2019-04-16 09:36:05.522 UTC [11670] STATEMENT:  COPY "npgsql_copy"."my_table" (...) FROM STDIN (FORMAT BINARY)
2019-04-16 09:36:07.381 UTC [11431] WARNING:  server closed the connection unexpectedly
		This probably means the server terminated abnormally
		before or while processing the request.
2019-04-16 09:36:07.381 UTC [11431] CONTEXT:  while executing command on 10.10.6.37:5432
	Citus maintenance daemon for database 16384 user 10
```

It's in the worker that we can see the segmentation fault that happens during autovaccum. 

```
2019-04-16 09:36:05.427 UTC [12462] LOG:  server process (PID 16629) was terminated by signal 11: Segmentation fault
2019-04-16 09:36:05.427 UTC [12462] DETAIL:  Failed process was running: autovacuum: ANALYZE npgsql_copy.my_table_102149
2019-04-16 09:36:05.427 UTC [12462] LOG:  terminating any other active server processes
2019-04-16 09:36:05.427 UTC [16836] WARNING:  terminating connection because of crash of another server process
2019-04-16 09:36:05.427 UTC [16836] DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
2019-04-16 09:36:05.427 UTC [16836] HINT:  In a moment you should be able to reconnect to the database and repeat your command.
2019-04-16 09:36:05.427 UTC [16836] CONTEXT:  COPY my_table_102164, line 211
2019-04-16 09:36:05.427 UTC [16741] WARNING:  terminating connection because of crash of another server process
2019-04-16 09:36:05.427 UTC [16741] DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
```

Turning off autovacuum prevents the error from happening. But that's not a great solution.

**Comment by marcocitus** [comment]
has not been observed for a few years
