### ISSUE TITLE
planner bug: WindowFunc found in non-WindowAgg plan node

### ISSUE THREAD

**Issue by will** [citusdata/citus#3235]
## versions
PostgreSQL 12.1 ( postgres/postgres@bf3cef24a319666 )
Citus 9.0.1 ( citusdata/citus@a853a824a5bc89 ) 

## schema
``` sql
CREATE TABLE stores_purchase (
    id integer NOT NULL,
    quantity integer NOT NULL,
    product_id integer NOT NULL,
    store_id integer NOT NULL
);
SELECT create_distributed_table('stores_purchase', 'store_id')
```

## broken queries
No data is needed in the table. In neither case does any traffic make it to the workers.

### query 1
``` sql
explain delete from stores_purchase
where
case when
  EXISTS (
    select
      (select action_statement from information_schema.triggers)
    from
      pg_catalog.pg_statio_sys_sequences
  )
then null
end = null
;
```
#### result 
`ERROR:  WindowFunc found in non-WindowAgg plan node`
from https://github.com/postgres/postgres/blob/bf3cef24a31966686dfaae3085ce7c545c0019a4/src/backend/executor/execExpr.c#L862

### query 2
```sql 
explain delete from stores_purchase
where
case when
  EXISTS (
    select 1
    from pg_catalog.pg_statio_sys_sequences
  )
then null
end = null
;
```
#### result 
`ERROR:  could not find valid entry for shard 0`

**Comment by will** [comment]
Originally the queries hadlike 

`````` sql
then cast(null as ltree)
else cast(null as ltree)
end = cast(null as ltree)
```

but I just realized that the `ltree` parts were not necessary, so I've removed them.

**Comment by marcocitus** [comment]
Stack trace for query 1:
```
#0  errstart (elevel=elevel@entry=20, filename=0xa3912d "execExpr.c", lineno=861, funcname=0xa399c0 <__func__.24941> "ExecInitExprRec", domain=domain@entry=0x0) at elog.c:251
#1  0x00000000008a90cf in elog_finish (elevel=elevel@entry=20, fmt=fmt@entry=0xa393d8 "WindowFunc found in non-WindowAgg plan node") at elog.c:1358
#2  0x000000000062d8fb in ExecInitExprRec (node=0x2bd9c98, state=state@entry=0x28c6d60, resv=resv@entry=0x28c6e70, resnull=resnull@entry=0x28c7190) at execExpr.c:861
#3  0x000000000062f966 in ExecInitFunc (scratch=scratch@entry=0x7fff32411d90, node=node@entry=0x2bd9be0, args=<optimized out>, funcid=<optimized out>, inputcollid=0, 
    state=state@entry=0x28c6d60) at execExpr.c:2233
#4  0x000000000062d952 in ExecInitExprRec (node=0x2bd9be0, state=state@entry=0x28c6d60, resv=resv@entry=0x28c6d68, resnull=resnull@entry=0x28c6d65) at execExpr.c:882
#5  0x000000000062f324 in ExecInitCoerceToDomain (scratch=scratch@entry=0x7fff32411f20, ctest=ctest@entry=0x2bd9b88, state=state@entry=0x28c6d60, resv=resv@entry=0x28c6d68, 
    resnull=resnull@entry=0x28c6d65) at execExpr.c:2691
#6  0x000000000062f21c in ExecInitExprRec (node=node@entry=0x2bd9b88, state=state@entry=0x28c6d60, resv=resv@entry=0x28c6d68, resnull=resnull@entry=0x28c6d65) at execExpr.c:2074
#7  0x000000000062f573 in ExecInitExpr (node=node@entry=0x2bd9b88, parent=parent@entry=0x2a09800) at execExpr.c:138
#8  0x00007f22c5ce7c8f in citus_evaluate_expr (expr=expr@entry=0x2bd9b88, result_type=13003, result_typmod=result_typmod@entry=-1, result_collation=result_collation@entry=0, 
    planState=planState@entry=0x2a09800) at utils/citus_clauses.c:177
#9  0x00007f22c5ce7e21 in PartiallyEvaluateExpression (expression=0x2bd9b88, planState=0x2a09800) at utils/citus_clauses.c:106
#10 0x000000000068887d in expression_tree_mutator (node=node@entry=0x2bd9b30, mutator=mutator@entry=0x7f22c5ce7d55 <PartiallyEvaluateExpression>, context=context@entry=0x2a09800)
    at nodeFuncs.c:2920
#11 0x00007f22c5ce7e4b in PartiallyEvaluateExpression (expression=0x2bd9b30, planState=0x2a09800) at utils/citus_clauses.c:122
#12 0x00000000006889dc in expression_tree_mutator (node=node@entry=0x2bd8cd8, mutator=mutator@entry=0x7f22c5ce7d55 <PartiallyEvaluateExpression>, context=context@entry=0x2a09800)
    at nodeFuncs.c:2969
#13 0x00007f22c5ce7e4b in PartiallyEvaluateExpression (expression=0x2bd8cd8, planState=0x2a09800) at utils/citus_clauses.c:122
#14 0x00000000006892fd in query_tree_mutator (query=0x2945530, mutator=mutator@entry=0x7f22c5ce7d55 <PartiallyEvaluateExpression>, context=context@entry=0x2a09800, 
    flags=flags@entry=32) at nodeFuncs.c:3163
#15 0x00007f22c5ce7e37 in PartiallyEvaluateExpression (expression=0x2945530, planState=0x2a09800) at utils/citus_clauses.c:115
#16 0x0000000000689138 in range_table_mutator (rtable=<optimized out>, mutator=mutator@entry=0x7f22c5ce7d55 <PartiallyEvaluateExpression>, context=context@entry=0x2a09800, 
    flags=flags@entry=32) at nodeFuncs.c:3266
#17 0x000000000068956e in query_tree_mutator (query=0x2bd2e38, mutator=mutator@entry=0x7f22c5ce7d55 <PartiallyEvaluateExpression>, context=context@entry=0x2a09800, 
    flags=flags@entry=32) at nodeFuncs.c:3226
#18 0x00007f22c5ce7e37 in PartiallyEvaluateExpression (expression=0x2bd2e38, planState=0x2a09800) at utils/citus_clauses.c:115
#19 0x000000000068817a in expression_tree_mutator (node=node@entry=0x2bd2de0, mutator=mutator@entry=0x7f22c5ce7d55 <PartiallyEvaluateExpression>, context=context@entry=0x2a09800)
    at nodeFuncs.c:2696
#20 0x00007f22c5ce7e4b in PartiallyEvaluateExpression (expression=0x2bd2de0, planState=0x2a09800) at utils/citus_clauses.c:122
#21 0x000000000068887d in expression_tree_mutator (node=node@entry=0x2bd2d88, mutator=mutator@entry=0x7f22c5ce7d55 <PartiallyEvaluateExpression>, context=context@entry=0x2a09800)
    at nodeFuncs.c:2920
#22 0x00007f22c5ce7e4b in PartiallyEvaluateExpression (expression=0x2bd2d88, planState=0x2a09800) at utils/citus_clauses.c:122
#23 0x00000000006889dc in expression_tree_mutator (node=node@entry=0x2bd2d28, mutator=mutator@entry=0x7f22c5ce7d55 <PartiallyEvaluateExpression>, context=context@entry=0x2a09800)
    at nodeFuncs.c:2969
#24 0x00007f22c5ce7e4b in PartiallyEvaluateExpression (expression=0x2bd2d28, planState=0x2a09800) at utils/citus_clauses.c:122
#25 0x00000000006892fd in query_tree_mutator (query=0x2bcb968, mutator=mutator@entry=0x7f22c5ce7d55 <PartiallyEvaluateExpression>, context=context@entry=0x2a09800, 
    flags=flags@entry=32) at nodeFuncs.c:3163
#26 0x00007f22c5ce7e37 in PartiallyEvaluateExpression (expression=0x2bcb968, planState=0x2a09800) at utils/citus_clauses.c:115
#27 0x000000000068817a in expression_tree_mutator (node=node@entry=0x2bcb910, mutator=mutator@entry=0x7f22c5ce7d55 <PartiallyEvaluateExpression>, context=context@entry=0x2a09800)
    at nodeFuncs.c:2696
#28 0x00007f22c5ce7e4b in PartiallyEvaluateExpression (expression=0x2bcb910, planState=0x2a09800) at utils/citus_clauses.c:122
#29 0x0000000000688540 in expression_tree_mutator (node=node@entry=0x2bcb8d8, mutator=mutator@entry=0x7f22c5ce7d55 <PartiallyEvaluateExpression>, context=context@entry=0x2a09800)
    at nodeFuncs.c:2815
#30 0x00007f22c5ce7e4b in PartiallyEvaluateExpression (expression=0x2bcb8d8, planState=0x2a09800) at utils/citus_clauses.c:122
#31 0x00000000006889dc in expression_tree_mutator (node=node@entry=0x2bcb878, mutator=mutator@entry=0x7f22c5ce7d55 <PartiallyEvaluateExpression>, context=context@entry=0x2a09800)
    at nodeFuncs.c:2969
#32 0x00007f22c5ce7e4b in PartiallyEvaluateExpression (expression=0x2bcb878, planState=0x2a09800) at utils/citus_clauses.c:122
#33 0x00000000006884e7 in expression_tree_mutator (node=node@entry=0x2bcb820, mutator=mutator@entry=0x7f22c5ce7d55 <PartiallyEvaluateExpression>, context=context@entry=0x2a09800)
    at nodeFuncs.c:2804
#34 0x00007f22c5ce7e4b in PartiallyEvaluateExpression (expression=0x2bcb820, planState=0x2a09800) at utils/citus_clauses.c:122
#35 0x00000000006889dc in expression_tree_mutator (node=node@entry=0x2bcb7c0, mutator=mutator@entry=0x7f22c5ce7d55 <PartiallyEvaluateExpression>, context=context@entry=0x2a09800)
    at nodeFuncs.c:2969
#36 0x00007f22c5ce7e4b in PartiallyEvaluateExpression (expression=0x2bcb7c0, planState=0x2a09800) at utils/citus_clauses.c:122
#36 0x00007f22c5ce7e4b in PartiallyEvaluateExpression (expression=0x2bcb7c0, planState=0x2a09800) at utils/citus_clauses.c:122
#37 0x0000000000687fd9 in expression_tree_mutator (node=node@entry=0x2bcb768, mutator=mutator@entry=0x7f22c5ce7d55 <PartiallyEvaluateExpression>, context=context@entry=0x2a09800)
    at nodeFuncs.c:2640
#38 0x00007f22c5ce7dee in PartiallyEvaluateExpression (expression=0x2bcb768, planState=0x2a09800) at utils/citus_clauses.c:101
#39 0x0000000000688a40 in expression_tree_mutator (node=node@entry=0x2bcb6b0, mutator=mutator@entry=0x7f22c5ce7d55 <PartiallyEvaluateExpression>, context=context@entry=0x2a09800)
    at nodeFuncs.c:2982
#40 0x00007f22c5ce7e4b in PartiallyEvaluateExpression (expression=0x2bcb6b0, planState=0x2a09800) at utils/citus_clauses.c:122
#41 0x000000000068934f in query_tree_mutator (query=0x2bcb150, mutator=mutator@entry=0x7f22c5ce7d55 <PartiallyEvaluateExpression>, context=context@entry=0x2a09800, 
    flags=flags@entry=32) at nodeFuncs.c:3167
#42 0x00007f22c5ce7e37 in PartiallyEvaluateExpression (expression=expression@entry=0x2bcb150, planState=planState@entry=0x2a09800) at utils/citus_clauses.c:115
#43 0x00007f22c5ce7f20 in ExecuteMasterEvaluableFunctions (query=query@entry=0x2bcb150, planState=planState@entry=0x2a09800) at utils/citus_clauses.c:56
#44 0x00007f22c5ca7761 in CitusModifyBeginScan (node=node@entry=0x2a09800, estate=estate@entry=0x2a095e8, eflags=eflags@entry=1) at executor/citus_custom_scan.c:198
#45 0x00007f22c5ca782e in CitusBeginScan (node=0x2a09800, estate=0x2a095e8, eflags=1) at executor/citus_custom_scan.c:140
#46 0x000000000064d904 in ExecInitCustomScan (cscan=cscan@entry=0x2ac5aa8, estate=estate@entry=0x2a095e8, eflags=eflags@entry=1) at nodeCustom.c:101
#47 0x000000000063f19b in ExecInitNode (node=node@entry=0x2ac5aa8, estate=estate@entry=0x2a095e8, eflags=eflags@entry=1) at execProcnode.c:282
#48 0x0000000000639498 in InitPlan (queryDesc=queryDesc@entry=0x2a17488, eflags=eflags@entry=1) at execMain.c:1046
#49 0x00000000006396e6 in standard_ExecutorStart (queryDesc=queryDesc@entry=0x2a17488, eflags=eflags@entry=1) at execMain.c:265
#50 0x00007f22c5caa374 in CitusExecutorStart (queryDesc=0x2a17488, eflags=1) at executor/multi_executor.c:120
#51 0x0000000000639708 in ExecutorStart (queryDesc=queryDesc@entry=0x2a17488, eflags=eflags@entry=1) at execMain.c:145
#52 0x00000000005cefae in ExplainOnePlan (plannedstmt=plannedstmt@entry=0x2ac1a60, into=into@entry=0x0, es=es@entry=0x291f718, 
    queryString=queryString@entry=0x27fd098 "explain delete from stores_purchase\nwhere\ncase when\n  EXISTS (\n    select\n      (select action_statement from information_schema.triggers)\n    from\n      pg_catalog.pg_statio_sys_sequences\n  )\nthen nu"..., params=params@entry=0x0, queryEnv=queryEnv@entry=0x0, 
    planduration=planduration@entry=0x7fff32412b40) at explain.c:521
#53 0x00000000005cf203 in ExplainOneQuery (query=<optimized out>, cursorOptions=cursorOptions@entry=256, into=into@entry=0x0, es=es@entry=0x291f718, 
    queryString=queryString@entry=0x27fd098 "explain delete from stores_purchase\nwhere\ncase when\n  EXISTS (\n    select\n      (select action_statement from information_schema.triggers)\n    from\n      pg_catalog.pg_statio_sys_sequences\n  )\nthen nu"..., params=params@entry=0x0, queryEnv=queryEnv@entry=0x0) at explain.c:371
#54 0x00000000005cf9fd in ExplainQuery (pstate=pstate@entry=0x291f600, stmt=stmt@entry=0x2998830, 
    queryString=queryString@entry=0x27fd098 "explain delete from stores_purchase\nwhere\ncase when\n  EXISTS (\n    select\n      (select action_statement from information_schema.triggers)\n    from\n      pg_catalog.pg_statio_sys_sequences\n  )\nthen nu"..., params=params@entry=0x0, queryEnv=queryEnv@entry=0x0, dest=dest@entry=0x2be9790) at explain.c:254
#55 0x000000000079bdb7 in standard_ProcessUtility (pstmt=pstmt@entry=0x2be9828, 
    queryString=queryString@entry=0x27fd098 "explain delete from stores_purchase\nwhere\ncase when\n  EXISTS (\n    select\n      (select action_statement from information_schema.triggers)\n    from\n      pg_catalog.pg_statio_sys_sequences\n  )\nthen nu"..., context=context@entry=PROCESS_UTILITY_TOPLEVEL, params=params@entry=0x0, 
    queryEnv=queryEnv@entry=0x0, dest=dest@entry=0x2be9790, completionTag=completionTag@entry=0x7fff32412ea0 "") at utility.c:675
#56 0x00007f22c5c8efae in multi_ProcessUtility (pstmt=0x2be9828, 
    queryString=0x27fd098 "explain delete from stores_purchase\nwhere\ncase when\n  EXISTS (\n    select\n      (select action_statement from information_schema.triggers)\n    from\n      pg_catalog.pg_statio_sys_sequences\n  )\nthen nu"..., context=PROCESS_UTILITY_TOPLEVEL, params=0x0, queryEnv=0x0, dest=0x2be9790, completionTag=0x7fff32412ea0 "")
    at commands/utility_hook.c:684
#57 0x000000000079c2ec in ProcessUtility (pstmt=pstmt@entry=0x27fe820, queryString=<optimized out>, context=<optimized out>, params=<optimized out>, queryEnv=<optimized out>, 
    dest=dest@entry=0x2be9790, completionTag=completionTag@entry=0x7fff32412ea0 "") at utility.c:356
#58 0x0000000000798a34 in PortalRunUtility (portal=portal@entry=0x28b0f78, pstmt=0x27fe820, isTopLevel=<optimized out>, setHoldSnapshot=setHoldSnapshot@entry=true, 
    dest=dest@entry=0x2be9790, completionTag=completionTag@entry=0x7fff32412ea0 "") at pquery.c:1178
#59 0x00000000007997e2 in FillPortalStore (portal=portal@entry=0x28b0f78, isTopLevel=isTopLevel@entry=true) at pquery.c:1038
#60 0x000000000079a232 in PortalRun (portal=portal@entry=0x28b0f78, count=count@entry=9223372036854775807, isTopLevel=isTopLevel@entry=true, run_once=run_once@entry=true, 
    dest=dest@entry=0x2addac0, altdest=altdest@entry=0x2addac0, completionTag=completionTag@entry=0x7fff324130b0 "") at pquery.c:768
#61 0x00000000007968d8 in exec_simple_query (
    query_string=query_string@entry=0x27fd098 "explain delete from stores_purchase\nwhere\ncase when\n  EXISTS (\n    select\n      (select action_statement from information_schema.triggers)\n    from\n      pg_catalog.pg_statio_sys_sequences\n  )\nthen nu"...) at postgres.c:1145
#62 0x0000000000798571 in PostgresMain (argc=<optimized out>, argv=argv@entry=0x286cac0, dbname=0x286c920 "postgres", username=<optimized out>) at postgres.c:4182
#63 0x0000000000719dad in BackendRun (port=port@entry=0x28648e0) at postmaster.c:4358
#64 0x000000000071c9d2 in BackendStartup (port=port@entry=0x28648e0) at postmaster.c:4030
#65 0x000000000071cc7b in ServerLoop () at postmaster.c:1707
#66 0x000000000071df16 in PostmasterMain (argc=argc@entry=3, argv=argv@entry=0x27f7bd0) at postmaster.c:1380
#67 0x000000000068580f in main (argc=3, argv=0x27f7bd0) at main.c:228
```
