### ISSUE TITLE
Using return value of a delegated function inside  another function errors

### ISSUE THREAD

**Issue by onderkalaci** [citusdata/citus#3291]
Reported on slack, I didn't have much time to look,  just created steps to repro:

```SQL
CREATE TABLE statement_table(id int, name text);
SET citus.shard_replication_factor TO 1;
SELECT create_distributed_table('statement_table','id');

CREATE OR REPLACE FUNCTION increment(int)
RETURNS NUMERIC AS $$
DECLARE ret_val NUMERIC;
BEGIN
        SELECT max(id)::numeric INTO ret_val  FROM statement_table WHERE id = $1+1;
        RETURN ret_val;
END;
$$  LANGUAGE plpgsql
    SECURITY DEFINER
    -- Set a secure search_path: trusted schema(s), then 'pg_temp'.
    SET search_path = admin, public;


SELECT create_distributed_function('increment(int)', '$1', colocate_with := 'statement_table');


CREATE OR REPLACE FUNCTION test_func_calls_dist_func()
RETURNS NUMERIC AS $$
DECLARE incremented_val NUMERIC;
BEGIN
        SELECT INTO incremented_val increment(1);
        RETURN incremented_val;
END;
$$  LANGUAGE plpgsql
    SECURITY DEFINER
    -- Set a secure search_path: trusted schema(s), then 'pg_temp'.
    SET search_path = admin, public;

SELECT test_func_calls_dist_func();

SELECT test_func_calls_dist_func();
ERROR:  unexpected plan node type: 34
CONTEXT:  PL/pgSQL function test_func_calls_dist_func() line 4 at SQL statement
Time: 1.305 ms


SELECT test_func_calls_dist_func();
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
Time: 341.933 ms
!> \q
```

**Comment by thanodnl** [comment]
The error in the first run comes from https://github.com/postgres/postgres/blob/5e7bedc5adba570b526d89746201481616756779/src/pl/plpgsql/src/pl_exec.c#L8045-L8046

While getting here plpgsql did a lot of checks to see if the query at hand `SELECT increment(1);` is what they call a simple query. This query matches every predicate of being simple (no tables, 1 entry in the target list, etc, etc). Then passes the query to the planner and assumes it either gets a `Restult` or a `Gather` node back, which is not the case with citus as it receives a `CustomScan` node.

It seems we cannot easily wrap the `CustomScan` in a `Result` node. Since it is supposed to be a simple query from plpgsql heuristics it assumes the `Result` will not have a left nor a right plan: https://github.com/postgres/postgres/blob/5e7bedc5adba570b526d89746201481616756779/src/pl/plpgsql/src/pl_exec.c#L8022-L8026 which would be the way to correctly wrap the `CustomScan` in a `Result` node.

That said, I wonder how safe the pushdown of a function from an other function is. Isn't the content of `test_func_calls_dist_func` supposed to run as a transaction? It would be a visibility issue if we push down a function with side effects and later read the table our pushed down function changed from the coordinator.

I will keep looking into this, but I think the right solution is to _NOT_ push down functions when executed from a function like this.

**Comment by marcocitus** [comment]
The main problem is that `IsMultiStatementTransaction()` is false because the assumption that we would recurse into the executor hook before `TryToDelegateFunctionCall` does not hold.

Stack trace for IsMultiStatementTransaction call
```
#0  errstart (elevel=elevel@entry=20, filename=0x7f131b614e10 "function_call_delegation.c", lineno=233, funcname=0x7f131b614e60 <__func__.22516> "TryToDelegateFunctionCall", 
    domain=domain@entry=0x0) at elog.c:251
#1  0x00000000008bc754 in elog_finish (elevel=elevel@entry=20, fmt=fmt@entry=0x7f131b614e49 "is multi %d %d %d") at elog.c:1358
#2  0x00007f131b5c8c39 in TryToDelegateFunctionCall (query=query@entry=0x1be5ee8, hasExternParam=hasExternParam@entry=0x7ffce51e2b2f) at planner/function_call_delegation.c:233
#3  0x00007f131b5c7f3d in distributed_planner (parse=0x1be5ee8, cursorOptions=256, boundParams=0x0) at planner/distributed_planner.c:230
#4  0x00000000006ed897 in planner (parse=parse@entry=0x1be5ee8, cursorOptions=cursorOptions@entry=256, boundParams=boundParams@entry=0x0) at planner.c:261
#5  0x00000000007a4f47 in pg_plan_query (querytree=querytree@entry=0x1be5ee8, cursorOptions=cursorOptions@entry=256, boundParams=boundParams@entry=0x0) at postgres.c:832
#6  0x00000000007a500f in pg_plan_queries (querytrees=querytrees@entry=0x1be5e88, cursorOptions=256, boundParams=boundParams@entry=0x0) at postgres.c:898
#7  0x00000000008a794b in BuildCachedPlan (plansource=plansource@entry=0x1bdb348, qlist=0x1be5e88, qlist@entry=0x0, boundParams=boundParams@entry=0x0, 
    queryEnv=queryEnv@entry=0x0) at plancache.c:938
#8  0x00000000008a7d8d in GetCachedPlan (plansource=plansource@entry=0x1bdb348, boundParams=boundParams@entry=0x0, useResOwner=<optimized out>, queryEnv=0x0) at plancache.c:1168
#9  0x0000000000678b48 in SPI_plan_get_cached_plan (plan=<optimized out>) at spi.c:1787
#10 0x00007f130d160ed1 in exec_simple_check_plan (estate=estate@entry=0x7ffce51e2ff0, expr=expr@entry=0x1bcf518) at pl_exec.c:7848
#11 0x00007f130d160f64 in exec_prepare_plan (estate=0x7ffce51e2ff0, expr=expr@entry=0x1bcf518, cursorOptions=cursorOptions@entry=256, keepplan=keepplan@entry=true)
    at pl_exec.c:4056
#12 0x00007f130d165ef9 in exec_stmt_execsql (estate=estate@entry=0x7ffce51e2ff0, stmt=stmt@entry=0x1bd12a8) at pl_exec.c:4091
#13 0x00007f130d1691b3 in exec_stmt (estate=estate@entry=0x7ffce51e2ff0, stmt=0x1bd12a8) at pl_exec.c:2013
#14 0x00007f130d1692b4 in exec_stmts (estate=estate@entry=0x7ffce51e2ff0, stmts=<optimized out>) at pl_exec.c:1904
#15 0x00007f130d1698b7 in exec_stmt_block (estate=estate@entry=0x7ffce51e2ff0, block=0x1bd13e8) at pl_exec.c:1845
#16 0x00007f130d169bb4 in plpgsql_exec_function (func=func@entry=0x1af82d0, fcinfo=fcinfo@entry=0x1bc34c0, simple_eval_estate=simple_eval_estate@entry=0x0, 
    atomic=atomic@entry=true) at pl_exec.c:589
#17 0x00007f130d15c7a2 in plpgsql_call_handler (fcinfo=0x1bc34c0) at pl_handler.c:263
#18 0x00000000008c0c4a in fmgr_security_definer (fcinfo=0x1bc34c0) at fmgr.c:748
#19 0x000000000063d474 in ExecInterpExpr (state=0x1bc33d8, econtext=0x1bc30c8, isnull=0x7ffce51e349f) at execExprInterp.c:654
#20 0x000000000063a4b3 in ExecInterpExprStillValid (state=0x1bc33d8, econtext=0x1bc30c8, isNull=0x7ffce51e349f) at execExprInterp.c:1786
#21 0x0000000000669ab7 in ExecEvalExprSwitchContext (isNull=0x7ffce51e349f, econtext=0x1bc30c8, state=0x1bc33d8) at ../../../src/include/executor/executor.h:313
#22 ExecProject (projInfo=0x1bc33d0) at ../../../src/include/executor/executor.h:347
#23 ExecResult (pstate=<optimized out>) at nodeResult.c:136
#24 0x00000000006485e1 in ExecProcNodeFirst (node=0x1bc2fb0) at execProcnode.c:445
#25 0x0000000000640e5b in ExecProcNode (node=0x1bc2fb0) at ../../../src/include/executor/executor.h:247
#26 ExecutePlan (estate=estate@entry=0x1bc2d98, planstate=0x1bc2fb0, use_parallel_mode=<optimized out>, operation=operation@entry=CMD_SELECT, sendTuples=sendTuples@entry=true, 
    numberTuples=numberTuples@entry=0, direction=ForwardScanDirection, dest=0x1bae568, execute_once=true) at execMain.c:1723
#27 0x0000000000641a96 in standard_ExecutorRun (queryDesc=queryDesc@entry=0x1af4038, direction=direction@entry=ForwardScanDirection, count=count@entry=0, 
    execute_once=execute_once@entry=true) at execMain.c:364
#28 0x00007f131b5b1240 in CitusExecutorRun (queryDesc=0x1af4038, direction=ForwardScanDirection, count=0, execute_once=<optimized out>) at executor/multi_executor.c:175
#29 0x0000000000641b41 in ExecutorRun (queryDesc=queryDesc@entry=0x1af4038, direction=direction@entry=ForwardScanDirection, count=count@entry=0, execute_once=<optimized out>)
    at execMain.c:305
#30 0x00000000007a7a09 in PortalRunSelect (portal=portal@entry=0x1b30388, forward=forward@entry=true, count=0, count@entry=9223372036854775807, dest=dest@entry=0x1bae568)
    at pquery.c:932
#31 0x00000000007a9090 in PortalRun (portal=portal@entry=0x1b30388, count=count@entry=9223372036854775807, isTopLevel=isTopLevel@entry=true, run_once=run_once@entry=true, 
    dest=dest@entry=0x1bae568, altdest=altdest@entry=0x1bae568, completionTag=0x7ffce51e3810 "") at pquery.c:773
#32 0x00000000007a54de in exec_simple_query (query_string=query_string@entry=0x1a7c3a8 "SELECT test_func_calls_dist_func();") at postgres.c:1145
#33 0x00000000007a7310 in PostgresMain (argc=<optimized out>, argv=argv@entry=0x1af6a30, dbname=<optimized out>, username=<optimized out>) at postgres.c:4193
#34 0x000000000072641a in BackendRun (port=port@entry=0x1aeba80) at postmaster.c:4364
#35 0x0000000000729471 in BackendStartup (port=port@entry=0x1aeba80) at postmaster.c:4036
#36 0x0000000000729680 in ServerLoop () at postmaster.c:1707
#37 0x000000000072aab3 in PostmasterMain (argc=argc@entry=3, argv=argv@entry=0x1a75b40) at postmaster.c:1380
```
