### ISSUE TITLE
Crash when using sublink and function call without FROM

### ISSUE THREAD

**Issue by marcocitus** [citusdata/citus#3436]
Following SQL crashes:
```sql
SELECT (SELECT count(*) FROM test), random();
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
Time: 328.922 ms
!> 
```

Stack trace:
```
Program received signal SIGSEGV, Segmentation fault.
0x00007fbe0f8f15b3 in RebuildQueryStrings (originalQuery=0x12c2920, taskList=0x12c3770) at /home/marco/pgsql-11/include/server/nodes/pg_list.h:79                                 
79              return l ? l->head : NULL;

(gdb) bt
#0  0x00007fbe0f8f15b3 in RebuildQueryStrings (originalQuery=0x12c2920, taskList=0x12c3770) at /home/marco/pgsql-11/include/server/nodes/pg_list.h:79
#1  0x00007fbe0f8d4f17 in CitusBeginScanWithCoordinatorProcessing (node=node@entry=0x1248330, estate=estate@entry=0x1248118, eflags=eflags@entry=16)
    at executor/citus_custom_scan.c:270
#2  0x00007fbe0f8d4fe9 in CitusBeginScan (node=0x1248330, estate=0x1248118, eflags=16) at executor/citus_custom_scan.c:152
#3  0x0000000000657439 in ExecInitCustomScan (cscan=cscan@entry=0x7fbe01623708, estate=estate@entry=0x1248118, eflags=eflags@entry=16) at nodeCustom.c:101
#4  0x0000000000648990 in ExecInitNode (node=node@entry=0x7fbe01623708, estate=estate@entry=0x1248118, eflags=eflags@entry=16) at execProcnode.c:282
#5  0x0000000000642a12 in InitPlan (queryDesc=queryDesc@entry=0x1250e48, eflags=eflags@entry=16) at execMain.c:1046
#6  0x0000000000642bc5 in standard_ExecutorStart (queryDesc=queryDesc@entry=0x1250e48, eflags=16, eflags@entry=0) at execMain.c:265
#7  0x00007fbe0f8da126 in CitusExecutorStart (queryDesc=0x1250e48, eflags=0) at executor/multi_executor.c:111
#8  0x0000000000642cab in ExecutorStart (queryDesc=queryDesc@entry=0x1250e48, eflags=<optimized out>) at execMain.c:145
#9  0x00000000007a8b88 in PortalStart (portal=portal@entry=0x11ae488, params=params@entry=0x0, eflags=eflags@entry=0, snapshot=snapshot@entry=0x0) at pquery.c:520
#10 0x00000000007a5460 in exec_simple_query (query_string=query_string@entry=0x10f83b8 "SELECT (SELECT count(*) FROM test), citus_total_relation_size('test');")
    at postgres.c:1106
#11 0x00000000007a7310 in PostgresMain (argc=<optimized out>, argv=argv@entry=0x1172a08, dbname=<optimized out>, username=<optimized out>) at postgres.c:4193
#12 0x000000000072641a in BackendRun (port=port@entry=0x116c170) at postmaster.c:4364
#13 0x0000000000729471 in BackendStartup (port=port@entry=0x116c170) at postmaster.c:4036
#14 0x0000000000729680 in ServerLoop () at postmaster.c:1707
#15 0x000000000072aab3 in PostmasterMain (argc=argc@entry=3, argv=argv@entry=0x10f1b50) at postmaster.c:1380
#16 0x0000000000690023 in main (argc=3, argv=0x10f1b50) at main.c:228
```

**Comment by marcocitus** [comment]
Seems to be a regression from 9.1
