### ISSUE TITLE
crash in insert command

### ISSUE THREAD

**Issue by mtuncer** [citusdata/citus#3824]
Following core dump trace was taken from a cloud customer.  Details about the query is sanitized.
They are using Citus 9.2-2 with 4 workers with shard_count = 32
Table is a distributed table.

```
Core was generated by `postgres: citus citus 127.0.0.1(56932) INSERT         '.
Program terminated with signal 11, Segmentation fault.
#0  FreeConnParamsHashEntryFields (entry=0x1c14498) at connection/connection_management.c:1034
1034	connection/connection_management.c: No such file or directory.
#0  FreeConnParamsHashEntryFields (entry=0x1c14498) at connection/connection_management.c:1034
#1  StartConnectionEstablishment (key=0x7ffcfd3114b0) at connection/connection_management.c:972
#2  StartNodeUserDatabaseConnection (flags=0, hostname=<optimized out>, port=<optimized out>, user=<optimized out>, database=0x0) at connection/connection_management.c:324
#3  0x00007f270187ab02 in ManageWorkerPool (workerPool=0x1c388f0) at executor/adaptive_executor.c:2262
#4  RunDistributedExecution (execution=0x1c386b0) at executor/adaptive_executor.c:2024
#5  0x00007f270187bc28 in AdaptiveExecutor (scanState=0x1c3c070) at executor/adaptive_executor.c:708
#6  0x00007f270187c582 in CitusExecScan (node=0x1c3c070) at executor/citus_custom_scan.c:182
#7  0x000000000060c9e2 in ExecProcNode (node=0x1c3c070) at ../../../src/include/executor/executor.h:239
#8  ExecutePlan (execute_once=<optimized out>, dest=0x1b28600, direction=<optimized out>, numberTuples=0, sendTuples=<optimized out>, operation=CMD_INSERT, use_parallel_mode=<optimized out>, planstate=0x1c3c070, estate=0x1c3bdd0) at execMain.c:1646
#9  standard_ExecutorRun (queryDesc=0x1c41670, direction=<optimized out>, count=0, execute_once=<optimized out>) at execMain.c:364
#10 0x00007f27018819bd in CitusExecutorRun (queryDesc=0x1c41670, direction=ForwardScanDirection, count=0, execute_once=true) at executor/multi_executor.c:177
#11 0x00007f27000adfee in pgss_ExecutorRun (queryDesc=0x1c41670, direction=ForwardScanDirection, count=0, execute_once=<optimized out>) at pg_stat_statements.c:891
#12 0x000000000074ffb4 in ProcessQuery (plan=<optimized out>, sourceText=0x1b283f0 "INSERT INTO <sanitized_table_name> ( column1, column2, ..,colmun8)  VALUES ( value1, value2, .....)"..., params=0x0, queryEnv=0x0, dest=0x1b28600, completionTag=0x7ffcfd311c30 "") at pquery.c:161
#13 0x00000000007501e9 in PortalRunMulti (portal=portal@entry=0x1b8b430, isTopLevel=isTopLevel@entry=true, setHoldSnapshot=setHoldSnapshot@entry=true, dest=dest@entry=0x1b28600, altdest=0x9dc480 <donothingDR>, completionTag=completionTag@entry=0x7ffcfd311c30 "") at pquery.c:1283
#14 0x0000000000750479 in FillPortalStore (portal=portal@entry=0x1b8b430, isTopLevel=isTopLevel@entry=true) at pquery.c:1030
#15 0x0000000000750ea5 in PortalRun (portal=portal@entry=0x1b8b430, count=count@entry=9223372036854775807, isTopLevel=isTopLevel@entry=true, run_once=<optimized out>, dest=dest@entry=0x1abfc90, altdest=altdest@entry=0x1abfc90, completionTag=0x7ffcfd312090 "") at pquery.c:765
#16 0x000000000074e745 in exec_execute_message (max_rows=9223372036854775807, portal_name=0x1abf880 "") at postgres.c:2090
#17 PostgresMain (argc=<optimized out>, argv=argv@entry=0x1b43748, dbname=<optimized out>, username=<optimized out>) at postgres.c:4308
#18 0x00000000006de9d8 in BackendRun (port=0x1b360c0, port=0x1b360c0) at postmaster.c:4437
#19 BackendStartup (port=0x1b360c0) at postmaster.c:4128
#20 ServerLoop () at postmaster.c:1704
#21 0x00000000006df955 in PostmasterMain (argc=argc@entry=3, argv=argv@entry=0x1aba280) at postmaster.c:1377
#22 0x0000000000487a4e in main (argc=3, argv=0x1aba280) at main.c:228
```

**Comment by onderkalaci** [comment]
same as #3716, fixed in Citus 9.3. So closing it
