### ISSUE TITLE
Inserting "composite type with array" to reference table (assertion) crashes at ruleutils

### ISSUE THREAD

**Issue by onurctirtir** [citusdata/citus#4089]
```sql
create type insert_test_type as (if1 int, if2 text[]);
create table inserttest (f1 int, f2 int[],
                         f3 insert_test_type, f4 insert_test_type[]);
select create_reference_table('inserttest');
insert into inserttest (f3.if1, f3.if2) values (1,array['foo']);
```

Above insert crashes due to assertion failure with below backtrace:

```c
#2  errorType=0x7f5ffa87ca81 "FailedAssertion", fileName=0x7f5ffa87caf1 "deparser/ruleutils_12.c", lineNumber=7859) at assert.c:54
#3  0x00007f5ffa7dbc4f in processIndirection (node=0x1d9cb00, context=0x7ffeb0977dd0) at deparser/ruleutils_12.c:7859
#4  0x00007f5ffa7d0b64 in get_insert_query_def (query=0x1d9bd88, context=0x7ffeb0977dd0) at deparser/ruleutils_12.c:3098
#5  0x00007f5ffa7ce686 in get_query_def_extended (query=0x1d9bd88, buf=0x1db5a10, parentnamespace=0x0, distrelid=804099, shardid=102107, resultDesc=0x0,
    prettyFlags=0, wrapColumn=0, startIndent=0) at deparser/ruleutils_12.c:1972
#6  0x00007f5ffa7ce42f in deparse_shard_query (query=0x1d9bd88, distrelid=804099, shardid=102107, buffer=0x1db5a10) at deparser/ruleutils_12.c:1890
#7  0x00007f5ffa8099c6 in DeparseTaskQuery (task=0x1d9b9b0, query=0x1d9bd88) at planner/deparse_shard_query.c:494
#8  0x00007f5ffa809b20 in TaskQueryString (task=0x1d9b9b0) at planner/deparse_shard_query.c:564
#9  0x00007f5ffa7e833d in ExecuteLocalTaskListExtended (taskList=0x1db5860, orig_paramListInfo=0x0, distributedPlan=0x1d9a828, defaultTupleDest=0x1d9d250,
    isUtilityCommand=false) at executor/local_executor.c:281
#10 0x00007f5ffa7dcd23 in RunLocalExecution (scanState=0x1d82630, execution=0x1d9c410) at executor/adaptive_executor.c:825
#11 0x00007f5ffa7dcb52 in AdaptiveExecutor (scanState=0x1d82630) at executor/adaptive_executor.c:751
#12 0x00007f5ffa7e1f53 in CitusExecScan (node=0x1d82630) at executor/citus_custom_scan.c:224
#13 0x0000000000732cc9 in ExecCustomScan (pstate=0x1d82630) at nodeCustom.c:116
#14 0x000000000071a5d6 in ExecProcNodeFirst (node=0x1d82630) at execProcnode.c:445
#15 0x000000000070f414 in ExecProcNode (node=0x1d82630) at ../../../src/include/executor/executor.h:239
#16 0x0000000000711c4f in ExecutePlan (estate=0x1d823c8, planstate=0x1d82630, use_parallel_mode=false, operation=CMD_INSERT, sendTuples=false,
    numberTuples=0, direction=ForwardScanDirection, dest=0x1d90c60, execute_once=true) at execMain.c:1646
#17 0x000000000070fa51 in standard_ExecutorRun (queryDesc=0x1d8c828, direction=ForwardScanDirection, count=0, execute_once=true) at execMain.c:364
#18 0x00007f5ffa7ea6e7 in CitusExecutorRun (queryDesc=0x1d8c828, direction=ForwardScanDirection, count=0, execute_once=true)
    at executor/multi_executor.c:202
#19 0x000000000070f874 in ExecutorRun (queryDesc=0x1d8c828, direction=ForwardScanDirection, count=0, execute_once=true) at execMain.c:306
#20 0x0000000000923abc in ProcessQuery (plan=0x1d90bc8, sourceText=0x1c1fae8 "insert into inserttest (f3.if1, f3.if2) values (1,array['foo']);",
    params=0x0, queryEnv=0x0, dest=0x1d90c60, completionTag=0x7ffeb0978690 "") at pquery.c:161
#21 0x00000000009254f0 in PortalRunMulti (portal=0x1cf07c8, isTopLevel=true, setHoldSnapshot=false, dest=0x1d90c60, altdest=0x1d90c60,
    completionTag=0x7ffeb0978690 "") at pquery.c:1283
#22 0x0000000000924a4d in PortalRun (portal=0x1cf07c8, count=9223372036854775807, isTopLevel=true, run_once=true, dest=0x1d90c60, altdest=0x1d90c60,
    completionTag=0x7ffeb0978690 "") at pquery.c:796
#23 0x000000000091e5b4 in exec_simple_query (query_string=0x1c1fae8 "insert into inserttest (f3.if1, f3.if2) values (1,array['foo']);") at postgres.c:1215
#24 0x0000000000922a7c in PostgresMain (argc=1, argv=0x1cb8880, dbname=0x1cb86c0 "postgres", username=0x1cb8698 "postgres") at postgres.c:4247
#25 0x00000000008713bd in BackendRun (port=0x1c3b9f0) at postmaster.c:4448
#26 0x0000000000870b06 in BackendStartup (port=0x1c3b9f0) at postmaster.c:4139
#27 0x000000000086cc46 in ServerLoop () at postmaster.c:1704
#28 0x000000000086c46d in PostmasterMain (argc=3, argv=0x1c1a760) at postmaster.c:1377
#29 0x00000000007850f7 in main (argc=3, argv=0x1c1a760) at main.c:228
```

And if we disable assertions, we get no errors nor warnings.

**Comment by onurctirtir** [comment]
Same with https://github.com/citusdata/citus/issues/1293, so closing this too :)
