### ISSUE TITLE
 CREATE INDEX CONCURRENTLY crashes with local execution

### ISSUE THREAD

**Issue by onurctirtir** [citusdata/citus#4090]
```sql
CREATE TABLE tbl_gist (c1 int, c2 int, c3 int, c4 box);
--or CREATE TABLE tbl_gist (c1 int, c2 int, c3 int, c4 box, EXCLUDE USING gist (c4 WITH &&) INCLUDE (c1, c2, c3));
SELECT create_reference_table('tbl_gist');
CREATE INDEX CONCURRENTLY tbl_gist_idx ON tbl_gist using gist (c4) INCLUDE (c1,c2,c3);
```

Above `CREATE INDEX CONCURRENTLY` command seg.faults **when coordinator is added to pg_dist_node**, with the below backtrace:

```c
#0  0x0000000000b06005 in PopActiveSnapshot () at snapmgr.c:818
#1  0x0000000000691468 in DefineIndex (relationId=812292, stmt=0x1df0c38, indexRelationId=812296, parentIndexId=0, parentConstraintId=0,
    is_alter_table=false, check_rights=true, check_not_in_use=true, skip_build=false, quiet=false) at indexcmds.c:1370
#2  0x0000000000928330 in ProcessUtilitySlow (pstate=0x1ddea50, pstmt=0x1df0700,
    queryString=0x1e4bb60 "CREATE  INDEX CONCURRENTLY  tbl_gist_idx_102140 ON public.tbl_gist_102140 USING gist (c4 ) INCLUDE (c1 ,c2 ,c3 )",
    context=PROCESS_UTILITY_TOPLEVEL, params=0x0, queryEnv=0x0, dest=0xcde5e0 <donothingDR>, completionTag=0x0) at utility.c:1372
#3  0x00000000009273ff in standard_ProcessUtility (pstmt=0x1df0700,
    queryString=0x1e4bb60 "CREATE  INDEX CONCURRENTLY  tbl_gist_idx_102140 ON public.tbl_gist_102140 USING gist (c4 ) INCLUDE (c1 ,c2 ,c3 )",
    context=PROCESS_UTILITY_TOPLEVEL, params=0x0, queryEnv=0x0, dest=0xcde5e0 <donothingDR>, completionTag=0x0) at utility.c:927
#4  0x00007f5ffa7b9b98 in multi_ProcessUtility (pstmt=0x1df0700,
    queryString=0x1e4bb60 "CREATE  INDEX CONCURRENTLY  tbl_gist_idx_102140 ON public.tbl_gist_102140 USING gist (c4 ) INCLUDE (c1 ,c2 ,c3 )",
    context=PROCESS_UTILITY_TOPLEVEL, params=0x0, queryEnv=0x0, dest=0xcde5e0 <donothingDR>, completionTag=0x0) at commands/utility_hook.c:490
#5  0x0000000000926399 in ProcessUtility (pstmt=0x1ddfa18,
    queryString=0x1e4bb60 "CREATE  INDEX CONCURRENTLY  tbl_gist_idx_102140 ON public.tbl_gist_102140 USING gist (c4 ) INCLUDE (c1 ,c2 ,c3 )",
    context=PROCESS_UTILITY_TOPLEVEL, params=0x0, queryEnv=0x0, dest=0xcde5e0 <donothingDR>, completionTag=0x0) at utility.c:356
#6  0x00007f5ffa7b8f80 in CitusProcessUtility (node=0x1ddec00,
    queryString=0x1e4bb60 "CREATE  INDEX CONCURRENTLY  tbl_gist_idx_102140 ON public.tbl_gist_102140 USING gist (c4 ) INCLUDE (c1 ,c2 ,c3 )",
    context=PROCESS_UTILITY_TOPLEVEL, params=0x0, dest=0xcde5e0 <donothingDR>, completionTag=0x0) at commands/utility_hook.c:97
#7  0x00007f5ffa7e85ac in LocallyExecuteUtilityTask (
    localTaskQueryCommand=0x1e4bb60 "CREATE  INDEX CONCURRENTLY  tbl_gist_idx_102140 ON public.tbl_gist_102140 USING gist (c4 ) INCLUDE (c1 ,c2 ,c3 )")
    at executor/local_executor.c:397
#8  0x00007f5ffa7e8229 in ExecuteLocalTaskListExtended (taskList=0x1ddfc10, orig_paramListInfo=0x0, distributedPlan=0x0, defaultTupleDest=0x1ddfc48,
    isUtilityCommand=true) at executor/local_executor.c:229
#9  0x00007f5ffa7e8110 in ExecuteLocalUtilityTaskList (utilityTaskList=0x1ddfc10) at executor/local_executor.c:171
#10 0x00007f5ffa7dd0c3 in ExecuteTaskListExtended (executionParams=0x1ddfab0) at executor/adaptive_executor.c:1007
#11 0x00007f5ffa7dce0c in ExecuteUtilityTaskList (utilityTaskList=0x1e4be20, localExecutionSupported=true) at executor/adaptive_executor.c:872
#12 0x00007f5ffa7ba0c5 in ExecuteDistributedDDLJob (ddlJob=0x1d792e8) at commands/utility_hook.c:693
#13 0x00007f5ffa7b9e56 in multi_ProcessUtility (pstmt=0x1cb3888,
    queryString=0x1c1fae8 "CREATE INDEX CONCURRENTLY tbl_gist_idx ON tbl_gist using gist (c4) INCLUDE (c1,c2,c3);", context=PROCESS_UTILITY_TOPLEVEL,
    params=0x0, queryEnv=0x0, dest=0x1c20db0, completionTag=0x7ffeb0978690 "") at commands/utility_hook.c:588
#14 0x0000000000926399 in ProcessUtility (pstmt=0x1c20cb8,
    queryString=0x1c1fae8 "CREATE INDEX CONCURRENTLY tbl_gist_idx ON tbl_gist using gist (c4) INCLUDE (c1,c2,c3);", context=PROCESS_UTILITY_TOPLEVEL,
    params=0x0, queryEnv=0x0, dest=0x1c20db0, completionTag=0x7ffeb0978690 "") at utility.c:356
#15 0x0000000000925377 in PortalRunUtility (portal=0x1cf87d8, pstmt=0x1c20cb8, isTopLevel=true, setHoldSnapshot=false, dest=0x1c20db0,
    completionTag=0x7ffeb0978690 "") at pquery.c:1175
#16 0x0000000000925593 in PortalRunMulti (portal=0x1cf87d8, isTopLevel=true, setHoldSnapshot=false, dest=0x1c20db0, altdest=0x1c20db0,
    completionTag=0x7ffeb0978690 "") at pquery.c:1321
#17 0x0000000000924a4d in PortalRun (portal=0x1cf87d8, count=9223372036854775807, isTopLevel=true, run_once=true, dest=0x1c20db0, altdest=0x1c20db0,
    completionTag=0x7ffeb0978690 "") at pquery.c:796
#18 0x000000000091e5b4 in exec_simple_query (
    query_string=0x1c1fae8 "CREATE INDEX CONCURRENTLY tbl_gist_idx ON tbl_gist using gist (c4) INCLUDE (c1,c2,c3);") at postgres.c:1215
#19 0x0000000000922a7c in PostgresMain (argc=1, argv=0x1cb8998, dbname=0x1cb87d8 "postgres", username=0x1cb87b0 "postgres") at postgres.c:4247
#20 0x00000000008713bd in BackendRun (port=0x1c3b9f0) at postmaster.c:4448
#21 0x0000000000870b06 in BackendStartup (port=0x1c3b9f0) at postmaster.c:4139
#22 0x000000000086cc46 in ServerLoop () at postmaster.c:1704
#23 0x000000000086c46d in PostmasterMain (argc=3, argv=0x1c1a760) at postmaster.c:1377
#24 0x00000000007850f7 in main (argc=3, argv=0x1c1a760) at main.c:228
```

**Comment by marcocitus** [comment]
I think we need to avoid local execution for commands like CREATE INDEX CONCURRENTLY.

**Comment by marcocitus** [comment]
Hmz, actually, we cannot do CREATE INDEX CONCURRENTLY via a localhost connection either because it waits for other transactions to finish and would thus get stuck forever.

**Comment by marcocitus** [comment]
I think we should do it over a localhost connection, but finish the CREATE INDEX CONCURRENTLY on the shards before we create an index on the shell table.

**Comment by onderkalaci** [comment]
Just note that this happens with distributed tables on single-node Citus, so nothing specific to reference tables
