### ISSUE TITLE
Inserting values from generate_series might give assertion failure

### ISSUE THREAD

**Issue by onurctirtir** [citusdata/citus#4091]
```sql
CREATE TABLE no_index_cleanup (i INT PRIMARY KEY, t TEXT);
SELECT create_reference_table('no_index_cleanup');
INSERT INTO no_index_cleanup(i, t)
VALUES (
  generate_series(1,30),
  repeat('1234567890',269)
);
```

Above insert crashes due to assertion failure with below backtrace:

```c
#2  0x0000000000aae380 in ExceptionalCondition (conditionName=0x7f5ffa87f990 "!(currentPlan->fastPathRouterPlan || !EnableFastPathRouterPlanner)",
    errorType=0x7f5ffa87f861 "FailedAssertion", fileName=0x7f5ffa87f922 "executor/citus_custom_scan.c", lineNumber=346) at assert.c:54
#3  0x00007f5ffa7e21aa in CitusBeginModifyScan (node=0x1dbefe0, estate=0x1dbed58, eflags=0) at executor/citus_custom_scan.c:346
#4  0x00007f5ffa7e1f01 in CitusBeginScan (node=0x1dbefe0, estate=0x1dbed58, eflags=0) at executor/citus_custom_scan.c:196
#5  0x0000000000732c4e in ExecInitCustomScan (cscan=0x1db9e60, estate=0x1dbed58, eflags=0) at nodeCustom.c:103
#6  0x000000000071a276 in ExecInitNode (node=0x1db9e60, estate=0x1dbed58, eflags=0) at execProcnode.c:282
#7  0x00000000007109a7 in InitPlan (queryDesc=0x1dc95c8, eflags=0) at execMain.c:1020
#8  0x000000000070f829 in standard_ExecutorStart (queryDesc=0x1dc95c8, eflags=0) at execMain.c:266
#9  0x00007f5ffa7ea47e in CitusExecutorStart (queryDesc=0x1dc95c8, eflags=0) at executor/multi_executor.c:116
#10 0x000000000070f5a5 in ExecutorStart (queryDesc=0x1dc95c8, eflags=0) at execMain.c:146
#11 0x0000000000923aa1 in ProcessQuery (plan=0x1dba2a0,
    sourceText=0x1c1fae8 "INSERT INTO no_index_cleanup(i, t)\nVALUES (\n  generate_series(1,30),\n  repeat('1234567890',269)\n);", params=0x0,
    queryEnv=0x0, dest=0x1dcab48, completionTag=0x7ffeb0978690 "") at pquery.c:156
#12 0x00000000009254f0 in PortalRunMulti (portal=0x1cf87d8, isTopLevel=true, setHoldSnapshot=false, dest=0x1dcab48, altdest=0x1dcab48,
    completionTag=0x7ffeb0978690 "") at pquery.c:1283
#13 0x0000000000924a4d in PortalRun (portal=0x1cf87d8, count=9223372036854775807, isTopLevel=true, run_once=true, dest=0x1dcab48, altdest=0x1dcab48,
    completionTag=0x7ffeb0978690 "") at pquery.c:796
#14 0x000000000091e5b4 in exec_simple_query (
    query_string=0x1c1fae8 "INSERT INTO no_index_cleanup(i, t)\nVALUES (\n  generate_series(1,30),\n  repeat('1234567890',269)\n);") at postgres.c:1215
#15 0x0000000000922a7c in PostgresMain (argc=1, argv=0x1cb8880, dbname=0x1cb86c0 "postgres", username=0x1cb8698 "postgres") at postgres.c:4247
#16 0x00000000008713bd in BackendRun (port=0x1c3b9f0) at postmaster.c:4448
#17 0x0000000000870b06 in BackendStartup (port=0x1c3b9f0) at postmaster.c:4139
#18 0x000000000086cc46 in ServerLoop () at postmaster.c:1704
#19 0x000000000086c46d in PostmasterMain (argc=3, argv=0x1c1a760) at postmaster.c:1377
#20 0x00000000007850f7 in main (argc=3, argv=0x1c1a760) at main.c:228
```

And if we disable assertions, we get no errors nor warnings.

**Comment by onurctirtir** [comment]
Another similar crash that applies to distributed tables, on single node:

```sql
create table parent_tab (id int) partition by range (id);
SELECT create_distributed_table('parent_tab', 'id');
insert into parent_tab values (generate_series(0,29));
```

**Comment by onurctirtir** [comment]
Again, another similar crash that applies to distributed tables, on single node:

```sql
create or replace function part_hashint4_noop(value int4, seed int8)
returns int8 as $$
select value + seed;
$$ language sql immutable;

create operator class part_test_int4_ops
for type int4
using hash as
operator 1 =,
function 2 part_hashint4_noop(int4, int8);

create table hash_parted (
	a int
) partition by hash (a part_test_int4_ops);
create table hpart0 partition of hash_parted for values with (modulus 4, remainder 0);
create table hpart1 partition of hash_parted for values with (modulus 4, remainder 1);
create table hpart2 partition of hash_parted for values with (modulus 4, remainder 2);
create table hpart3 partition of hash_parted for values with (modulus 4, remainder 3);

insert into hash_parted values(generate_series(1,10));
```
