### ISSUE TITLE
ON CONFLICT DO UPDATE crash

### ISSUE THREAD

**Issue by SaitTalhaNisanci** [citusdata/citus#4448]
```sql
CREATE TABLE rollup_searches_5min (
rollup_at TIMESTAMP NOT NULL,
app_id TEXT NOT NULL,
index TEXT NOT NULL,
search TEXT NOT NULL
);
SELECT create_distributed_table('rollup_searches_5min','app_id);
CREATE UNIQUE INDEX rollup_searches_5min_idx ON rollup_searches_5min (app_id, index, search, rollup_at);

[local] talha@talha:9700-21335=# insert into rollup_searches_5min(app_id, index, search, rollup_at) VALUE
S('KO4W2GBINK', 'catalog_products_en_search', 'fea', '2020-12-21 15:05:00') ON CONFLICT (app_id) DO UPDAT
E set app_id = 'textasd';
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
Time: 4.422 ms
```

backtrace:
```
Program received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) where
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007faa75382801 in __GI_abort () at abort.c:79
#2  0x0000564424b0320f in ExceptionalCondition (
    conditionName=conditionName@entry=0x7faa729fd9b2 "rte->values_lists != NIL",
    errorType=errorType@entry=0x7faa729e8ba0 "FailedAssertion",
    fileName=fileName@entry=0x7faa729fd984 "planner/distributed_planner.c",
    lineNumber=lineNumber@entry=459) at assert.c:67
#3  0x00007faa7298e6c3 in GetRTEIdentity (rte=<optimized out>) at planner/distributed_planner.c:459
#4  0x00007faa729940ef in ResultRTEIdentity (query=query@entry=0x564426882180)
    at planner/local_distributed_join_planner.c:241
#5  0x00007faa729946fe in RecursivelyPlanLocalTableJoins (query=query@entry=0x564426882180,
    context=context@entry=0x7ffc79d60df0) at planner/local_distributed_join_planner.c:216
#6  0x00007faa729b2e0d in RecursivelyPlanSubqueriesAndCTEs (query=query@entry=0x564426882180,
    context=context@entry=0x7ffc79d60df0) at planner/recursive_planning.c:361
#7  0x00007faa729b2ee2 in GenerateSubplansForSubqueriesAndCTEs (planId=planId@entry=1,
    originalQuery=originalQuery@entry=0x564426882180,
    plannerRestrictionContext=plannerRestrictionContext@entry=0x5644269fcb98)
    at planner/recursive_planning.c:238
#8  0x00007faa7298e91b in CreateDistributedPlan (planId=planId@entry=1, originalQuery=0x564426882180,
    query=0x564426882298, boundParams=0x0, hasUnresolvedParams=hasUnresolvedParams@entry=false,
    plannerRestrictionContext=0x5644269fcb98) at planner/distributed_planner.c:978
#9  0x00007faa7298f332 in CreateDistributedPlannedStmt (planContext=planContext@entry=0x7ffc79d60f40)
    at planner/distributed_planner.c:646
#10 0x00007faa7298f4be in PlanFastPathDistributedStmt (planContext=planContext@entry=0x7ffc79d60f40,
    distributionKeyValue=<optimized out>) at planner/distributed_planner.c:566
#11 0x00007faa7298f8de in distributed_planner (parse=0x564426882298, query_string=<optimized out>,
    cursorOptions=256, boundParams=0x0) at planner/distributed_planner.c:217
#12 0x00007faa6c844f88 in pgss_planner (parse=0x564426882298,
    query_string=0x564426880ce0 "insert into rollup_searches_5min(app_id, index, search, rollup_at) VALUES('KO4W2GBINK', 'catalog_products_en_search', 'fear藕粉', '2020-12-21 15:05:00') ON CONFLICT (app_id) DO
UPDATE set app_id = '"..., cursorOptions=256, boundParams=0x0) at pg_stat_statements.c:988
#13 0x00005644248f0de6 in planner (parse=parse@entry=0x564426882298,
    query_string=query_string@entry=0x564426880ce0 "insert into rollup_searches_5min(app_id, index, search, rollup_at) VALUES('KO4W2GBINK', 'catalog_products_en_search', 'fear藕粉', '2020-12-21 15:05:00') ON CONFLICT (app_id) DO UPDATE set app_id = '"..., cursorOptions=cursorOptions@entry=256,
    boundParams=boundParams@entry=0x0) at planner.c:273
#14 0x00005644249ce257 in pg_plan_query (querytree=querytree@entry=0x564426882298,
    query_string=query_string@entry=0x564426880ce0 "insert into rollup_searches_5min(app_id, index, search, rollup_at) VALUES('KO4W2GBINK', 'catalog_products_en_search', 'fear藕粉', '2020-12-21 15:05:00') ON CONFLICT (app_id) DO UPDATE set app_id = '"..., cursorOptions=cursorOptions@entry=256,
    boundParams=boundParams@entry=0x0) at postgres.c:875
#15 0x00005644249ce3cc in pg_plan_queries (querytrees=0x5644269c9fc8,
```

**Comment by SaitTalhaNisanci** [comment]
I guess my cluster was in a weird state, after clean build I don't seem to be getting this crash

**Comment by metdos** [comment]
If we can't replicate this, shall we close the issue?
