### ISSUE TITLE
Crash in lateral join when using columnar

### ISSUE THREAD

**Issue by pykello** [citusdata/citus#4600]
```sql
CREATE TABLE INT8_TBL(q1 int8, q2 int8) using columnar;

INSERT INTO INT8_TBL VALUES('  123   ','  456');
INSERT INTO INT8_TBL VALUES('123   ','4567890123456789');
INSERT INTO INT8_TBL VALUES('4567890123456789','123');
INSERT INTO INT8_TBL VALUES(+4567890123456789,'4567890123456789');
INSERT INTO INT8_TBL VALUES('+4567890123456789','-4567890123456789');

select * from
  int8_tbl a left join lateral
  (select b.q1 as bq1, c.q1 as cq1, least(a.q1,b.q1,c.q1) from
   int8_tbl b cross join int8_tbl c) ss
  on a.q2 = ss.bq1;

server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
```

Backtrace using pg12 is:

```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007f53dcd64859 in __GI_abort () at abort.c:79
#2  0x000055ef0d37a63a in ExceptionalCondition (
    conditionName=conditionName@entry=0x55ef0d52a488 "!(bms_is_subset(joinrel->lateral_relids, required_outer))", errorType=errorType@entry=0x55ef0d3d001d "FailedAssertion", 
    fileName=fileName@entry=0x55ef0d529c24 "relnode.c", lineNumber=lineNumber@entry=1369) at assert.c:54
#3  0x000055ef0d1a91ed in get_joinrel_parampathinfo (root=root@entry=0x55ef0eff6b68, 
    joinrel=joinrel@entry=0x55ef0ef98310, outer_path=outer_path@entry=0x55ef0ef97110, 
    inner_path=inner_path@entry=0x55ef0ef97ce8, sjinfo=0x7fffd94f8ae0, 
    required_outer=required_outer@entry=0x0, restrict_clauses=0x7fffd94f87c8) at relnode.c:1369
#4  0x000055ef0d19ee3e in create_nestloop_path (root=root@entry=0x55ef0eff6b68, 
    joinrel=joinrel@entry=0x55ef0ef98310, jointype=jointype@entry=JOIN_INNER, workspace=0x7fffd94f8810, 
    extra=extra@entry=0x7fffd94f8920, outer_path=outer_path@entry=0x55ef0ef97110, inner_path=0x55ef0ef97ce8, 
    restrict_clauses=<optimized out>, pathkeys=0x0, required_outer=0x0) at pathnode.c:2367
#5  0x000055ef0d16bfa2 in try_nestloop_path (root=root@entry=0x55ef0eff6b68, 
    joinrel=joinrel@entry=0x55ef0ef98310, outer_path=outer_path@entry=0x55ef0ef97110, 
    inner_path=0x55ef0ef97ce8, pathkeys=pathkeys@entry=0x0, jointype=jointype@entry=JOIN_INNER, 
    extra=0x7fffd94f8920) at joinpath.c:450
#6  0x000055ef0d16cecf in match_unsorted_outer (extra=0x7fffd94f8920, jointype=JOIN_INNER, 
    innerrel=0x55ef0ef94d10, outerrel=0x55ef0ef94140, joinrel=0x55ef0ef98310, root=0x55ef0eff6b68)
    at joinpath.c:1475
#7  add_paths_to_joinrel (root=root@entry=0x55ef0eff6b68, joinrel=joinrel@entry=0x55ef0ef98310, 
    outerrel=outerrel@entry=0x55ef0ef94140, innerrel=innerrel@entry=0x55ef0ef94d10, 
    jointype=jointype@entry=JOIN_INNER, sjinfo=sjinfo@entry=0x7fffd94f8ae0, restrictlist=0x0)
    at joinpath.c:280
#8  0x000055ef0d16ea2c in populate_joinrel_with_paths (root=0x55ef0eff6b68, rel1=0x55ef0ef94140, 
    rel2=0x55ef0ef94d10, joinrel=0x55ef0ef98310, sjinfo=0x7fffd94f8ae0, restrictlist=0x0) at joinrels.c:785
#9  0x000055ef0d16f6ad in make_join_rel (root=root@entry=0x55ef0eff6b68, rel1=rel1@entry=0x55ef0ef94140, 
    rel2=rel2@entry=0x55ef0ef94d10) at joinrels.c:738
#10 0x000055ef0d16f921 in make_rels_by_clause_joins (other_rels=<optimized out>, old_rel=<optimized out>, 
    root=<optimized out>) at joinrels.c:289
#11 join_search_one_level (root=root@entry=0x55ef0eff6b68, level=level@entry=2) at joinrels.c:111
#12 0x000055ef0d15b493 in standard_join_search (initial_rels=<optimized out>, levels_needed=3, 
    root=0x55ef0eff6b68) at allpaths.c:2881
#13 standard_join_search (root=0x55ef0eff6b68, levels_needed=3, initial_rels=<optimized out>)
    at allpaths.c:2846
#14 0x000055ef0d15b914 in make_one_rel (root=root@entry=0x55ef0eff6b68, 
    joinlist=joinlist@entry=0x55ef0ef957c8) at allpaths.c:227
#15 0x000055ef0d17e5b9 in query_planner (root=root@entry=0x55ef0eff6b68, 
    qp_callback=qp_callback@entry=0x55ef0d17f190 <standard_qp_callback>, 
    qp_extra=qp_extra@entry=0x7fffd94f8d80) at planmain.c:271
#16 0x000055ef0d182f1c in grouping_planner (root=<optimized out>, inheritance_update=false, 
    tuple_fraction=<optimized out>) at planner.c:2048
#17 0x000055ef0d185d1e in subquery_planner (glob=glob@entry=0x55ef0eff6ad0, parse=parse@entry=0x55ef0efe6e18, 
    parent_root=parent_root@entry=0x0, hasRecursion=hasRecursion@entry=false, 
    tuple_fraction=tuple_fraction@entry=0) at planner.c:1012
#18 0x000055ef0d186dc2 in standard_planner (parse=0x55ef0efe6e18, cursorOptions=256, 
    boundParams=<optimized out>) at planner.c:406
#19 0x00007f53d9b0848b in distributed_planner (parse=0x55ef0efe6e18, cursorOptions=256, boundParams=0x0)
    at planner/distributed_planner.c:226
#20 0x000055ef0d251000 in pg_plan_query (querytree=0x55ef0efe6e18, cursorOptions=256, boundParams=0x0)
    at postgres.c:878
#21 0x000055ef0d2510ed in pg_plan_queries (querytrees=<optimized out>, cursorOptions=cursorOptions@entry=256, 
    boundParams=boundParams@entry=0x0) at postgres.c:968
#22 0x000055ef0d251599 in exec_simple_query (
    query_string=0x55ef0ee02a18 "select * from\n  int8_tbl a left join lateral\n  (select b.q1 as bq1, c.q1 as cq1, least(a.q1,b.q1,c.q1) from\n   int8_tbl b cross join int8_tbl c) ss\n  on a.q2 = ss.bq1;")
    at postgres.c:1143
#23 0x000055ef0d252d23 in PostgresMain (argc=<optimized out>, argv=argv@entry=0x55ef0eeaf730, 
    dbname=<optimized out>, username=<optimized out>) at postgres.c:4247
#24 0x000055ef0d1c969a in BackendRun (port=0x55ef0ee9bad0, port=0x55ef0ee9bad0) at postmaster.c:4437
#25 BackendStartup (port=0x55ef0ee9bad0) at postmaster.c:4128
#26 ServerLoop () at postmaster.c:1704
#27 0x000055ef0d1ca512 in PostmasterMain (argc=3, argv=<optimized out>) at postmaster.c:1377
#28 0x000055ef0cef1651 in main (argc=3, argv=0x55ef0edfc480) at main.c:228

```

**Comment by pykello** [comment]
Similar crash but a different backtrace:

```sql
set default_table_access_method TO 'columnar';

CREATE TABLE prt1 (a int, b int, c varchar) PARTITION BY RANGE(a);
CREATE TABLE prt1_p1 PARTITION OF prt1 FOR VALUES FROM (0) TO (250);
CREATE TABLE prt1_p3 PARTITION OF prt1 FOR VALUES FROM (500) TO (600);
CREATE TABLE prt1_p2 PARTITION OF prt1 FOR VALUES FROM (250) TO (500);
INSERT INTO prt1 SELECT i, i % 25, to_char(i, 'FM0000') FROM generate_series(0, 599) i WHERE i % 2 = 0;
ANALYZE prt1;


CREATE TABLE prt2 (a int, b int, c varchar) PARTITION BY RANGE(b);
CREATE TABLE prt2_p1 PARTITION OF prt2 FOR VALUES FROM (0) TO (250);
CREATE TABLE prt2_p2 PARTITION OF prt2 FOR VALUES FROM (250) TO (500);
CREATE TABLE prt2_p3 PARTITION OF prt2 FOR VALUES FROM (500) TO (600);
INSERT INTO prt2 SELECT i % 25, i, to_char(i, 'FM0000') FROM generate_series(0, 599) i WHERE i % 3 = 0;
ANALYZE prt2;

SELECT * FROM prt1 t1 LEFT JOIN LATERAL
			  (SELECT t2.a AS t2a, t3.a AS t3a, least(t1.a,t2.a,t3.b) FROM prt1 t2 JOIN prt2 t3 ON (t2.a = t3.b)) ss
			  ON t1.a = ss.t2a WHERE t1.b = 0 ORDER BY t1.a;
```

backtrace:

```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007f412c751859 in __GI_abort () at abort.c:79
#2  0x00005594d206963a in ExceptionalCondition (
    conditionName=conditionName@entry=0x5594d2219410 "!(bms_is_subset(baserel->lateral_relids, required_outer))", errorType=errorType@entry=0x5594d20bf01d "FailedAssertion", 
    fileName=fileName@entry=0x5594d2218c24 "relnode.c", lineNumber=lineNumber@entry=1271) at assert.c:54
#3  0x00005594d1e97dcf in get_baserel_parampathinfo (root=root@entry=0x5594d26faa60, 
    baserel=baserel@entry=0x5594d2709f58, required_outer=required_outer@entry=0x0) at relnode.c:1271
#4  0x00005594d1e8c6ce in create_append_path (root=root@entry=0x5594d26faa60, rel=rel@entry=0x5594d2709f58, 
    subpaths=0x5594d27333c0, partial_subpaths=partial_subpaths@entry=0x0, pathkeys=pathkeys@entry=0x0, 
    required_outer=required_outer@entry=0x0, parallel_workers=0, parallel_aware=false, 
    partitioned_rels=0x5594d2733360, rows=rows@entry=-1) at pathnode.c:1236
#5  0x00005594d1e497fe in add_paths_to_append_rel (root=<optimized out>, rel=0x5594d2709f58, 
    live_childrels=0x5594d2731ce0) at allpaths.c:1524
#6  0x00005594d1e4a074 in set_append_rel_pathlist (rte=0x5594d27ff6e0, rti=4, rel=0x5594d2709f58, 
    root=0x5594d26faa60) at allpaths.c:1278
#7  set_rel_pathlist (root=root@entry=0x5594d26faa60, rel=0x5594d2709f58, rti=rti@entry=4, rte=0x5594d27ff6e0)
    at allpaths.c:480
#8  0x00005594d1e4a901 in set_base_rel_pathlists (root=0x5594d26faa60) at allpaths.c:352
#9  make_one_rel (root=root@entry=0x5594d26faa60, joinlist=joinlist@entry=0x5594d2700f70) at allpaths.c:222
#10 0x00005594d1e6d5b9 in query_planner (root=root@entry=0x5594d26faa60, 
    qp_callback=qp_callback@entry=0x5594d1e6e190 <standard_qp_callback>, 
    qp_extra=qp_extra@entry=0x7fff1a4a48d0) at planmain.c:271
#11 0x00005594d1e71f1c in grouping_planner (root=<optimized out>, inheritance_update=false, 
    tuple_fraction=<optimized out>) at planner.c:2048
#12 0x00005594d1e74d1e in subquery_planner (glob=glob@entry=0x5594d2709920, parse=parse@entry=0x5594d27ff7f8, 
    parent_root=parent_root@entry=0x0, hasRecursion=hasRecursion@entry=false, 
    tuple_fraction=tuple_fraction@entry=0) at planner.c:1012
#13 0x00005594d1e75dc2 in standard_planner (parse=0x5594d27ff7f8, cursorOptions=256, 
    boundParams=<optimized out>) at planner.c:406
#14 0x00007f41294f548b in distributed_planner (parse=0x5594d27ff7f8, cursorOptions=256, boundParams=0x0)
    at planner/distributed_planner.c:226
#15 0x00005594d1f40000 in pg_plan_query (querytree=0x5594d27ff7f8, cursorOptions=256, boundParams=0x0)
    at postgres.c:878
#16 0x00005594d1f400ed in pg_plan_queries (querytrees=<optimized out>, cursorOptions=cursorOptions@entry=256, 
    boundParams=boundParams@entry=0x0) at postgres.c:968
#17 0x00005594d1f40599 in exec_simple_query (
    query_string=0x5594d256aa18 "SELECT * FROM prt1 t1 LEFT JOIN LATERAL\n  (SELECT t2.a AS t2a, t3.a AS t3a, least(t1.a,t2.a,t3.b) FROM prt1 t2 JOIN prt2 t3 ON (t2.a = t3.b)) ss\n  ON t1.a = ss.t2a WHERE t1.b = 0 ORDER BY t1.a;") at postgres.c:1143
#18 0x00005594d1f41d23 in PostgresMain (argc=<optimized out>, argv=argv@entry=0x5594d2612650, 
    dbname=<optimized out>, username=<optimized out>) at postgres.c:4247
#19 0x00005594d1eb869a in BackendRun (port=0x5594d25e89c0, port=0x5594d25e89c0) at postmaster.c:4437
#20 BackendStartup (port=0x5594d25e89c0) at postmaster.c:4128
#21 ServerLoop () at postmaster.c:1704
#22 0x00005594d1eb9512 in PostmasterMain (argc=3, argv=<optimized out>) at postmaster.c:1377
#23 0x00005594d1be0651 in main (argc=3, argv=0x5594d2564480) at main.c:228
```
