### ISSUE TITLE
Adding generated column to a populated columnar table crashes

### ISSUE THREAD

**Issue by pykello** [citusdata/citus#4601]
```sql
CREATE TABLE itest13 (a int) using columnar;
INSERT INTO itest13 VALUES (1), (2), (3);
ALTER TABLE itest13 ADD COLUMN c int GENERATED BY DEFAULT AS IDENTITY;
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
```

backtrace with pg12:

```
#0  SelectedChunkMask (stripeSkipList=0x5594d260dcd8, stripeSkipList=0x5594d260dcd8, 
    chunksFiltered=0x5594d28367b0, whereClauseList=<optimized out>, projectedColumnList=<optimized out>)
    at ../columnar/cstore_reader.c:517
#1  LoadFilteredStripeBuffers (chunksFiltered=0x5594d28367b0, whereClauseList=<optimized out>, 
    projectedColumnList=<optimized out>, tupleDescriptor=<optimized out>, stripeMetadata=0x5594d2836cd0, 
    relation=0x7f411ece8f18) at ../columnar/cstore_reader.c:342
#2  ColumnarReadNextRow (readState=0x5594d2836760, columnValues=0x5594d274bc20, columnNulls=0x5594d274bc28)
    at ../columnar/cstore_reader.c:152
#3  0x00007f4129540520 in columnar_getnextslot (sscan=0x5594d2835ec8, direction=<optimized out>, 
    slot=0x5594d274bbd8) at ../columnar/cstore_tableam.c:302
#4  0x00005594d1d8049c in table_scan_getnextslot (slot=0x5594d274bbd8, direction=ForwardScanDirection, 
    sscan=0x5594d2835ec8) at ../../../src/include/access/tableam.h:875
#5  ATRewriteTable (tab=tab@entry=0x5594d2760808, OIDNewHeap=OIDNewHeap@entry=32783, 
    lockmode=lockmode@entry=8) at tablecmds.c:4941
#6  0x00005594d1d95dba in ATRewriteTables (lockmode=8, wqueue=0x7fff1a4a4330, parsetree=0x5594d2716d00)
    at tablecmds.c:4644
#7  ATController (parsetree=parsetree@entry=0x5594d2716d00, rel=<optimized out>, cmds=<optimized out>, 
    recurse=<optimized out>, lockmode=lockmode@entry=8) at tablecmds.c:3849
#8  0x00005594d1d96184 in AlterTable (relid=relid@entry=32778, lockmode=lockmode@entry=8, 
    stmt=stmt@entry=0x5594d2716d00) at tablecmds.c:3507
#9  0x00005594d1f47543 in ProcessUtilitySlow (pstate=pstate@entry=0x5594d2716ba8, 
    pstmt=pstmt@entry=0x5594d278fea8, 
    queryString=queryString@entry=0x5594d256aa18 "ALTER TABLE itest13 ADD COLUMN c int GENERATED BY DEFAULT AS IDENTITY;", context=context@entry=PROCESS_UTILITY_TOPLEVEL, params=params@entry=0x0, 
    queryEnv=queryEnv@entry=0x0, completionTag=0x7fff1a4a4d40 "", dest=0x5594d256bd58) at utility.c:1131
#10 0x00005594d1f46041 in standard_ProcessUtility (pstmt=pstmt@entry=0x5594d278fea8, 
    queryString=queryString@entry=0x5594d256aa18 "ALTER TABLE itest13 ADD COLUMN c int GENERATED BY DEFAULT AS IDENTITY;", context=context@entry=PROCESS_UTILITY_TOPLEVEL, params=params@entry=0x0, 
    queryEnv=queryEnv@entry=0x0, dest=dest@entry=0x5594d256bd58, completionTag=0x7fff1a4a4d40 "")
    at utility.c:927
#11 0x00007f41294b368c in ProcessUtilityInternal (pstmt=0x5594d278fea8, pstmt@entry=0x5594d256bc60, 
    queryString=queryString@entry=0x5594d256aa18 "ALTER TABLE itest13 ADD COLUMN c int GENERATED BY DEFAULT AS
IDENTITY;", context=context@entry=PROCESS_UTILITY_TOPLEVEL, params=params@entry=0x0, 
    queryEnv=queryEnv@entry=0x0, dest=dest@entry=0x5594d256bd58, completionTag=0x7fff1a4a4d40 "")
    at commands/utility_hook.c:558
#12 0x00007f41294b3f63 in multi_ProcessUtility (pstmt=0x5594d256bc60, 
    queryString=0x5594d256aa18 "ALTER TABLE itest13 ADD COLUMN c int GENERATED BY DEFAULT AS IDENTITY;", 
    context=PROCESS_UTILITY_TOPLEVEL, params=0x0, queryEnv=0x0, dest=0x5594d256bd58, 
    completionTag=0x7fff1a4a4d40 "") at commands/utility_hook.c:251
#13 0x00005594d1f42f86 in PortalRunUtility (portal=0x5594d264a2d8, pstmt=0x5594d256bc60, 
    isTopLevel=<optimized out>, setHoldSnapshot=<optimized out>, dest=0x5594d256bd58, 
    completionTag=0x7fff1a4a4d40 "") at pquery.c:1175
#14 0x00005594d1f43b31 in PortalRunMulti (portal=portal@entry=0x5594d264a2d8, 
    isTopLevel=isTopLevel@entry=true, setHoldSnapshot=setHoldSnapshot@entry=false, 
    dest=dest@entry=0x5594d256bd58, altdest=altdest@entry=0x5594d256bd58, 
    completionTag=completionTag@entry=0x7fff1a4a4d40 "") at pquery.c:1321
#15 0x00005594d1f448e9 in PortalRun (portal=portal@entry=0x5594d264a2d8, 
    count=count@entry=9223372036854775807, isTopLevel=isTopLevel@entry=true, run_once=run_once@entry=true, 
    dest=dest@entry=0x5594d256bd58, altdest=altdest@entry=0x5594d256bd58, completionTag=0x7fff1a4a4d40 "")
    at pquery.c:796
#16 0x00005594d1f40488 in exec_simple_query (
    query_string=0x5594d256aa18 "ALTER TABLE itest13 ADD COLUMN c int GENERATED BY DEFAULT AS IDENTITY;")
    at postgres.c:1215
#17 0x00005594d1f41d23 in PostgresMain (argc=<optimized out>, argv=argv@entry=0x5594d2612360, 
    dbname=<optimized out>, username=<optimized out>) at postgres.c:4247
#18 0x00005594d1eb869a in BackendRun (port=0x5594d25dec00, port=0x5594d25dec00) at postmaster.c:4437
#19 BackendStartup (port=0x5594d25dec00) at postmaster.c:4128
#20 ServerLoop () at postmaster.c:1704
#21 0x00005594d1eb9512 in PostmasterMain (argc=3, argv=<optimized out>) at postmaster.c:1377
#22 0x00005594d1be0651 in main (argc=3, argv=0x5594d2564480) at main.c:228
```

**Comment by pykello** [comment]
Following also fails with a similar backtrace:

```sql
create table atacc1 (a int) using columnar;
insert into atacc1 values(1);
alter table atacc1
  add column b float8 not null default random(),
  add primary key(a);
```
