### ISSUE TITLE
Adding domain column to columnar crashes

### ISSUE THREAD

**Issue by pykello** [citusdata/citus#4602]
```sql
create domain str_domain as text not null;

create table domain_test (a int, b int) using columnar;

insert into domain_test values (1, 2);
insert into domain_test values (1, 2);

alter table domain_test add column c str_domain;

alter table domain_test add column c str_domain;
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.

```

trace with pg12:

```
#0  0x00007f412953f01a in ReadStripeNextRow (stripeBuffers=<optimized out>, chunkIndex=<optimized out>, 
    chunkData=<optimized out>, chunkData=<optimized out>, columnNulls=0x5594d27738e0, 
    columnValues=0x5594d27738d0, chunkRowIndex=0, projectedColumnList=0x5594d27536d8)
    at ../columnar/cstore_reader.c:410
#1  ColumnarReadNextRow (readState=<optimized out>, columnValues=<optimized out>, columnNulls=<optimized out>)
    at ../columnar/cstore_reader.c:197
#2  0x00007f4129540520 in columnar_getnextslot (sscan=0x5594d2753438, direction=<optimized out>, 
    slot=0x5594d2773888) at ../columnar/cstore_tableam.c:302
#3  0x00005594d1d8049c in table_scan_getnextslot (slot=0x5594d2773888, direction=ForwardScanDirection, 
    sscan=0x5594d2753438) at ../../../src/include/access/tableam.h:875
#4  ATRewriteTable (tab=tab@entry=0x5594d26f2c18, OIDNewHeap=OIDNewHeap@entry=65541, 
    lockmode=lockmode@entry=8) at tablecmds.c:4941
#5  0x00005594d1d95dba in ATRewriteTables (lockmode=8, wqueue=0x7fff1a4a4330, parsetree=0x5594d2785a78)
    at tablecmds.c:4644
#6  ATController (parsetree=parsetree@entry=0x5594d2785a78, rel=<optimized out>, cmds=<optimized out>, 
    recurse=<optimized out>, lockmode=lockmode@entry=8) at tablecmds.c:3849
#7  0x00005594d1d96184 in AlterTable (relid=relid@entry=65538, lockmode=lockmode@entry=8, 
    stmt=stmt@entry=0x5594d2785a78) at tablecmds.c:3507
#8  0x00005594d1f47543 in ProcessUtilitySlow (pstate=pstate@entry=0x5594d2785960, 
    pstmt=pstmt@entry=0x5594d2785558, 
    queryString=queryString@entry=0x5594d256aa18 "alter table domain_test add column c str_domain;", 
    context=context@entry=PROCESS_UTILITY_TOPLEVEL, params=params@entry=0x0, queryEnv=queryEnv@entry=0x0, 
    completionTag=0x7fff1a4a4d40 "", dest=0x5594d256bb80) at utility.c:1131
#9  0x00005594d1f46041 in standard_ProcessUtility (pstmt=pstmt@entry=0x5594d2785558, 
    queryString=queryString@entry=0x5594d256aa18 "alter table domain_test add column c str_domain;", 
    context=context@entry=PROCESS_UTILITY_TOPLEVEL, params=params@entry=0x0, queryEnv=queryEnv@entry=0x0, 
    dest=dest@entry=0x5594d256bb80, completionTag=0x7fff1a4a4d40 "") at utility.c:927
#10 0x00007f41294b368c in ProcessUtilityInternal (pstmt=0x5594d2785558, pstmt@entry=0x5594d256ba88, 
    queryString=queryString@entry=0x5594d256aa18 "alter table domain_test add column c str_domain;", 
    context=context@entry=PROCESS_UTILITY_TOPLEVEL, params=params@entry=0x0, queryEnv=queryEnv@entry=0x0, 
    dest=dest@entry=0x5594d256bb80, completionTag=0x7fff1a4a4d40 "") at commands/utility_hook.c:558
#11 0x00007f41294b3f63 in multi_ProcessUtility (pstmt=0x5594d256ba88, 
    queryString=0x5594d256aa18 "alter table domain_test add column c str_domain;", 
    context=PROCESS_UTILITY_TOPLEVEL, params=0x0, queryEnv=0x0, dest=0x5594d256bb80, 
    completionTag=0x7fff1a4a4d40 "") at commands/utility_hook.c:251
#12 0x00005594d1f42f86 in PortalRunUtility (portal=0x5594d264b6e8, pstmt=0x5594d256ba88, 
    isTopLevel=<optimized out>, setHoldSnapshot=<optimized out>, dest=0x5594d256bb80, 
    completionTag=0x7fff1a4a4d40 "") at pquery.c:1175
#13 0x00005594d1f43b31 in PortalRunMulti (portal=portal@entry=0x5594d264b6e8, 
    isTopLevel=isTopLevel@entry=true, setHoldSnapshot=setHoldSnapshot@entry=false, 
    dest=dest@entry=0x5594d256bb80, altdest=altdest@entry=0x5594d256bb80, 
    completionTag=completionTag@entry=0x7fff1a4a4d40 "") at pquery.c:1321
#14 0x00005594d1f448e9 in PortalRun (portal=portal@entry=0x5594d264b6e8, 
    count=count@entry=9223372036854775807, isTopLevel=isTopLevel@entry=true, run_once=run_once@entry=true, 
    dest=dest@entry=0x5594d256bb80, altdest=altdest@entry=0x5594d256bb80, completionTag=0x7fff1a4a4d40 "")
    at pquery.c:796
#15 0x00005594d1f40488 in exec_simple_query (
    query_string=0x5594d256aa18 "alter table domain_test add column c str_domain;") at postgres.c:1215
#16 0x00005594d1f41d23 in PostgresMain (argc=<optimized out>, argv=argv@entry=0x5594d26197a0, 
    dbname=<optimized out>, username=<optimized out>) at postgres.c:4247
#17 0x00005594d1eb869a in BackendRun (port=0x5594d25e9330, port=0x5594d25e9330) at postmaster.c:4437
#18 BackendStartup (port=0x5594d25e9330) at postmaster.c:4128
#19 ServerLoop () at postmaster.c:1704
#20 0x00005594d1eb9512 in PostmasterMain (argc=3, argv=<optimized out>) at postmaster.c:1377
#21 0x00005594d1be0651 in main (argc=3, argv=0x5594d2564480) at main.c:228
```

**Comment by pykello** [comment]
Similar crash:

```sql
set default_table_access_method TO 'columnar';
CREATE TABLE has_volatile AS
SELECT * FROM generate_series(1,10) id;
ALTER TABLE has_volatile ADD col4 int DEFAULT (random() * 10000)::int;
```

**Comment by jeff-davis** [comment]
Duplicate of #4601
