### ISSUE TITLE
Insert CTE Crash

### ISSUE THREAD

**Issue by SaitTalhaNisanci** [citusdata/citus#4663]
```sql
create table table1 (a int);
create table table2 (a text);
select create_distributed_table('table1','a');
select create_distributed_table('table2','a');
with wcte as (insert into table1 values (42))
  insert into table2 values ('hello world');
```

Gdb:
```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007fb9f2f3f801 in __GI_abort () at abort.c:79
#2  0x000055acd49f1c96 in ExceptionalCondition (conditionName=<optimized out>,
    errorType=<optimized out>, fileName=<optimized out>, lineNumber=<optimized out>)
    at assert.c:54
#3  0x00007fb9f0527e8a in RegenerateTaskListForInsert (workerJob=0x2)
    at executor/citus_custom_scan.c:472
#4  0x00007fb9f0527f90 in CitusBeginModifyScan (node=0x55acd5d5bf50, estate=<optimized out>,
    eflags=<optimized out>) at executor/citus_custom_scan.c:347
#5  0x000055acd4749dd8 in ExecInitCustomScan (cscan=0x55acd5d5bf50, cscan@entry=0x55acd5d511e8,
    estate=0x55acd5d511e8, estate@entry=0x55acd5d5bc88, eflags=65002, eflags@entry=0)
    at nodeCustom.c:103
#6  0x000055acd4737e95 in ExecInitNode (node=node@entry=0x55acd5d511e8,
    estate=estate@entry=0x55acd5d5bc88, eflags=eflags@entry=0) at execProcnode.c:282
#7  0x000055acd4731eba in InitPlan (queryDesc=queryDesc@entry=0x55acd5ce4ac8,
    eflags=eflags@entry=0) at execMain.c:1020
#8  0x000055acd473206c in standard_ExecutorStart (queryDesc=0x55acd5ce4ac8, eflags=0)
    at execMain.c:266
#9  0x00007fb9f052d05a in CitusCustomScanStateWalker (planState=0x2,
    citusCustomScanStates=0x7fff60befdd0) at executor/multi_executor.c:273
#10 0x00007fb9ea3fc729 in pgss_ExecutorStart (queryDesc=0x55acd5d513c0, eflags=<optimized out>)
    at pg_stat_statements.c:853
#11 0x000055acd4732164 in ExecutorStart (queryDesc=queryDesc@entry=0x55acd5ce4ac8,
    eflags=eflags@entry=0) at execMain.c:146
#12 0x000055acd48be79d in ProcessQuery (plan=plan@entry=0x55acd5d513c0,
    sourceText=<optimized out>, params=0x0, queryEnv=0x0, dest=dest@entry=0x55acd5d51630,
    completionTag=completionTag@entry=0x7fff60bf0570 "") at pquery.c:156
#13 0x000055acd48be999 in PortalRunMulti (portal=portal@entry=0x55acd5ca22c8,
    isTopLevel=isTopLevel@entry=true, setHoldSnapshot=setHoldSnapshot@entry=false,
    dest=dest@entry=0x55acd5d51630, altdest=altdest@entry=0x55acd5d51630,
    completionTag=completionTag@entry=0x7fff60bf0570 "") at pquery.c:1283
#14 0x000055acd48bf920 in PortalRun (portal=portal@entry=0x55acd5ca22c8,
    count=count@entry=9223372036854775807, isTopLevel=isTopLevel@entry=true,
    run_once=run_once@entry=true, dest=dest@entry=0x55acd5d51630,
    altdest=altdest@entry=0x55acd5d51630, completionTag=0x7fff60bf0570 "") at pquery.c:796
#15 0x000055acd48bb9c6 in exec_simple_query (
    query_string=query_string@entry=0x55acd5bcbcb8 "with wcte as (insert into table1 values (42))\n  insert into table2 values ('hello world');") at postgres.c:1215
#16 0x000055acd48bda78 in PostgresMain (argc=<optimized out>, argv=argv@entry=0x55acd5c68338,
    dbname=<optimized out>, username=<optimized out>) at postgres.c:4247
#17 0x000055acd482cd15 in BackendRun (port=port@entry=0x55acd5c65f70) at postmaster.c:4448
#18 0x000055acd48301b0 in BackendStartup (port=port@entry=0x55acd5c65f70) at postmaster.c:4139
#19 0x000055acd48304cf in ServerLoop () at postmaster.c:1704
#20 0x000055acd48318f9 in PostmasterMain (argc=5, argv=<optimized out>) at postmaster.c:1377
#21 0x000055acd478868f in main (argc=5, argv=0x55acd5bc39f0) at main.c:228
```

**Comment by naisila** [comment]
It seems that we always defer shard pruning for inserts, however we don't allow fastpathrouterquery for inserts with CTE's as this one.

For example, this one also crashes:
with wcte as (select * from table1)
  insert into table2 values ('hello world');

**Comment by onurctirtir** [comment]
with non-optimized back-trace:

```c
#0  0x00007f54911bc428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007f54911be02a in __GI_abort () at abort.c:89
#2  0x0000000000b0513e in ExceptionalCondition (conditionName=0x7f548ea9f9f0 "currentPlan->fastPathRouterPlan || !EnableFastPathRouterPlanner",
    errorType=0x7f548ea9f8e1 "FailedAssertion", fileName=0x7f548ea9f988 "executor/citus_custom_scan.c", lineNumber=347) at assert.c:67
#3  0x00007f548e9db2b4 in CitusBeginModifyScan (node=0x26965d0, estate=0x2696360, eflags=0) at executor/citus_custom_scan.c:347
#4  0x00007f548e9db00b in CitusBeginScan (node=0x26965d0, estate=0x2696360, eflags=0) at executor/citus_custom_scan.c:196
#5  0x000000000075abc5 in ExecInitCustomScan (cscan=0x268fdd8, estate=0x2696360, eflags=0) at nodeCustom.c:102
#6  0x000000000073e0bc in ExecInitNode (node=0x268fdd8, estate=0x2696360, eflags=0) at execProcnode.c:282
#7  0x0000000000733c65 in InitPlan (queryDesc=0x267f870, eflags=0) at execMain.c:1020
#8  0x0000000000732918 in standard_ExecutorStart (queryDesc=0x267f870, eflags=0) at execMain.c:266
#9  0x00007f548e9e3569 in CitusExecutorStart (queryDesc=0x267f870, eflags=0) at executor/multi_executor.c:123
#10 0x0000000000732686 in ExecutorStart (queryDesc=0x267f870, eflags=0) at execMain.c:146
#11 0x000000000096fa1a in ProcessQuery (plan=0x268ffa0,
    sourceText=0x250aaf0 "with wcte as (insert into table1 values (42))\n  insert into table2 values ('hello world');", params=0x0, queryEnv=0x0,
    dest=0x2690288, qc=0x7ffd1d6ebc00) at pquery.c:155
#12 0x00000000009714b1 in PortalRunMulti (portal=0x25daff0, isTopLevel=true, setHoldSnapshot=false, dest=0x2690288, altdest=0x2690288, qc=0x7ffd1d6ebc00)
    at pquery.c:1265
#13 0x00000000009709dd in PortalRun (portal=0x25daff0, count=9223372036854775807, isTopLevel=true, run_once=true, dest=0x2690288, altdest=0x2690288,
    qc=0x7ffd1d6ebc00) at pquery.c:779
#14 0x000000000096a60c in exec_simple_query (
    query_string=0x250aaf0 "with wcte as (insert into table1 values (42))\n  insert into table2 values ('hello world');") at postgres.c:1239
#15 0x000000000096e96d in PostgresMain (argc=1, argv=0x259f0f0, dbname=0x259efe8 "postgres", username=0x259efc0 "postgres") at postgres.c:4315
#16 0x00000000008b5ca3 in BackendRun (port=0x2592810) at postmaster.c:4536
#17 0x00000000008b541c in BackendStartup (port=0x2592810) at postmaster.c:4220
#18 0x00000000008b1851 in ServerLoop () at postmaster.c:1739
#19 0x00000000008b1080 in PostmasterMain (argc=3, argv=0x2505760) at postmaster.c:1412
#20 0x00000000007b0914 in main (argc=3, argv=0x2505760) at main.c:210
```

Similar to ones in #4091.
At least, throws same assert failure.
