### ISSUE TITLE
Intersect + union all crash with range distributed table

### ISSUE THREAD

**Issue by SaitTalhaNisanci** [citusdata/citus#4664]
```sql
CREATE TABLE INT8_TBL(q1 int8, q2 int8);
SELECT create_distributed_table('int8_tbl','q1','range');
(((SELECT q1 FROM int8_tbl INTERSECT SELECT q2 FROM int8_tbl ORDER BY 1))) UNION ALL SELECT q2 FROM int8_tbl;
```

backtrace:

```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007fb9f2f3f801 in __GI_abort () at abort.c:79
#2  0x000055acd49f1c96 in ExceptionalCondition (conditionName=<optimized out>,
    errorType=<optimized out>, fileName=<optimized out>, lineNumber=<optimized out>)
    at assert.c:54
#3  0x00007fb9f052125f in get_setop_query (setOp=0x55acd5d1cf28, query=0x55acd5d1ce10,
    context=0x7fff60befd10, resultDesc=0x0) at deparser/ruleutils_12.c:2637
#4  0x00007fb9f0521108 in get_insert_query_def (query=0x0, context=0x0)
    at deparser/ruleutils_12.c:3178
#5  0x00007fb9f05224d0 in get_basic_select_query (query=0x0, context=0x55acd5d1ce10,
    resultDesc=0x0) at deparser/ruleutils_12.c:2351
#6  0x00007fb9f052076f in get_query_def_extended (query=0x55acd5d1ce10, buf=0x7fb9e09b1b48,
    parentnamespace=0x0, distrelid=0, shardid=0, resultDesc=0x0, prettyFlags=0, wrapColumn=0,
    startIndent=0) at deparser/ruleutils_12.c:1945
#7  0x00007fb9f052084c in get_query_def_extended (query=0x7fb9e09b1b48, buf=0x55acd5d5e7a8,
    parentnamespace=0x55acd5d1ce10, distrelid=3587651592, shardid=0, resultDesc=0x550100000000,
    prettyFlags=0, wrapColumn=-707401816, startIndent=1623129728)
    at /home/talha/.pgenv/pgsql-12.3/include/server/nodes/pg_list.h:91
#8  0x00007fb9f0520877 in get_query_def_extended (
    query=0x7fb9f052084c <get_query_def_extended+316>, buf=0x0, parentnamespace=0x0,
    distrelid=3768261448, shardid=0, resultDesc=0x0, prettyFlags=0, wrapColumn=-707401816,
    startIndent=-722353760) at deparser/ruleutils_12.c:1967
#9  0x00007fb9f05495b4 in ReplaceRelationConstraintByShardConstraint (
    relationShardList=<optimized out>, onConflict=0x7fff60befe50)
    at planner/deparse_shard_query.c:368
#10 0x00007fb9f054980c in UpdateTaskQueryString (query=0x2, distributedTableId=1623128496,
    valuesRTE=0x0, task=0x55acd4f1c1a0 <CurrentMemoryContext>)
    at planner/deparse_shard_query.c:155
#11 0x00007fb9f052c2fd in SetLocalExecutionStatus (newStatus=(unknown: 4032075788))
    at executor/local_executor.c:675
#12 0x00007fb9f0525304 in CleanUpSessions (execution=<optimized out>)
    at executor/adaptive_executor.c:1681
#13 0x00007fb9f0527747 in AdaptiveExecutor (scanState=0x7fff60beff60)
    at executor/adaptive_executor.c:793
#14 0x00007fb9f0527fcb in list_head (l=0x0)
    at /home/talha/.pgenv/pgsql-12.3/include/server/nodes/pg_list.h:79
#15 CitusBeginModifyScan (node=0x0, estate=<optimized out>, eflags=<optimized out>)
    at executor/citus_custom_scan.c:394
#16 0x000055acd4749c66 in ExecCustomScan (pstate=0x55acd5d5e710) at nodeCustom.c:116
#17 0x000055acd4737aca in ExecProcNodeFirst (node=0x55acd5d3f780) at execProcnode.c:445
#18 0x000055acd47301f3 in ExecProcNode (node=0x55acd5d3f780)
    at ../../../src/include/executor/executor.h:239
#19 ExecutePlan (estate=0x7fff60bf0010, estate@entry=0x55acd5d3f438, planstate=0x55acd5d3f780,
    use_parallel_mode=<optimized out>, operation=operation@entry=CMD_SELECT,
    sendTuples=sendTuples@entry=true, numberTuples=1945555039024062464, numberTuples@entry=0,
    direction=ForwardScanDirection, dest=0x55acd5d5e710, execute_once=true) at execMain.c:1646
#20 0x000055acd4730e6d in standard_ExecutorRun (queryDesc=0x55acd5d3f028,
    direction=ForwardScanDirection, count=0, execute_once=<optimized out>) at execMain.c:364
```

**Comment by onurctirtir** [comment]
Same as https://github.com/citusdata/citus/issues/4093
