### ISSUE TITLE
Inserting domain over array of composite type crashes 

### ISSUE THREAD

**Issue by onurctirtir** [citusdata/citus#4704]
Might be similar to #4085.

On single node:

```sql
create type comptype as (r float8, i float8);
create domain dcomptypea as comptype[];
create table dcomptable (d1 dcomptypea unique);

SELECT create_distributed_table('dcomptable', 'd1');

insert into dcomptable values (array[row(1,2)]::dcomptypea);
```

```c
#0  0x0000000000000000 in ?? ()
#1  0x0000000000b0fbac in FunctionCall1Coll (flinfo=0x315e940, collation=0, arg1=51927200) at fmgr.c:1142
#2  0x00007f1c81d97e49 in FindShardInterval (partitionColumnValue=51927200, cacheEntry=0x3141770) at utils/shardinterval_utils.c:266
#3  0x00007f1c81d5cc27 in BuildRoutesForInsert (query=0x3184ae0, planningError=0x7ffcd54e59b0) at planner/multi_router_planner.c:2981
#4  0x00007f1c81d5a7dc in RouterInsertTaskList (query=0x3184ae0, parametersInQueryResolved=true, planningError=0x7ffcd54e59b0)
    at planner/multi_router_planner.c:1659
#5  0x00007f1c81cff461 in RegenerateTaskListForInsert (workerJob=0x3184a28) at executor/citus_custom_scan.c:478
#6  0x00007f1c81cff2cc in CitusBeginModifyScan (node=0x3157a50, estate=0x3157810, eflags=0) at executor/citus_custom_scan.c:355
#7  0x00007f1c81cff00b in CitusBeginScan (node=0x3157a50, estate=0x3157810, eflags=0) at executor/citus_custom_scan.c:196
#8  0x000000000075abc5 in ExecInitCustomScan (cscan=0x3170fb0, estate=0x3157810, eflags=0) at nodeCustom.c:102
#9  0x000000000073e0bc in ExecInitNode (node=0x3170fb0, estate=0x3157810, eflags=0) at execProcnode.c:282
#10 0x0000000000733c65 in InitPlan (queryDesc=0x3084b30, eflags=0) at execMain.c:1020
#11 0x0000000000732918 in standard_ExecutorStart (queryDesc=0x3084b30, eflags=0) at execMain.c:266
#12 0x00007f1c81d07569 in CitusExecutorStart (queryDesc=0x3084b30, eflags=0) at executor/multi_executor.c:123
#13 0x0000000000732686 in ExecutorStart (queryDesc=0x3084b30, eflags=0) at execMain.c:146
#14 0x000000000096fa1a in ProcessQuery (plan=0x2ff98c8, sourceText=0x2ff7af0 "insert into dcomptable values (array[row(1,2)]::dcomptypea);", params=0x0,
    queryEnv=0x0, dest=0x3170ce0, qc=0x7ffcd54e6080) at pquery.c:155
#15 0x00000000009714b1 in PortalRunMulti (portal=0x30c7ff0, isTopLevel=true, setHoldSnapshot=false, dest=0x3170ce0, altdest=0x3170ce0, qc=0x7ffcd54e6080)
    at pquery.c:1265
#16 0x00000000009709dd in PortalRun (portal=0x30c7ff0, count=9223372036854775807, isTopLevel=true, run_once=true, dest=0x3170ce0, altdest=0x3170ce0,
    qc=0x7ffcd54e6080) at pquery.c:779
#17 0x000000000096a60c in exec_simple_query (query_string=0x2ff7af0 "insert into dcomptable values (array[row(1,2)]::dcomptypea);") at postgres.c:1239
#18 0x000000000096e96d in PostgresMain (argc=1, argv=0x308c0f0, dbname=0x308bfe8 "postgres", username=0x308bfc0 "postgres") at postgres.c:4315
#19 0x00000000008b5ca3 in BackendRun (port=0x307f810) at postmaster.c:4536
#20 0x00000000008b541c in BackendStartup (port=0x307f810) at postmaster.c:4220
#21 0x00000000008b1851 in ServerLoop () at postmaster.c:1739
#22 0x00000000008b1080 in PostmasterMain (argc=3, argv=0x2ff2760) at postmaster.c:1412
#23 0x00000000007b0914 in main (argc=3, argv=0x2ff2760) at main.c:210
```

**Comment by c2main** [comment]
it looks like it's fixed, not sure if https://github.com/citusdata/citus/pull/7912 is related but it's very closed topic.
