### ISSUE TITLE
Check for maximum number of arguments allowed in a function should work like pg standard

### ISSUE THREAD

**Issue by akoerbe** [citusdata/citus#4939]
Postgres (in this case I'm using PG13) allows the creation of functions with [FUNC_MAX_ARGS] input arguments (default 100). Output arguments do not count against that number. After loading the citus extension, the argument count check seems to count both input and output arguments combined against FUNC_MAX_ARGS, preventing the creation of functions you've been able to create without citus.

In the exampe below (on an new/empty PG database) we're able to successfully create a function with 100 input args and 1 output. Then we load the citus extension and repeat the function creation. It fails as long as out combined argument count of input and output args is larger than FUNC_MAX_ARGS. The expected behavior would be the same as without citus extension.

```
-- Check that FUNC_MAX_ARGS is at default (100)
show max_function_args;

-- Create function with 100 input args and 1 output arg
CREATE OR REPLACE FUNCTION args_test_function(
IN in1 integer,  IN in2 integer, IN in3 integer, IN in4 integer, IN in5 integer, IN in6 integer, IN in7 integer, IN in8 integer, IN in9 integer, IN in10 integer, 
IN in11 integer,  IN in12 integer, IN in13 integer, IN in14 integer, IN in15 integer, IN in16 integer, IN in17 integer, IN in18 integer, IN in19 integer, IN in20 integer, 
IN in21 integer,  IN in22 integer, IN in23 integer, IN in24 integer, IN in25 integer, IN in26 integer, IN in27 integer, IN in28 integer, IN in29 integer, IN in30 integer, 
IN in31 integer,  IN in32 integer, IN in33 integer, IN in34 integer, IN in35 integer, IN in36 integer, IN in37 integer, IN in38 integer, IN in39 integer, IN in40 integer, 
IN in41 integer,  IN in42 integer, IN in43 integer, IN in44 integer, IN in45 integer, IN in46 integer, IN in47 integer, IN in48 integer, IN in49 integer, IN in50 integer, 
IN in51 integer,  IN in52 integer, IN in53 integer, IN in54 integer, IN in55 integer, IN in56 integer, IN in57 integer, IN in58 integer, IN in59 integer, IN in60 integer, 
IN in61 integer,  IN in62 integer, IN in63 integer, IN in64 integer, IN in65 integer, IN in66 integer, IN in67 integer, IN in68 integer, IN in69 integer, IN in70 integer, 
IN in71 integer,  IN in72 integer, IN in73 integer, IN in74 integer, IN in75 integer, IN in76 integer, IN in77 integer, IN in78 integer, IN in79 integer, IN in80 integer, 
IN in81 integer,  IN in82 integer, IN in83 integer, IN in84 integer, IN in85 integer, IN in86 integer, IN in87 integer, IN in88 integer, IN in89 integer, IN in90 integer, 
IN in91 integer,  IN in92 integer, IN in93 integer, IN in94 integer, IN in95 integer, IN in96 integer, IN in97 integer, IN in98 integer, IN in99 integer, IN in100 integer,
OUT out1 integer)
    LANGUAGE 'plpgsql'
AS $BODY$ 
begin
   out1 = 1; 
end $BODY$;

-- Drop function for second test
DROP FUNCTION args_test_function;

-- Load citus extension
CREATE EXTENSION citus;

-- Create function with 100 input args and 1 output arg (same as above)
CREATE OR REPLACE FUNCTION args_test_function(
IN in1 integer,  IN in2 integer, IN in3 integer, IN in4 integer, IN in5 integer, IN in6 integer, IN in7 integer, IN in8 integer, IN in9 integer, IN in10 integer, 
IN in11 integer,  IN in12 integer, IN in13 integer, IN in14 integer, IN in15 integer, IN in16 integer, IN in17 integer, IN in18 integer, IN in19 integer, IN in20 integer, 
IN in21 integer,  IN in22 integer, IN in23 integer, IN in24 integer, IN in25 integer, IN in26 integer, IN in27 integer, IN in28 integer, IN in29 integer, IN in30 integer, 
IN in31 integer,  IN in32 integer, IN in33 integer, IN in34 integer, IN in35 integer, IN in36 integer, IN in37 integer, IN in38 integer, IN in39 integer, IN in40 integer, 
IN in41 integer,  IN in42 integer, IN in43 integer, IN in44 integer, IN in45 integer, IN in46 integer, IN in47 integer, IN in48 integer, IN in49 integer, IN in50 integer, 
IN in51 integer,  IN in52 integer, IN in53 integer, IN in54 integer, IN in55 integer, IN in56 integer, IN in57 integer, IN in58 integer, IN in59 integer, IN in60 integer, 
IN in61 integer,  IN in62 integer, IN in63 integer, IN in64 integer, IN in65 integer, IN in66 integer, IN in67 integer, IN in68 integer, IN in69 integer, IN in70 integer, 
IN in71 integer,  IN in72 integer, IN in73 integer, IN in74 integer, IN in75 integer, IN in76 integer, IN in77 integer, IN in78 integer, IN in79 integer, IN in80 integer, 
IN in81 integer,  IN in82 integer, IN in83 integer, IN in84 integer, IN in85 integer, IN in86 integer, IN in87 integer, IN in88 integer, IN in89 integer, IN in90 integer, 
IN in91 integer,  IN in92 integer, IN in93 integer, IN in94 integer, IN in95 integer, IN in96 integer, IN in97 integer, IN in98 integer, IN in99 integer, IN in100 integer,
OUT out1 integer)
    LANGUAGE 'plpgsql'
AS $BODY$ 
begin
   out1 = 1; 
end $BODY$;
```

Result of the last statement:

```
ERROR:  functions cannot have more than 100 arguments
SQL state: 54023
```

**Comment by marcocitus** [comment]
Backtrace:
```
#0  errstart (elevel=elevel@entry=20, domain=domain@entry=0x0) at elog.c:251
#1  0x0000557891b502ec in LookupFuncWithArgs (objtype=objtype@entry=OBJECT_FUNCTION, func=func@entry=0x557893b78330, missing_ok=missing_ok@entry=true)
    at parse_func.c:2189
#2  0x00007f3c6e8ae73a in FunctionToObjectAddress (objectType=objectType@entry=OBJECT_FUNCTION, objectWithArgs=objectWithArgs@entry=0x557893b78330, 
    missing_ok=missing_ok@entry=true) at commands/function.c:1890
#3  0x00007f3c6e8af2aa in CreateFunctionStmtObjectAddress (node=0x557893b78188, missing_ok=<optimized out>) at commands/function.c:1311
#4  0x00007f3c6e8d053c in GetObjectAddressFromParseTree (parseTree=0x557893b78188, missing_ok=missing_ok@entry=true) at deparser/objectaddress.c:36
#5  0x00007f3c6e8ae6b9 in ShouldPropagateCreateFunction (stmt=<optimized out>) at commands/function.c:1177
#6  0x00007f3c6e8af082 in PreprocessCreateFunctionStmt (node=<optimized out>, queryString=<optimized out>, processUtilityContext=<optimized out>)
    at commands/function.c:1240
#7  0x00007f3c6e8c25c9 in ProcessUtilityInternal (pstmt=0x557893b78070, pstmt@entry=0x557893c508c8, 
    queryString=queryString@entry=0x557893ae1450 "CREATE OR REPLACE FUNCTION args_test_function(\nIN in1 integer,  IN in2 integer, IN in3 integer, IN in4 integer, IN in5 integer, IN in6 integer, IN in7 integer, IN in8 integer, IN in9 integer, IN in10 "..., context=context@entry=PROCESS_UTILITY_TOPLEVEL, params=params@entry=0x0, 
    queryEnv=queryEnv@entry=0x0, dest=dest@entry=0x557893c4f808, completionTag=0x7ffc12b59170) at commands/utility_hook.c:457
#8  0x00007f3c6e8c2a7b in multi_ProcessUtility (pstmt=0x557893c508c8, 
    queryString=0x557893ae1450 "CREATE OR REPLACE FUNCTION args_test_function(\nIN in1 integer,  IN in2 integer, IN in3 integer, IN in4 integer, IN in5 integer, IN in6 integer, IN in7 integer, IN in8 integer, IN in9 integer, IN in10 "..., context=PROCESS_UTILITY_TOPLEVEL, params=0x0, queryEnv=0x0, dest=0x557893c4f808, 
    completionTag=0x7ffc12b59170) at commands/utility_hook.c:251
#9  0x00007f3c6e963201 in ColumnarProcessUtility (pstmt=0x557893c508c8, 
    queryString=0x557893ae1450 "CREATE OR REPLACE FUNCTION args_test_function(\nIN in1 integer,  IN in2 integer, IN in3 integer, IN in4 integer, IN in5 integer, IN in6 integer, IN in7 integer, IN in8 integer, IN in9 integer, IN in10 "..., context=PROCESS_UTILITY_TOPLEVEL, params=0x0, queryEnv=0x0, dest=0x557893c4f808, 
    completionTag=0x7ffc12b59170) at ../columnar/columnar_tableam.c:1325
#10 0x00007f3c6d9a99e6 in DatabaseWorkerLauncherProcessUtility (pstmt=0x557893c508c8, 
    queryString=0x557893ae1450 "CREATE OR REPLACE FUNCTION args_test_function(\nIN in1 integer,  IN in2 integer, IN in3 integer, IN in4 integer, IN in5 integer, IN in6 integer, IN in7 integer, IN in8 integer, IN in9 integer, IN in10 "..., context=PROCESS_UTILITY_TOPLEVEL, params=0x0, queryEnv=0x0, dest=0x557893c4f808, 
    completionTag=0x7ffc12b59170) at src/database_worker_launcher.c:760
#11 0x00007f3c6d982443 in CStoreProcessUtility (plannedStatement=0x557893c508c8, 
    queryString=0x557893ae1450 "CREATE OR REPLACE FUNCTION args_test_function(\nIN in1 integer,  IN in2 integer, IN in3 integer, IN in4 integer, IN in5 integer, IN in6 integer, IN in7 integer, IN in8 integer, IN in9 integer, IN in10 "..., context=PROCESS_UTILITY_TOPLEVEL, paramListInfo=0x0, queryEnvironment=0x0, 
    destReceiver=0x557893c4f808, queryCompletion=0x7ffc12b59170) at cstore_fdw.c:426
#12 0x0000557891db96e9 in ProcessUtility (pstmt=pstmt@entry=0x557893c508c8, queryString=<optimized out>, context=<optimized out>, params=<optimized out>, 
    queryEnv=<optimized out>, dest=dest@entry=0x557893c4f808, qc=0x7ffc12b59170) at utility.c:520
#13 0x0000557891db5a86 in PortalRunUtility (portal=portal@entry=0x557893bbccc0, pstmt=pstmt@entry=0x557893c508c8, isTopLevel=isTopLevel@entry=true, 
    setHoldSnapshot=setHoldSnapshot@entry=false, dest=dest@entry=0x557893c4f808, qc=qc@entry=0x7ffc12b59170) at pquery.c:1157
#14 0x0000557891db65fd in PortalRunMulti (portal=portal@entry=0x557893bbccc0, isTopLevel=isTopLevel@entry=true, setHoldSnapshot=setHoldSnapshot@entry=false, 
    dest=dest@entry=0x557893c4f808, altdest=altdest@entry=0x557893c4f808, qc=qc@entry=0x7ffc12b59170) at pquery.c:1303
#15 0x0000557891db7363 in PortalRun (portal=portal@entry=0x557893bbccc0, count=count@entry=9223372036854775807, isTopLevel=isTopLevel@entry=true, 
    run_once=run_once@entry=true, dest=dest@entry=0x557893c4f808, altdest=altdest@entry=0x557893c4f808, qc=0x7ffc12b59170) at pquery.c:779
#16 0x0000557891db35e8 in exec_simple_query (
    query_string=query_string@entry=0x557893ae1450 "CREATE OR REPLACE FUNCTION args_test_function(\nIN in1 integer,  IN in2 integer, IN in3 integer, IN in4 integer, IN in5 integer, IN in6 integer, IN in7 integer, IN in8 integer, IN in9 integer, IN in10 "...) at postgres.c:1239
#17 0x0000557891db55f4 in PostgresMain (argc=<optimized out>, argv=argv@entry=0x557893b80798, dbname=<optimized out>, username=<optimized out>) at postgres.c:4329
#18 0x0000557891d1ec13 in BackendRun (port=port@entry=0x557893b7e350) at postmaster.c:4526
#19 0x0000557891d21e7e in BackendStartup (port=port@entry=0x557893b7e350) at postmaster.c:4210
#20 0x0000557891d220c7 in ServerLoop () at postmaster.c:1739
#21 0x0000557891d23606 in PostmasterMain (argc=<optimized out>, argv=<optimized out>) at postmaster.c:1412
#22 0x0000557891c687bf in main (argc=3, argv=0x557893ad9c20) at main.c:210
```
Interestingly, the error does come from PostgreSQL code, so it looks like it might be a PG bug.
