### ISSUE TITLE
get_rebalance_progress() crashed while rebalance is running

### ISSUE THREAD

**Issue by onderkalaci** [citusdata/citus#5044]
I don't have a core-dump.

Create & load table:
```SQL
CREATE TABLE events(ts timestamptz, i int, n numeric, s text)
  PARTITION BY RANGE (ts);

CREATE TABLE events_2021_jan PARTITION OF events
  FOR VALUES FROM ('2021-01-01') TO ('2021-02-01');

CREATE TABLE events_2021_feb PARTITION OF events
  FOR VALUES FROM ('2021-02-01') TO ('2021-03-01');
SELECT create_distributed_table('events', 'i');
INSERT INTO events SELECT
    '2021-01-01'::timestamptz + '0.45 seconds'::interval * g,
    g,
    g*pi(),
    'number: ' || g::text
    FROM generate_series(1,10000000) g;

VACUUM (FREEZE, ANALYZE) events_2021_feb;

```
Run rebalance -- the parameters are probably not relevant:
```SQL
select rebalance_table_shards(rebalance_strategy:='by_disk_size', shard_transfer_mode:='force_logical');
```

And, on another session:
```SQL

SELECT
              sessionid, table_name::text,
              shardid, shard_size,
              sourcename, targetname,
              progress
            FROM get_rebalance_progress();
\watch 0.01
```

```SQL
2021-06-15 13:15:41.081 +03 [28030] LOG: could not receive data from client: Connection reset by peer
2021-06-15 13:15:41.082 +03 [18083] LOG: server process (PID 26959) was terminated by signal 11: Segmentation fault: 11
2021-06-15 13:15:41.082 +03 [18083] DETAIL: Failed process was running: SELECT
sessionid, table_name::text,
shardid, shard_size,
sourcename, targetname,
progress
FROM get_rebalance_progress();2021-06-15 13:15:41.081 +03 [28030] LOG: could not receive data from client: Connection reset by peer
2021-06-15 13:15:41.082 +03 [18083] LOG: server process (PID 26959) was terminated by signal 11: Segmentation fault: 11
2021-06-15 13:15:41.082 +03 [18083] DETAIL: Failed process was running: SELECT
sessionid, table_name::text,
shardid, shard_size,
sourcename, targetname,
progress
FROM get_rebalance_progress();
```

**Comment by JelteF** [comment]
backtrace:
```
#0  BuildShardSizesHash (monitor=0x7f03ee5e6000, monitor=0x7f03ee5e6000, shardStatistics=0x108b7c8) at operations/shard_rebalancer.c:1159
#1  get_rebalance_progress (fcinfo=<optimized out>) at operations/shard_rebalancer.c:1087
#2  0x0000000000636b07 in ExecMakeTableFunctionResult (setexpr=0x1031b88, econtext=0x1031aa8, argContext=<optimized out>, expectedDesc=0x1032820, randomAccess=false) at execSRF.c:234
#3  0x000000000064744c in FunctionNext (node=node@entry=0x1031998) at nodeFunctionscan.c:94
#4  0x000000000063758a in ExecScanFetch (recheckMtd=0x647170 <FunctionRecheck>, accessMtd=0x647190 <FunctionNext>, node=0x1031998) at execScan.c:133
#5  ExecScan (node=0x1031998, accessMtd=0x647190 <FunctionNext>, recheckMtd=0x647170 <FunctionRecheck>) at execScan.c:199
#6  0x000000000063e7d9 in ExecProcNode (node=0x1031998) at ../../../src/include/executor/executor.h:248
#7  fetch_input_tuple (aggstate=aggstate@entry=0x1031370) at nodeAgg.c:589
#8  0x0000000000641602 in agg_retrieve_direct (aggstate=0x1031370) at nodeAgg.c:2368
#9  ExecAgg (pstate=0x1031370) at nodeAgg.c:2183
#10 0x000000000062db82 in ExecProcNode (node=0x1031370) at ../../../src/include/executor/executor.h:248
#11 ExecutePlan (execute_once=<optimized out>, dest=0x1047230, direction=8, numberTuples=0, sendTuples=true, operation=CMD_SELECT, use_parallel_mode=<optimized out>, planstate=0x1031370, estate=0x1031148) at execMain.c:1632
#12 standard_ExecutorRun (queryDesc=queryDesc@entry=0x10229f8, direction=direction@entry=ForwardScanDirection, count=count@entry=0, execute_once=execute_once@entry=true) at execMain.c:350
#13 0x00007f03f071794a in CitusExecutorRun (queryDesc=0x10229f8, direction=ForwardScanDirection, count=0, execute_once=<optimized out>) at executor/multi_executor.c:214
#14 0x00007f03eefe7321 in pgss_ExecutorRun (queryDesc=0x10229f8, direction=ForwardScanDirection, count=0, execute_once=<optimized out>) at pg_stat_statements.c:1043
#15 0x00000000007922cb in PortalRunSelect (portal=portal@entry=0xfcf1b8, forward=forward@entry=true, count=0, count@entry=9223372036854775807, dest=dest@entry=0x1047230) at pquery.c:912
#16 0x00000000007935c7 in PortalRun (portal=<optimized out>, count=9223372036854775807, isTopLevel=<optimized out>, run_once=<optimized out>, dest=0x1047230, altdest=0x1047230, qc=0x7ffdf20f0620) at pquery.c:756
#17 0x000000000078f277 in exec_simple_query (query_string=<optimized out>) at postgres.c:1239
#18 0x00000000007905e7 in PostgresMain (argc=<optimized out>, argv=<optimized out>, dbname=<optimized out>, username=<optimized out>) at postgres.c:4329
#19 0x0000000000487dbf in BackendRun (port=<optimized out>, port=<optimized out>) at postmaster.c:4526
#20 BackendStartup (port=0xf30250) at postmaster.c:4210
#21 ServerLoop () at postmaster.c:1739
#22 0x0000000000719db8 in PostmasterMain (argc=argc@entry=3, argv=argv@entry=0xebc2d0) at postmaster.c:1412
#23 0x0000000000488cfd in main (argc=3, argv=0xebc2d0) at main.c:210
```
