### ISSUE TITLE
Assertion failure in GetClauseVars

### ISSUE THREAD

**Issue by onurctirtir** [citusdata/citus#5257]
Doesn't reproduce on v10.1.0.

Sharing steps to repro & backtrace:

```sql
set default_table_access_method to columnar;
CREATE TABLE prt1 (a int, b int, c varchar) PARTITION BY RANGE(a);
CREATE TABLE prt1_p1 PARTITION OF prt1 FOR VALUES FROM (0) TO (250);
CREATE TABLE prt1_p3 PARTITION OF prt1 FOR VALUES FROM (500) TO (600);
CREATE TABLE prt1_p2 PARTITION OF prt1 FOR VALUES FROM (250) TO (500);
INSERT INTO prt1 SELECT i, i % 25, to_char(i, 'FM0000') FROM generate_series(0, 599) i WHERE i % 2 = 0;

CREATE TABLE prt2 (a int, b int, c varchar) PARTITION BY RANGE(b);
CREATE TABLE prt2_p1 PARTITION OF prt2 FOR VALUES FROM (0) TO (250);
CREATE TABLE prt2_p2 PARTITION OF prt2 FOR VALUES FROM (250) TO (500);
CREATE TABLE prt2_p3 PARTITION OF prt2 FOR VALUES FROM (500) TO (600);
INSERT INTO prt2 SELECT i % 25, i, to_char(i, 'FM0000') FROM generate_series(0, 599) i WHERE i % 3 = 0;

SET enable_partitionwise_join to true;
SELECT * FROM prt1 t1 LEFT JOIN LATERAL
			  (SELECT t2.a AS t2a, t3.a AS t3a, least(t1.a,t2.a,t3.b) FROM prt1 t2 JOIN prt2 t3 ON (t2.a = t3.b)) ss
			  ON t1.a = ss.t2a WHERE t1.b = 0 ORDER BY t1.a;
```

```c
#0  0x00007ff608b55428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007ff608b5702a in __GI_abort () at abort.c:89
#2  0x0000000000b60d31 in ExceptionalCondition (conditionName=0x7ff606452a28 "equal(var, deduplicate[idx])", errorType=0x7ff6064527c6 "FailedAssertion",
    fileName=0x7ff606452834 "../columnar/columnar_reader.c", lineNumber=1247) at assert.c:69
#3  0x00007ff606404f66 in GetClauseVars (whereClauseList=0x2be12a0, natts=3) at ../columnar/columnar_reader.c:1247
#4  0x00007ff606403567 in ColumnarBeginRead (relation=0x7ff5f6a454a0, tupleDescriptor=0x7ff5f6a41550, projectedColumnList=0x2be1458,
    whereClauseList=0x2be12a0, scanContext=0x2be10c0, snapshot=0x2acf168, flushWrites=true) at ../columnar/columnar_reader.c:195
#5  0x00007ff6064079ba in init_columnar_read_state (relation=0x7ff5f6a454a0, tupdesc=0x7ff5f6a41550, attr_needed=0x2be1278, scanQual=0x2be12a0,
    scanContext=0x2be10c0, snapshot=0x2acf168, flushWrites=true) at ../columnar/columnar_tableam.c:263
#6  0x00007ff606407b0c in columnar_getnextslot (sscan=0x2be11e0, direction=ForwardScanDirection, slot=0x2bb3708) at ../columnar/columnar_tableam.c:318
#7  0x00007ff6063fd148 in table_scan_getnextslot (sscan=0x2be11e0, direction=ForwardScanDirection, slot=0x2bb3708)
    at /home/onurctirtir/.pgenv/pgsql-14beta3/include/server/access/tableam.h:1044
#8  0x00007ff6063ff4f4 in ColumnarScanNext (columnarScanState=0x2bb3458) at ../columnar/columnar_customscan.c:1477
#9  0x000000000076849e in ExecScanFetch (node=0x2bb3458, accessMtd=0x7ff6063ff416 <ColumnarScanNext>, recheckMtd=0x7ff6063ff505 <ColumnarScanRecheck>)
    at execScan.c:133
#10 0x000000000076853f in ExecScan (node=0x2bb3458, accessMtd=0x7ff6063ff416 <ColumnarScanNext>, recheckMtd=0x7ff6063ff505 <ColumnarScanRecheck>)
    at execScan.c:199
#11 0x00007ff6063ff53e in ColumnarScan_ExecCustomScan (node=0x2bb3458) at ../columnar/columnar_customscan.c:1498
#12 0x00000000007820bf in ExecCustomScan (pstate=0x2bb3458) at nodeCustom.c:115
#13 0x000000000076454e in ExecProcNodeFirst (node=0x2bb3458) at execProcnode.c:463
#14 0x000000000078d44c in ExecProcNode (node=0x2bb3458) at ../../../src/include/executor/executor.h:257
#15 0x000000000078d784 in ExecHashJoinImpl (pstate=0x2bb31a8, parallel=false) at nodeHashjoin.c:262
#16 0x000000000078df94 in ExecHashJoin (pstate=0x2bb31a8) at nodeHashjoin.c:591
#17 0x000000000076454e in ExecProcNodeFirst (node=0x2bb31a8) at execProcnode.c:463
#18 0x00000000007a459f in ExecProcNode (node=0x2bb31a8) at ../../../src/include/executor/executor.h:257
#19 0x00000000007a49e0 in ExecNestLoop (pstate=0x2b43850) at nodeNestloop.c:160
#20 0x000000000076454e in ExecProcNodeFirst (node=0x2b43850) at execProcnode.c:463
#21 0x000000000077cd13 in ExecProcNode (node=0x2b43850) at ../../../src/include/executor/executor.h:257
#22 0x000000000077d4f2 in ExecAppend (pstate=0x2b430d0) at nodeAppend.c:360
#23 0x000000000076454e in ExecProcNodeFirst (node=0x2b430d0) at execProcnode.c:463
#24 0x00000000007a897e in ExecProcNode (node=0x2b430d0) at ../../../src/include/executor/executor.h:257
#25 0x00000000007a8acd in ExecSort (pstate=0x2b42eb8) at nodeSort.c:108
#26 0x000000000076454e in ExecProcNodeFirst (node=0x2b42eb8) at execProcnode.c:463
#27 0x00000000007589ab in ExecProcNode (node=0x2b42eb8) at ../../../src/include/executor/executor.h:257
#28 0x000000000075b22b in ExecutePlan (estate=0x2b42b70, planstate=0x2b42eb8, use_parallel_mode=false, operation=CMD_SELECT, sendTuples=true,
    numberTuples=0, direction=ForwardScanDirection, dest=0x2c7bc78, execute_once=true) at execMain.c:1551
#29 0x0000000000759039 in standard_ExecutorRun (queryDesc=0x2b4a500, direction=ForwardScanDirection, count=0, execute_once=true) at execMain.c:361
#30 0x00007ff606357208 in CitusExecutorRun (queryDesc=0x2b4a500, direction=ForwardScanDirection, count=0, execute_once=true)
    at executor/multi_executor.c:214
#31 0x00007ff600b021ac in pgss_ExecutorRun (queryDesc=0x2b4a500, direction=ForwardScanDirection, count=0, execute_once=true) at pg_stat_statements.c:1001
#32 0x0000000000758e4e in ExecutorRun (queryDesc=0x2b4a500, direction=ForwardScanDirection, count=0, execute_once=true) at execMain.c:303
#33 0x00000000009b73cc in PortalRunSelect (portal=0x2aa7510, forward=true, count=0, dest=0x2c7bc78) at pquery.c:919
#34 0x00000000009b7017 in PortalRun (portal=0x2aa7510, count=9223372036854775807, isTopLevel=true, run_once=true, dest=0x2c7bc78, altdest=0x2c7bc78,
    qc=0x7ffe8d3ff960) at pquery.c:763
#35 0x00000000009b07e1 in exec_simple_query (
    query_string=0x29bf510 "SELECT * FROM prt1 t1 LEFT JOIN LATERAL\n\t\t\t  (SELECT t2.a AS t2a, t3.a AS t3a, least(t1.a,t2.a,t3.b) FROM prt1 t2 JOIN prt2 t3 ON (t2.a = t3.b)) ss\n\t\t\t  ON t1.a = ss.t2a WHERE t1.b = 0 ORDER BY t1.a;") at postgres.c:1214
#36 0x00000000009b4fed in PostgresMain (argc=1, argv=0x7ffe8d3ffb80, dbname=0x2a5ca58 "regression", username=0x2a5a9e0 "postgres") at postgres.c:4486
#37 0x00000000008e8a84 in BackendRun (port=0x2a56fe0) at postmaster.c:4506
#38 0x00000000008e8393 in BackendStartup (port=0x2a56fe0) at postmaster.c:4228
#39 0x00000000008e46c7 in ServerLoop () at postmaster.c:1745
#40 0x00000000008e3ef6 in PostmasterMain (argc=5, argv=0x29b9ea0) at postmaster.c:1417
#41 0x00000000007ddf20 in main (argc=5, argv=0x29b9ea0) at main.c:209
```

**Comment by onurctirtir** [comment]
Added 10.2 release milestone, please remove if you think otherwise
