### ISSUE TITLE
Multiple tests SIGSEGV'd when using range / multi range types

### ISSUE THREAD

**Issue by onurctirtir** [citusdata/citus#5258]
Doesn't reproduce on v10.1.0.

Sharing steps to repro & backtrace for only one of 5 coredumps:
```sql
set default_table_access_method to columnar;
CREATE TABLE atest1 ( a int, b text );
CREATE TABLE atest2 (col1 varchar(10), col2 boolean);

INSERT INTO atest1 VALUES (1, 'one');
SELECT * FROM atest1; -- ok
SELECT * FROM atest2; -- ok
INSERT INTO atest1 VALUES (2, 'two'); -- ok
INSERT INTO atest1 SELECT 1, b FROM atest1; -- ok

-- crahes
SELECT * FROM atest2 WHERE ( col1 IN ( SELECT b FROM atest1 ) );
```

```c
#0  0x0000000000b6d074 in pg_detoast_datum (datum=0x0) at fmgr.c:1724
#1  0x000000000080162c in makeConst (consttype=1043, consttypmod=14, constcollid=100, constlen=-1, constvalue=0, constisnull=false, constbyval=false)
    at makefuncs.c:315
#2  0x00007ff6063ff107 in EvalParamsMutator (node=0x2b75a78, econtext=0x2b9a3a8) at ../columnar/columnar_customscan.c:1358
#3  0x0000000000807698 in expression_tree_mutator (node=0x2b75a20, mutator=0x7ff6063ff036 <EvalParamsMutator>, context=0x2b9a3a8) at nodeFuncs.c:2877
#4  0x00007ff6063ff124 in EvalParamsMutator (node=0x2b75a20, econtext=0x2b9a3a8) at ../columnar/columnar_customscan.c:1367
#5  0x00000000008082b9 in expression_tree_mutator (node=0x2b75ab0, mutator=0x7ff6063ff036 <EvalParamsMutator>, context=0x2b9a3a8) at nodeFuncs.c:3109
#6  0x00007ff6063ff124 in EvalParamsMutator (node=0x2b75ab0, econtext=0x2b9a3a8) at ../columnar/columnar_customscan.c:1367
#7  0x00000000008070fb in expression_tree_mutator (node=0x2b759c8, mutator=0x7ff6063ff036 <EvalParamsMutator>, context=0x2b9a3a8) at nodeFuncs.c:2765
#8  0x00007ff6063ff124 in EvalParamsMutator (node=0x2b759c8, econtext=0x2b9a3a8) at ../columnar/columnar_customscan.c:1367
#9  0x00000000008082b9 in expression_tree_mutator (node=0x2b75b08, mutator=0x7ff6063ff036 <EvalParamsMutator>, context=0x2b9a3a8) at nodeFuncs.c:3109
#10 0x00007ff6063ff124 in EvalParamsMutator (node=0x2b75b08, econtext=0x2b9a3a8) at ../columnar/columnar_customscan.c:1367
#11 0x00007ff6063ff1e0 in ColumnarScan_BeginCustomScan (cscanstate=0x2b520f8, estate=0x2b51680, eflags=16) at ../columnar/columnar_customscan.c:1388
#12 0x000000000078203b in ExecInitCustomScan (cscan=0x2b752d0, estate=0x2b51680, eflags=16) at nodeCustom.c:102
#13 0x0000000000764153 in ExecInitNode (node=0x2b752d0, estate=0x2b51680, eflags=16) at execProcnode.c:289
#14 0x00000000007a4cee in ExecInitNestLoop (node=0x2b75b60, estate=0x2b51680, eflags=16) at nodeNestloop.c:302
#15 0x0000000000764172 in ExecInitNode (node=0x2b75b60, estate=0x2b51680, eflags=16) at execProcnode.c:297
#16 0x0000000000759e35 in InitPlan (queryDesc=0x2b683e0, eflags=16) at execMain.c:936
#17 0x0000000000758e03 in standard_ExecutorStart (queryDesc=0x2b683e0, eflags=16) at execMain.c:263
#18 0x00007ff606356f64 in CitusExecutorStart (queryDesc=0x2b683e0, eflags=0) at executor/multi_executor.c:123
#19 0x00007ff600b0203a in pgss_ExecutorStart (queryDesc=0x2b683e0, eflags=0) at pg_stat_statements.c:963
#20 0x0000000000758b4b in ExecutorStart (queryDesc=0x2b683e0, eflags=0) at execMain.c:141
#21 0x00000000009b69af in PortalStart (portal=0x2a9e2e0, params=0x0, eflags=0, snapshot=0x0) at pquery.c:512
#22 0x00000000009b06e9 in exec_simple_query (query_string=0x29bf510 "SELECT * FROM atest2 WHERE ( col1 IN ( SELECT b FROM atest1 ) );") at postgres.c:1175
#23 0x00000000009b4fed in PostgresMain (argc=1, argv=0x7ffe8d3ffb80, dbname=0x2a5cb98 "regression", username=0x2a5cb70 "postgres") at postgres.c:4486
#24 0x00000000008e8a84 in BackendRun (port=0x2a56fe0) at postmaster.c:4506
#25 0x00000000008e8393 in BackendStartup (port=0x2a56fe0) at postmaster.c:4228
#26 0x00000000008e46c7 in ServerLoop () at postmaster.c:1745
#27 0x00000000008e3ef6 in PostmasterMain (argc=5, argv=0x29b9ea0) at postmaster.c:1417
#28 0x00000000007ddf20 in main (argc=5, argv=0x29b9ea0) at main.c:209
```

-----

Other four queries crashed with a very similar backtrace are:
```sql
select * from\n  (select distinct f1, f2, (select f2 from t1 x where x.f1 = up.f1) as fs\n   from t1 up) ss\ngroup by f1,f2,fs;
```
```sql
select * from nummultirange_test natural join nummultirange_test2 order by nmr;
```
```sql
SELECT * FROM\n(SELECT name, n as s1_n, 1 as s1_1 FROM t1) as s1\nNATURAL INNER JOIN\n(SELECT name, n as s2_n, 2 as s2_2 FROM t2) as s2\nNATURAL INNER JOIN\n(SELECT name, n as s3_n, 3 as s3_2 FROM t3) s3;
```
```sql
select * from numrange_test natural join numrange_test2 order by nr;
```

**Comment by onurctirtir** [comment]
Added 10.2 release milestone since we are close to fixing that

**Comment by halilozanakgul** [comment]
SQLancer also hit this bug. These queries crash:
```SQL
CREATE TABLE tbl1(c0 int4range) USING COLUMNAR;
CREATE TABLE tbl2(c0 int4range);

INSERT INTO tbl1(c0) VALUES('[0,1]'::int4range);
INSERT INTO tbl1(c0) VALUES('[0,1]'::int4range);

SELECT tbl1.c0 FROM tbl1 JOIN tbl2 ON tbl1.c0=tbl2.c0 WHERE tbl2.c0<=tbl2.c0 ISNULL;
```
