### ISSUE TITLE
Where Clauses with Money Columns Crash On Distributed Selects

### ISSUE THREAD

**Issue by halilozanakgul** [citusdata/citus#5813]
This query crashes on single node:

```
CREATE TABLE tbl1(a REAL, b FLOAT, c money);
CREATE TABLE tbl2(a REAL, b FLOAT, c money);

SELECT create_distributed_table('tbl1', 'a');
SELECT create_distributed_table('tbl2', 'b');

INSERT INTO tbl1 VALUES(1, 1, 1);

SET citus.enable_repartition_joins to ON;

SELECT * FROM tbl1, tbl2 WHERE tbl2.c=tbl1.c;
```

The query also fails in multi-node clusters but on workers, so it is more apparent in single node.

**Comment by halilozanakgul** [comment]
This is very similar to #4281 but this time you have to insert some values before running `SELECT` and now it crashes

**Comment by marcocitus** [comment]
Stack trace:
```
#0  0x0000000000000000 in ?? ()
#1  0x000056264250730b in FunctionCall1Coll (flinfo=0x562643d7b130, collation=<optimized out>, arg1=arg1@entry=100) at fmgr.c:1142
#2  0x00007fad12d496d2 in FindShardInterval (partitionColumnValue=100, cacheEntry=0x562643d7c3c8) at utils/shardinterval_utils.c:266
#3  0x00007fad12cd7ae2 in PartitionedResultDestReceiverReceive (slot=0x562643d72f80, dest=0x562643d92e68) at executor/partitioned_intermediate_results.c:499
#4  0x0000562642220863 in ExecutePlan (estate=estate@entry=0x562643d72b40, planstate=0x562643d72d78, use_parallel_mode=<optimized out>, operation=operation@entry=CMD_SELECT, 
    sendTuples=sendTuples@entry=true, numberTuples=numberTuples@entry=0, direction=ForwardScanDirection, dest=0x562643d92e68, execute_once=true) at execMain.c:1677
#5  0x0000562642221534 in standard_ExecutorRun (queryDesc=queryDesc@entry=0x562643d22690, direction=direction@entry=ForwardScanDirection, count=count@entry=0, 
    execute_once=execute_once@entry=true) at execMain.c:364
#6  0x00007fad12cd67b6 in CitusExecutorRun (queryDesc=0x562643d22690, direction=ForwardScanDirection, count=0, execute_once=<optimized out>) at executor/multi_executor.c:220
#7  0x00005626422215f7 in ExecutorRun (queryDesc=queryDesc@entry=0x562643d22690, direction=direction@entry=ForwardScanDirection, count=count@entry=0, 
    execute_once=<optimized out>) at execMain.c:306
#8  0x00005626423cbd0c in PortalRunSelect (portal=portal@entry=0x562643cd28f8, forward=forward@entry=true, count=0, count@entry=9223372036854775807, 
    dest=dest@entry=0x562643d92e68) at pquery.c:912
#9  0x00005626423cd4e2 in PortalRun (portal=portal@entry=0x562643cd28f8, count=count@entry=9223372036854775807, isTopLevel=isTopLevel@entry=false, run_once=run_once@entry=true, 
    dest=dest@entry=0x562643d92e68, altdest=altdest@entry=0x562643d92e68, qc=0x0) at pquery.c:756
#10 0x00007fad12cd7fe6 in worker_partition_query_result (fcinfo=0x562643d5dca0) at executor/partitioned_intermediate_results.c:252
#11 0x000056264222b126 in ExecMakeTableFunctionResult (setexpr=0x562643cfdd68, econtext=0x562643cfdc20, argContext=<optimized out>, expectedDesc=0x562643d653a8, 
    randomAccess=false) at execSRF.c:234
#12 0x000056264223e28f in FunctionNext (node=node@entry=0x562643cfdb08) at nodeFunctionscan.c:94
#13 0x000056264222bcde in ExecScanFetch (recheckMtd=0x56264223e16b <FunctionRecheck>, accessMtd=0x56264223e1bb <FunctionNext>, node=0x562643cfdb08) at execScan.c:133
#14 ExecScan (node=0x562643cfdb08, accessMtd=accessMtd@entry=0x56264223e1bb <FunctionNext>, recheckMtd=recheckMtd@entry=0x56264223e16b <FunctionRecheck>) at execScan.c:199
#15 0x000056264223e19a in ExecFunctionScan (pstate=<optimized out>) at nodeFunctionscan.c:270
#16 0x0000562642228a64 in ExecProcNodeFirst (node=0x562643cfdb08) at execProcnode.c:450
#17 0x0000562642220832 in ExecProcNode (node=0x562643cfdb08) at ../../../src/include/executor/executor.h:248
#18 ExecutePlan (estate=estate@entry=0x562643cfd8d0, planstate=0x562643cfdb08, use_parallel_mode=<optimized out>, operation=operation@entry=CMD_SELECT, 
    sendTuples=sendTuples@entry=true, numberTuples=numberTuples@entry=0, direction=ForwardScanDirection, dest=0x562643d5b860, execute_once=true) at execMain.c:1646
#19 0x0000562642221534 in standard_ExecutorRun (queryDesc=queryDesc@entry=0x562643d18380, direction=direction@entry=ForwardScanDirection, count=count@entry=0, 
    execute_once=execute_once@entry=true) at execMain.c:364
#20 0x00007fad12cd67b6 in CitusExecutorRun (queryDesc=0x562643d18380, direction=ForwardScanDirection, count=0, execute_once=<optimized out>) at executor/multi_executor.c:220
#21 0x00005626422215f7 in ExecutorRun (queryDesc=queryDesc@entry=0x562643d18380, direction=direction@entry=ForwardScanDirection, count=count@entry=0, 
    execute_once=<optimized out>) at execMain.c:306
#22 0x00005626423cbd0c in PortalRunSelect (portal=portal@entry=0x562643cd27e0, forward=forward@entry=true, count=0, count@entry=9223372036854775807, 
    dest=dest@entry=0x562643d5b860) at pquery.c:912
#23 0x00005626423cd4e2 in PortalRun (portal=portal@entry=0x562643cd27e0, count=count@entry=9223372036854775807, isTopLevel=isTopLevel@entry=true, run_once=run_once@entry=true, 
    dest=dest@entry=0x562643d5b860, altdest=altdest@entry=0x562643d5b860, qc=0x7ffd3b2cd8e0) at pquery.c:756
#24 0x00005626423c95e8 in exec_simple_query (
    query_string=query_string@entry=0x562643bf5c80 "SELECT partition_index, 'repartition_339184975873_24' || '_' || partition_index::text , rows_written FROM pg_catalog.worker_partition_query_result('repartition_339184975873_24','SELECT a AS column1, b"...) at postgres.c:1239
#25 0x00005626423cb5f4 in PostgresMain (argc=<optimized out>, argv=argv@entry=0x562643c961a0, dbname=<optimized out>, username=<optimized out>) at postgres.c:4329
#26 0x0000562642334c13 in BackendRun (port=port@entry=0x562643c8f510) at postmaster.c:4526
#27 0x0000562642337e7e in BackendStartup (port=port@entry=0x562643c8f510) at postmaster.c:4210
#28 0x00005626423380c7 in ServerLoop () at postmaster.c:1739
#29 0x0000562642339606 in PostmasterMain (argc=<optimized out>, argv=<optimized out>) at postmaster.c:1412
#30 0x000056264227e7bf in main (argc=3, argv=0x562643beec80) at main.c:210
```
