### ISSUE TITLE
Extension upgrade from v5.1 busted

### ISSUE THREAD

**Issue by anarazel** [citusdata/citus#600]
Upgrading from v5.1 to master currently is busted
```
postgres[1049][1]=# ALTER EXTENSION citus UPDATE ;
ERROR:  42883: function master_update_shard_statistics(bigint) does not exist
LOCATION:  LookupFuncName, parse_func.c:1922
```
the backtrace is
```
#0  LookupFuncName (funcname=0x2329c98, nargs=1, argtypes=0x7ffc319c35b0, noError=0 '\000')
    at /home/andres/src/postgresql-9.5/src/backend/parser/parse_func.c:1917
#1  0x00000000005be300 in LookupFuncNameTypeNames (funcname=0x2329c98, argtypes=0x2329f10, noError=0 '\000')
    at /home/andres/src/postgresql-9.5/src/backend/parser/parse_func.c:1958
#2  0x000000000055a39e in get_object_address (objtype=OBJECT_FUNCTION, objname=0x2329c98, objargs=0x2329f10, 
    relp=0x7ffc319c3888, lockmode=8, missing_ok=0 '\000')
    at /home/andres/src/postgresql-9.5/src/backend/catalog/objectaddress.c:812
#3  0x00000000005f38e2 in RemoveObjects (stmt=0x2329e30)
    at /home/andres/src/postgresql-9.5/src/backend/commands/dropcmds.c:77
#4  0x00000000007ec2e1 in ExecDropStmt (stmt=0x2329e30, isTopLevel=0 '\000')
    at /home/andres/src/postgresql-9.5/src/backend/tcop/utility.c:1572
#5  0x00000000007ec038 in ProcessUtilitySlow (parsetree=0x2329e30, 
    queryString=0x2329818 "DROP FUNCTION master_update_shard_statistics(shard_id bigint);\n\nCREATE FUNCTION pg_catalog.master_update_shard_statistics(shard_id bigint)\n    RETURNS bigint\n    LANGUAGE C STRICT\n    AS '$libdir/citu"..., context=PROCESS_UTILITY_QUERY, params=0x0, dest=0xe02060 <donothingDR>, completionTag=0x0)
    at /home/andres/src/postgresql-9.5/src/backend/tcop/utility.c:1465
#6  0x00000000007eac58 in standard_ProcessUtility (parsetree=0x2329e30, 
    queryString=0x2329818 "DROP FUNCTION master_update_shard_statistics(shard_id bigint);\n\nCREATE FUNCTION pg_catalog.master_update_shard_statistics(shard_id bigint)\n    RETURNS bigint\n    LANGUAGE C STRICT\n    AS '$libdir/citu"..., context=PROCESS_UTILITY_QUERY, params=0x0, dest=0xe02060 <donothingDR>, completionTag=0x0)
---Type <return> to continue, or q <return> to quit---
    at /home/andres/src/postgresql-9.5/src/backend/tcop/utility.c:817
#7  0x00007f9bd5aa9d91 in multi_ProcessUtility (parsetree=0x2329e30, 
    queryString=0x2329818 "DROP FUNCTION master_update_shard_statistics(shard_id bigint);\n\nCREATE FUNCTION pg_catalog.master_update_shard_statistics(shard_id bigint)\n    RETURNS bigint\n    LANGUAGE C STRICT\n    AS '$libdir/citu"..., context=PROCESS_UTILITY_QUERY, params=0x0, dest=0xe02060 <donothingDR>, completionTag=0x0)
    at /home/andres/src/citusdb/src/backend/distributed/executor/multi_utility.c:228
#8  0x00000000007ea067 in ProcessUtility (parsetree=0x2329e30, 
    queryString=0x2329818 "DROP FUNCTION master_update_shard_statistics(shard_id bigint);\n\nCREATE FUNCTION pg_catalog.master_update_shard_statistics(shard_id bigint)\n    RETURNS bigint\n    LANGUAGE C STRICT\n    AS '$libdir/citu"..., context=PROCESS_UTILITY_QUERY, params=0x0, dest=0xe02060 <donothingDR>, completionTag=0x0)
    at /home/andres/src/postgresql-9.5/src/backend/tcop/utility.c:330
#9  0x0000000000600edb in execute_sql_string (
    sql=0x2329818 "DROP FUNCTION master_update_shard_statistics(shard_id bigint);\n\nCREATE FUNCTION pg_catalog.master_update_shard_statistics(shard_id bigint)\n    RETURNS bigint\n    LANGUAGE C STRICT\n    AS '$libdir/citu"..., 
    filename=0x2318460 "/home/andres/build/postgres/9.5-assert/install/share/extension/citus--5.1-2--5.1-3.sql")
    at /home/andres/src/postgresql-9.5/src/backend/commands/extension.c:744
#10 0x0000000000601367 in execute_extension_script (extensionOid=16384, control=0x2318218, 
    from_version=0x2309228 "5.1-2", version=0x231b840 "5.1-3", requiredSchemas=0x0, 
    schemaName=0x2318388 "pg_catalog", schemaOid=11)
    at /home/andres/src/postgresql-9.5/src/backend/commands/extension.c:904
---Type <return> to continue, or q <return> to quit---
#11 0x0000000000605dec in ApplyExtensionUpdates (extensionOid=16384, pcontrol=0x22eb408, 
    initialVersion=0x22eb6a8 "5.1-1", updateVersions=0x231bac8)
    at /home/andres/src/postgresql-9.5/src/backend/commands/extension.c:2875
#12 0x000000000060593a in ExecAlterExtensionStmt (stmt=0x22da970)
    at /home/andres/src/postgresql-9.5/src/backend/commands/extension.c:2722
```

**Comment by metdos** [comment]
@anarazel, I created this PR #604 to fix this. Could you review it?
