### ISSUE TITLE
Split fails/hangs with dropped column + jsonb

### ISSUE THREAD

**Issue by marcocitus** [citusdata/citus#6303]
While trying the following scenario:
```sql
drop table if exists observations;

create table observations (
  tenant_id text not null, 
  dummy int,
  measurement_id bigserial not null,
  payload jsonb not null,
  observation_time timestamptz not null default now(),
  PRIMARY KEY (tenant_id, measurement_id)
);
insert into observations (tenant_id, payload) select 'large_tenant', '{"hello":"world"}' from generate_series(1,4000000) s;
alter table observations drop column dummy;

-- start concurrent inserts in a separate session:

insert into observations (tenant_id, payload) values ('large_tenant', '{"current_value" : "29.3"}');
\watch

-- in original session:
select create_distributed_table_concurrently('observations','tenant_id');

```

In the logs I repeatedly see the following message:
```
2022-09-07 14:49:20.495 CEST [4837] ERROR:  unknown type of jsonb container
2022-09-07 14:49:20.495 CEST [4837] CONTEXT:  slot "citus_shard_split_slot_2_10", output plugin "citus", in the change callback, associated LSN 2/BA98CCE8
2022-09-07 14:49:20.495 CEST [4837] STATEMENT:  START_REPLICATION SLOT "citus_shard_split_slot_2_10" LOGICAL 0/0 (proto_version '3', publication_names '"citus_shard_split_publication_2_10"', binary 'true')
```

**Comment by marcocitus** [comment]
Stack trace:
```
#0  0x000055e71c888d4d in iteratorFromContainer (container=container@entry=0x55e71daeff44, parent=parent@entry=0x0) at jsonb_util.c:1033
1033                            elog(ERROR, "unknown type of jsonb container %d", it->state);
#0  0x000055e71c888d4d in iteratorFromContainer (container=container@entry=0x55e71daeff44, parent=parent@entry=0x0) at jsonb_util.c:1033
#1  0x000055e71c88928f in JsonbIteratorInit (container=container@entry=0x55e71daeff44) at jsonb_util.c:821
#2  0x000055e71c881848 in JsonbToCStringWorker (out=out@entry=0x55e71daf04f0, in=in@entry=0x55e71daeff44, estimated_len=<optimized out>, 
    indent=indent@entry=false) at jsonb.c:493
#3  0x000055e71c882236 in JsonbToCString (out=out@entry=0x55e71daf04f0, in=in@entry=0x55e71daeff44, estimated_len=<optimized out>) at jsonb.c:452
#4  0x000055e71c8822a4 in jsonb_send (fcinfo=<optimized out>) at jsonb.c:134
#5  0x000055e71c9672ea in FunctionCall1Coll (flinfo=flinfo@entry=0x7ffe1fb40070, collation=collation@entry=0, arg1=arg1@entry=140417280409928)
    at fmgr.c:1124
#6  0x000055e71c968364 in SendFunctionCall (flinfo=flinfo@entry=0x7ffe1fb40070, val=val@entry=140417280409928) at fmgr.c:1622
#7  0x000055e71c9683aa in OidSendFunctionCall (functionId=<optimized out>, val=140417280409928) at fmgr.c:1663
#8  0x000055e71c77e12c in logicalrep_write_tuple (out=out@entry=0x55e71dadfa20, rel=rel@entry=0x7fb572a3eb60, slot=slot@entry=0x55e71daf3c18, 
    binary=binary@entry=true, columns=columns@entry=0x0) at proto.c:841
#9  0x000055e71c77f3d3 in logicalrep_write_insert (out=0x55e71dadfa20, xid=xid@entry=0, rel=rel@entry=0x7fb572a3eb60, newslot=0x55e71daf3c18, 
    binary=<optimized out>, columns=0x0) at proto.c:427
#10 0x00007fb57dd3ee5f in pgoutput_change (ctx=0x55e71dadf750, txn=0x55e71daf75f8, relation=0x7fb572a3eb60, change=0x55e71db176b8) at pgoutput.c:1451
#11 0x00007fb57de3726d in split_change_cb (ctx=0x55e71dadf750, txn=0x55e71daf75f8, relation=<optimized out>, change=0x55e71db176b8)
    at operations/shardsplit/shardsplit_decoder.c:132
#12 0x000055e71c77890c in change_cb_wrapper (cache=<optimized out>, txn=<optimized out>, relation=<optimized out>, change=<optimized out>) at logical.c:1075
#13 0x000055e71c786945 in ReorderBufferApplyChange (streaming=false, change=0x55e71db176b8, relation=0x7fb572a3bce8, txn=0x55e71daf75f8, rb=0x55e71da1cc00)
    at reorderbuffer.c:1924
#14 ReorderBufferProcessTXN (rb=rb@entry=0x55e71da1cc00, txn=0x55e71daf75f8, commit_lsn=commit_lsn@entry=13329679688, snapshot_now=<optimized out>, 
    command_id=command_id@entry=0, streaming=streaming@entry=false) at reorderbuffer.c:2200
#15 0x000055e71c7878a0 in ReorderBufferReplay (txn=<optimized out>, rb=rb@entry=0x55e71da1cc00, xid=xid@entry=1369447, 
    commit_lsn=commit_lsn@entry=13329679688, end_lsn=end_lsn@entry=13329679736, commit_time=commit_time@entry=715870635518031, origin_id=0, origin_lsn=0)
    at reorderbuffer.c:2630
#16 0x000055e71c788047 in ReorderBufferCommit (rb=0x55e71da1cc00, xid=xid@entry=1369447, commit_lsn=13329679688, end_lsn=13329679736, 
    commit_time=commit_time@entry=715870635518031, origin_id=origin_id@entry=0, origin_lsn=0) at reorderbuffer.c:2654
#17 0x000055e71c774903 in DecodeCommit (ctx=ctx@entry=0x55e71dadf750, buf=buf@entry=0x7ffe1fb40710, parsed=parsed@entry=0x7ffe1fb40580, 
    xid=xid@entry=1369447, two_phase=<optimized out>) at decode.c:696
#18 0x000055e71c775845 in xact_decode (ctx=ctx@entry=0x55e71dadf750, buf=buf@entry=0x7ffe1fb40710) at decode.c:216
#19 0x000055e71c775561 in LogicalDecodingProcessRecord (ctx=0x55e71dadf750, record=0x55e71dadfb48) at decode.c:119
#20 0x000055e71c7a1698 in XLogSendLogical () at walsender.c:3073
#21 0x000055e71c7a4d8d in WalSndLoop (send_data=send_data@entry=0x55e71c7a1641 <XLogSendLogical>) at walsender.c:2503
#22 0x000055e71c7a55c4 in StartLogicalReplication (cmd=cmd@entry=0x55e71dadeb10) at walsender.c:1333
#23 0x000055e71c7a5bf5 in exec_replication_command (
    cmd_string=cmd_string@entry=0x55e71d9660c0 "START_REPLICATION SLOT \"citus_shard_split_slot_2_10\" LOGICAL 0/0 (proto_version '3', publication_names '\"citus_shard_split_publication_2_10\"', binary 'true')") at walsender.c:1843
#24 0x000055e71c803704 in PostgresMain (dbname=<optimized out>, username=<optimized out>) at postgres.c:4577
#25 0x000055e71c75c3ca in BackendRun (port=port@entry=0x55e71da039f0) at postmaster.c:4504
#26 0x000055e71c75f566 in BackendStartup (port=port@entry=0x55e71da039f0) at postmaster.c:4232
#27 0x000055e71c75f7af in ServerLoop () at postmaster.c:1806
#28 0x000055e71c760d81 in PostmasterMain (argc=3, argv=<optimized out>) at postmaster.c:1478
#29 0x000055e71c69c7fc in main (argc=3, argv=0x55e71d95ecc0) at main.c:202
```
