### ISSUE TITLE
isolate_tenant_to_new_shard fails with text argument

### ISSUE THREAD

**Issue by marcocitus** [citusdata/citus#6304]
When using a text argument in isolate_tenant_to_new_shard, I get the following error.
```sql
drop table if exists observations;
create table observations (
  tenant_id text not null, 
  dummy int,
  measurement_id bigserial not null,
  payload jsonb not null,
  observation_time timestamptz not null default now(),
  PRIMARY KEY (tenant_id, measurement_id)
);
select create_distributed_table('observations', 'tenant_id');
select isolate_tenant_to_new_shard(
 'observations', 'large_tenant');
ERROR:  could not determine which collation to use for string hashing
HINT:  Use the COLLATE clause to set the collation explicitly.
```
Setting a COLLATE does not seem to help. Moreover, we should be able to derive the collation from the distribution column.

Stack trace:
```
#0  errstart (elevel=elevel@entry=21, domain=domain@entry=0x0) at elog.c:372
#1  0x000055b26b909000 in errstart_cold (elevel=elevel@entry=21, domain=domain@entry=0x0) at elog.c:326
#2  0x000055b26b414534 in hashtext (fcinfo=0x7fff91516610) at hashfunc.c:276
#3  0x000055b26b90e903 in FunctionCall1Coll (flinfo=0x55b26d4760d0, collation=collation@entry=0, arg1=arg1@entry=94224826004360) at fmgr.c:1138
#4  0x00007fc2db57c47a in isolate_tenant_to_new_shard (fcinfo=<optimized out>) at operations/isolate_shards.c:136
#5  0x000055b26b5ea047 in ExecInterpExpr (state=0x55b26d468ae0, econtext=0x55b26d4687e0, isnull=0x7fff91516787) at execExprInterp.c:749
#6  0x000055b26b5e61d0 in ExecInterpExprStillValid (state=0x55b26d468ae0, econtext=0x55b26d4687e0, isNull=0x7fff91516787) at execExprInterp.c:1824
#7  0x000055b26b6282de in ExecEvalExprSwitchContext (isNull=0x7fff91516787, econtext=0x55b26d4687e0, state=0x55b26d468ae0)
    at ../../../src/include/executor/executor.h:339
#8  ExecProject (projInfo=0x55b26d468ad8) at ../../../src/include/executor/executor.h:373
#9  ExecResult (pstate=<optimized out>) at nodeResult.c:136
#10 0x000055b26b5f7153 in ExecProcNodeFirst (node=0x55b26d4686c8) at execProcnode.c:463
#11 0x000055b26b5ef007 in ExecProcNode (node=0x55b26d4686c8) at ../../../src/include/executor/executor.h:257
#12 ExecutePlan (estate=estate@entry=0x55b26d468490, planstate=0x55b26d4686c8, use_parallel_mode=<optimized out>, operation=operation@entry=CMD_SELECT, 
    sendTuples=sendTuples@entry=true, numberTuples=numberTuples@entry=0, direction=ForwardScanDirection, dest=0x55b26d470bb0, execute_once=true) at execMain.c:1551
#13 0x000055b26b5efccb in standard_ExecutorRun (queryDesc=queryDesc@entry=0x55b26d3a4a00, direction=direction@entry=ForwardScanDirection, count=count@entry=0, 
    execute_once=execute_once@entry=true) at execMain.c:361
#14 0x00007fc2db55e3c7 in CitusExecutorRun (queryDesc=0x55b26d3a4a00, direction=ForwardScanDirection, count=0, execute_once=<optimized out>)
    at executor/multi_executor.c:233
#15 0x00007fc2db49de5b in pgss_ExecutorRun (queryDesc=0x55b26d3a4a00, direction=ForwardScanDirection, count=0, execute_once=<optimized out>)
    at pg_stat_statements.c:1001
#16 0x000055b26b5efd8e in ExecutorRun (queryDesc=queryDesc@entry=0x55b26d3a4a00, direction=direction@entry=ForwardScanDirection, count=count@entry=0, 
    execute_once=<optimized out>) at execMain.c:303
#17 0x000055b26b7bbae6 in PortalRunSelect (portal=portal@entry=0x55b26d3e93f0, forward=forward@entry=true, count=0, count@entry=9223372036854775807, 
    dest=dest@entry=0x55b26d470bb0) at pquery.c:921
#18 0x000055b26b7bd604 in PortalRun (portal=portal@entry=0x55b26d3e93f0, count=count@entry=9223372036854775807, isTopLevel=isTopLevel@entry=true, 
    run_once=run_once@entry=true, dest=dest@entry=0x55b26d470bb0, altdest=altdest@entry=0x55b26d470bb0, qc=0x7fff91516d20) at pquery.c:765
#19 0x000055b26b7b947f in exec_simple_query (
    query_string=query_string@entry=0x55b26d304110 "select isolate_tenant_to_new_shard(\n 'observations', 'large_tenant' collate \"POSIX\");") at postgres.c:1213
#20 0x000055b26b7bb536 in PostgresMain (argc=argc@entry=1, argv=argv@entry=0x7fff91516f20, dbname=<optimized out>, username=<optimized out>) at postgres.c:4496
#21 0x000055b26b713265 in BackendRun (port=port@entry=0x55b26d3a5180) at postmaster.c:4530
#22 0x000055b26b716623 in BackendStartup (port=port@entry=0x55b26d3a5180) at postmaster.c:4252
#23 0x000055b26b71686c in ServerLoop () at postmaster.c:1745
#24 0x000055b26b717dc8 in PostmasterMain (argc=<optimized out>, argv=<optimized out>) at postmaster.c:1417
#25 0x000055b26b65441d in main (argc=3, argv=0x55b26d2fcd10) at main.c:209
```

**Comment by marcocitus** [comment]
Fix is to use:
```c
    /* get hashed value of the distribution value */
    Datum hashedValueDatum = FunctionCall1Coll(cacheEntry->hashFunction,
                                               cacheEntry->partitionColumn->varcollid,
                                               tenantIdDatum);
```
