### ISSUE TITLE
Segmentation fault when doing DROP EXTENSION IF EXISTS citus

### ISSUE THREAD

**Issue by marcocitus** [citusdata/citus#6331]
When the extension does not exist, the following command causes a segmentation fault.
```sql
DROP EXTENSION IF EXISTS citus CASCADE; 
```
This appears to be coming from the columnar DDL hook:
```
0  __strcmp_avx2 () at ../sysdeps/x86_64/multiarch/strcmp-avx2.S:101
#1  0x000055cb8959f95f in RangeVarGetRelidExtended (relation=relation@entry=0x55cb8b047b60, lockmode=lockmode@entry=1, flags=flags@entry=0, callback=callback@entry=0x0, 
    callback_arg=callback_arg@entry=0x0) at namespace.c:256
#2  0x000055cb8949dc13 in relation_openrv_extended (relation=0x55cb8b047b60, lockmode=lockmode@entry=1, missing_ok=<optimized out>) at relation.c:186
#3  0x00007f831e927516 in ColumnarProcessAlterTable (alterTableStmt=alterTableStmt@entry=0x55cb8b047bb8, columnarOptions=columnarOptions@entry=0x7ffe312f7390)
    at columnar_tableam.c:2172
#4  0x00007f831e928146 in ColumnarProcessUtility (pstmt=0x55cb8b047f08, queryString=0x55cb8b047100 "DROP EXTENSION IF EXISTS citus CASCADE;", readOnlyTree=<optimized out>, 
    context=PROCESS_UTILITY_TOPLEVEL, params=0x0, queryEnv=0x0, dest=0x55cb8b047ff8, completionTag=0x7ffe312f7a40) at columnar_tableam.c:2339
#5  0x00007f831f768bf2 in multi_ProcessUtility (pstmt=0x55cb8b047f08, queryString=0x55cb8b047100 "DROP EXTENSION IF EXISTS citus CASCADE;", readOnlyTree=<optimized out>, 
    context=PROCESS_UTILITY_TOPLEVEL, params=0x0, queryEnv=0x0, dest=0x55cb8b047ff8, completionTag=0x7ffe312f7a40) at commands/utility_hook.c:220
..
#8  0x000055cb8989661e in ProcessUtility (pstmt=pstmt@entry=0x55cb8b047f08, queryString=<optimized out>, readOnlyTree=<optimized out>, context=<optimized out>, 
    params=<optimized out>, queryEnv=<optimized out>, dest=0x55cb8b047ff8, qc=0x7ffe312f7a40) at utility.c:526
#9  0x000055cb89893a31 in PortalRunUtility (portal=portal@entry=0x55cb8b10ffc0, pstmt=pstmt@entry=0x55cb8b047f08, isTopLevel=isTopLevel@entry=true, 
    setHoldSnapshot=setHoldSnapshot@entry=false, dest=dest@entry=0x55cb8b047ff8, qc=qc@entry=0x7ffe312f7a40) at pquery.c:1158
#10 0x000055cb89893d49 in PortalRunMulti (portal=portal@entry=0x55cb8b10ffc0, isTopLevel=isTopLevel@entry=true, setHoldSnapshot=setHoldSnapshot@entry=false, 
    dest=dest@entry=0x55cb8b047ff8, altdest=altdest@entry=0x55cb8b047ff8, qc=qc@entry=0x7ffe312f7a40) at pquery.c:1315
#11 0x000055cb898941a3 in PortalRun (portal=portal@entry=0x55cb8b10ffc0, count=count@entry=9223372036854775807, isTopLevel=isTopLevel@entry=true, run_once=run_once@entry=true, 
    dest=dest@entry=0x55cb8b047ff8, altdest=altdest@entry=0x55cb8b047ff8, qc=0x7ffe312f7a40) at pquery.c:791
#12 0x000055cb89890170 in exec_simple_query (query_string=query_string@entry=0x55cb8b047100 "DROP EXTENSION IF EXISTS citus CASCADE;") at postgres.c:1250
#13 0x000055cb898920e0 in PostgresMain (dbname=<optimized out>, username=<optimized out>) at postgres.c:4581
#14 0x000055cb897ead90 in BackendRun (port=port@entry=0x55cb8b0c19b0) at postmaster.c:4504
#15 0x000055cb897edf2c in BackendStartup (port=port@entry=0x55cb8b0c19b0) at postmaster.c:4232
#16 0x000055cb897ee175 in ServerLoop () at postmaster.c:1806
#17 0x000055cb897ef747 in PostmasterMain (argc=3, argv=<optimized out>) at postmaster.c:1478
#18 0x000055cb8972f2d4 in main (argc=3, argv=0x55cb8b03fd00) at main.c:202
```

**Comment by marcocitus** [comment]
seems like it was a build issue
