### ISSUE TITLE
SQLancer "database is being accessed by other users"

### ISSUE THREAD

**Issue by mrigger** [citusdata/citus#6670]
The Citus implementation of SQLancer has been failing for the last couple of months (see https://github.com/sqlancer/sqlancer/issues/698). I just created a PR to ignore a known Citus bug in SQLancer (see https://github.com/sqlancer/sqlancer/pull/706), but the tests still frequently fail with the issue below:

```
org.postgresql.util.PSQLException: ERROR: database "database1" is being accessed by other users
  Detail: There is 1 other session using the database.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:496)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:413)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:333)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:319)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:295)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:290)
	at sqlancer.citus.CitusProvider.prepareCitusWorkerNodes(CitusProvider.java:374)
	at sqlancer.citus.CitusProvider.createDatabase(CitusProvider.java:426)
	at sqlancer.postgres.PostgresProvider.createDatabase(PostgresProvider.java:1)
	at sqlancer.Main$DBMSExecutor.run(Main.java:347)
	at sqlancer.Main$2.run(Main.java:559)
	at sqlancer.Main$2.runThread(Main.java:541)
	at sqlancer.Main$2.run(Main.java:532)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
--org.postgresql.util.PSQLException: ERROR: database "database1" is being accessed by other users
--  Detail: There is 1 other session using the database.
--	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
--	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
--	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
--	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:496)
--	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:413)
--	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:333)
--	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:319)
--	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:295)
--	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:290)
--	at sqlancer.citus.CitusProvider.prepareCitusWorkerNodes(CitusProvider.java:374)
--	at sqlancer.citus.CitusProvider.createDatabase(CitusProvider.java:426)
--	at sqlancer.postgres.PostgresProvider.createDatabase(PostgresProvider.java:1)
--	at sqlancer.Main$DBMSExecutor.run(Main.java:347)
--	at sqlancer.Main$2.run(Main.java:559)
--	at sqlancer.Main$2.runThread(Main.java:541)
--	at sqlancer.Main$2.run(Main.java:532)
--	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
--	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
--	at java.base/java.lang.Thread.run(Thread.java:829)
--
-- Time: [202](https://github.com/sqlancer/sqlancer/actions/runs/4035273876/jobs/6937078631#step:6:203)3/01/29 05:19:44
-- Database: database1
-- Database version: null
-- seed value: 1
\c test;
DROP DATABASE IF EXISTS database1;
CREATE DATABASE database1 ;
\c database1;
CREATE EXTENSION citus;
\c test;
SELECT * FROM citus_get_active_worker_nodes();
\q;
postgresql://localhost:9701/test;
DROP DATABASE IF EXISTS database1;
CREATE DATABASE database1 ;
```

Any idea what the problem could be and how SQLancer should address it? Most of the Citus implementation was contributed by the Citus team, so I am not that familiar with this part of SQLancer's code and Citus' expected behavior.

**Comment by onurctirtir** [comment]
Hey @mrigger,

Could you the sqlancer command to reproduce this issue so that we can take a look to see what's happening ?

**Comment by mrigger** [comment]
This currently reproduces using `CITUS_AVAILABLE=true mvn -Dtest=TestCitus test`. The environment setup is specified here:

https://github.com/sqlancer/sqlancer/blob/6d90c985950f4afbf12728d1f2cf99c00dc2a86d/.github/workflows/main.yml#L43-L71

**Comment by onurctirtir** [comment]
I guess this is probably same as https://github.com/citusdata/citus/issues/5297.

**Comment by mrigger** [comment]
I see the issue was already opened in 2021. Interestingly, the errors started appearing in SQLancer only a couple of months ago - perhaps a change in the environment in which the tests are run.

**Comment by onurctirtir** [comment]
Hey @mrigger, I have two questions:
* Does that break SQLAncer tests on Citus or can it be ignored by the tool --maybe adding this to some ignore-lists?
* Is it the case that the database that you're connected to "doesn't have Citus installed" but the database to be dropped "has Citus" ?

(cc: @gokhangulbiz)

**Comment by onurctirtir** [comment]
I see what's happening now. Looks like `CREATE EXTENSION` hack works for coordinator but not for worker nodes and probably we're getting this error from one of the worker nodes.

**Comment by malwaregarry** [comment]
Hi, we're still facing this error even though we updated to 11.3 which contains the update.
https://github.com/malwaregarry/sqlancer/actions/runs/9723253169/job/26838146444?pr=9

This is the configuration used in the CI
https://github.com/malwaregarry/sqlancer/blob/31abc1846eefb6762a151a1ca079fe9c2de5943f/.github/workflows/main.yml#L64-L91
