### ISSUE TITLE
PlaceHolderVar found where not expected

### ISSUE THREAD

**Issue by aykut-bozkurt** [citusdata/citus#6758]
During integration of join query generator tool into Citus CI tests (PR https://github.com/citusdata/citus/pull/6686), I noticed the error below ~5 times over 10.000 generated queries:

```sql
CREATE TABLE dist0(id int);
SELECT create_distributed_table('dist0','id');

CREATE TABLE dist1(id int);
SELECT create_distributed_table('dist1','id');

SELECT avg(avgsub.id) FROM  (  SELECT  table_0.id  FROM  (  SELECT  table_1.id  FROM  (  SELECT  table_2.id  FROM  (  SELECT  table_3.id  FROM  ( VALUES(838 ) )  AS  table_3(id)  FULL JOIN dist0  AS  table_4 USING (id )  WHERE  table_4.id = 3 )  AS  table_2 WHERE  table_2.id = 2 ORDER BY id  LIMIT 77 )  AS  table_1 LEFT JOIN dist0  AS  table_5 USING (id )  ORDER BY id  LIMIT 44 )  AS  table_0 FULL JOIN dist1  AS  table_6 USING (id )  )  AS avgsub;

ERROR:  PlaceHolderVar found where not expected
```

The query above works fine for undistributed PG tables.

**Comment by JelteF** [comment]
backtrace:

```gdb
#0  errstart (elevel=elevel@entry=21, domain=domain@entry=0x0) at elog.c:367
#1  0x000055f749020de0 in errstart_cold (elevel=elevel@entry=21, domain=domain@entry=0x0) at elog.c:321
#2  0x000055f748e0a735 in pull_var_clause_walker (node=<optimized out>, context=0x7ffe2fbfbf50) at var.c:700
#3  0x000055f748d80b93 in expression_tree_walker (node=0x55f74ad963d0, walker=walker@entry=0x55f748e0a6bf <pull_var_clause_walker>, context=context@entry=0x7ffe2fbfbf50) at nodeFuncs.c:2235
#4  0x000055f748d8075a in expression_tree_walker (node=0x55f74ad96378, walker=walker@entry=0x55f748e0a6bf <pull_var_clause_walker>, context=context@entry=0x7ffe2fbfbf50) at nodeFuncs.c:2028
#5  0x000055f748e0a7e3 in pull_var_clause_walker (node=node@entry=0x55f74ad96378, context=context@entry=0x7ffe2fbfbf50) at var.c:702
#6  0x000055f748e0b2d5 in pull_var_clause (node=node@entry=0x55f74ad96378, flags=flags@entry=10) at var.c:619
#7  0x00007faef1b93d06 in pull_var_clause_default (node=node@entry=0x55f74ad96378) at planner/multi_logical_planner.c:1923
#8  0x00007faef1ba90c9 in GetRestrictInfoListForRelation (rangeTblEntry=rangeTblEntry@entry=0x55f74aced080, plannerRestrictionContext=<optimized out>) at planner/relation_restriction_equivalence.c:2113
#9  0x00007faef1ba631c in ReplaceRTERelationWithRteSubquery (rangeTableEntry=rangeTableEntry@entry=0x55f74aced080, requiredAttrNumbers=<optimized out>, context=context@entry=0x7ffe2fbfc5d0) at planner/recursive_planning.c:1761
#10 0x00007faef1ba65f6 in RecursivelyPlanDistributedJoinNode (node=node@entry=0x55f74aced7b8, query=query@entry=0x55f74acec620, recursivePlanningContext=recursivePlanningContext@entry=0x7ffe2fbfc5d0) at planner/recursive_planning.c:890
#11 0x00007faef1ba689d in RecursivelyPlanRecurringTupleOuterJoinWalker (node=0x55f74acebc40, query=query@entry=0x55f74acec620, recursivePlanningContext=recursivePlanningContext@entry=0x7ffe2fbfc5d0) at planner/recursive_planning.c:760
#12 0x00007faef1ba6728 in RecursivelyPlanRecurringTupleOuterJoinWalker (node=<optimized out>, query=query@entry=0x55f74acec620, recursivePlanningContext=recursivePlanningContext@entry=0x7ffe2fbfc5d0) at planner/recursive_planning.c:676
#13 0x00007faef1ba6eae in RecursivelyPlanSubqueriesAndCTEs (query=query@entry=0x55f74acec620, context=context@entry=0x7ffe2fbfc5d0) at planner/recursive_planning.c:361
#14 0x00007faef1ba7003 in RecursivelyPlanSubqueryWalker (node=0x55f74acec620, context=0x7ffe2fbfc5d0) at planner/recursive_planning.c:1236
#15 0x000055f748d80fb0 in range_table_entry_walker (rte=0x55f74acec508, walker=walker@entry=0x7faef1ba6fc9 <RecursivelyPlanSubqueryWalker>, context=context@entry=0x7ffe2fbfc5d0, flags=flags@entry=0) at nodeFuncs.c:2537
#16 0x000055f748d81051 in range_table_walker (rtable=0x55f74acebb20, walker=walker@entry=0x7faef1ba6fc9 <RecursivelyPlanSubqueryWalker>, context=context@entry=0x7ffe2fbfc5d0, flags=flags@entry=0) at nodeFuncs.c:2505
#17 0x000055f748d812b4 in query_tree_walker (query=query@entry=0x55f74acec3f0, walker=walker@entry=0x7faef1ba6fc9 <RecursivelyPlanSubqueryWalker>, context=context@entry=0x7ffe2fbfc5d0, flags=flags@entry=0) at nodeFuncs.c:2482
#18 0x00007faef1ba6d7e in RecursivelyPlanSubqueriesAndCTEs (query=query@entry=0x55f74acec3f0, context=context@entry=0x7ffe2fbfc5d0) at planner/recursive_planning.c:302
#19 0x00007faef1ba7003 in RecursivelyPlanSubqueryWalker (node=0x55f74acec3f0, context=0x7ffe2fbfc5d0) at planner/recursive_planning.c:1236
#20 0x000055f748d80fb0 in range_table_entry_walker (rte=0x55f74acec2d8, walker=walker@entry=0x7faef1ba6fc9 <RecursivelyPlanSubqueryWalker>, context=context@entry=0x7ffe2fbfc5d0, flags=flags@entry=0) at nodeFuncs.c:2537
#21 0x000055f748d81051 in range_table_walker (rtable=0x55f74acec280, walker=walker@entry=0x7faef1ba6fc9 <RecursivelyPlanSubqueryWalker>, context=context@entry=0x7ffe2fbfc5d0, flags=flags@entry=0) at nodeFuncs.c:2505
#22 0x000055f748d812b4 in query_tree_walker (query=query@entry=0x55f74acec168, walker=walker@entry=0x7faef1ba6fc9 <RecursivelyPlanSubqueryWalker>, context=context@entry=0x7ffe2fbfc5d0, flags=flags@entry=0) at nodeFuncs.c:2482
#23 0x00007faef1ba6d7e in RecursivelyPlanSubqueriesAndCTEs (query=query@entry=0x55f74acec168, context=context@entry=0x7ffe2fbfc5d0) at planner/recursive_planning.c:302
#24 0x00007faef1ba7003 in RecursivelyPlanSubqueryWalker (node=0x55f74acec168, context=0x7ffe2fbfc5d0) at planner/recursive_planning.c:1236
#25 0x000055f748d80fb0 in range_table_entry_walker (rte=0x55f74acec050, walker=walker@entry=0x7faef1ba6fc9 <RecursivelyPlanSubqueryWalker>, context=context@entry=0x7ffe2fbfc5d0, flags=flags@entry=0) at nodeFuncs.c:2537
#26 0x000055f748d81051 in range_table_walker (rtable=0x55f74acebff8, walker=walker@entry=0x7faef1ba6fc9 <RecursivelyPlanSubqueryWalker>, context=context@entry=0x7ffe2fbfc5d0, flags=flags@entry=0) at nodeFuncs.c:2505
#27 0x000055f748d812b4 in query_tree_walker (query=query@entry=0x55f74acebee0, walker=walker@entry=0x7faef1ba6fc9 <RecursivelyPlanSubqueryWalker>, context=context@entry=0x7ffe2fbfc5d0, flags=flags@entry=0) at nodeFuncs.c:2482
#28 0x00007faef1ba6d7e in RecursivelyPlanSubqueriesAndCTEs (query=query@entry=0x55f74acebee0, context=context@entry=0x7ffe2fbfc5d0) at planner/recursive_planning.c:302
#29 0x00007faef1ba7003 in RecursivelyPlanSubqueryWalker (node=0x55f74acebee0, context=0x7ffe2fbfc5d0) at planner/recursive_planning.c:1236
#30 0x000055f748d80fb0 in range_table_entry_walker (rte=0x55f74acebdc8, walker=walker@entry=0x7faef1ba6fc9 <RecursivelyPlanSubqueryWalker>, context=context@entry=0x7ffe2fbfc5d0, flags=flags@entry=0) at nodeFuncs.c:2537
#31 0x000055f748d81051 in range_table_walker (rtable=0x55f74acebb58, walker=walker@entry=0x7faef1ba6fc9 <RecursivelyPlanSubqueryWalker>, context=context@entry=0x7ffe2fbfc5d0, flags=flags@entry=0) at nodeFuncs.c:2505
#32 0x000055f748d812b4 in query_tree_walker (query=query@entry=0x55f74ace7cc0, walker=walker@entry=0x7faef1ba6fc9 <RecursivelyPlanSubqueryWalker>, context=context@entry=0x7ffe2fbfc5d0, flags=flags@entry=0) at nodeFuncs.c:2482
#33 0x00007faef1ba6d7e in RecursivelyPlanSubqueriesAndCTEs (query=query@entry=0x55f74ace7cc0, context=context@entry=0x7ffe2fbfc5d0) at planner/recursive_planning.c:302
#34 0x00007faef1ba6f11 in GenerateSubplansForSubqueriesAndCTEs (planId=planId@entry=3, originalQuery=originalQuery@entry=0x55f74ace7cc0, plannerRestrictionContext=plannerRestrictionContext@entry=0x55f74acefe48) at planner/recursive_planning.c:236
#35 0x00007faef1b7e912 in CreateDistributedPlan (planId=planId@entry=3, allowRecursivePlanning=allowRecursivePlanning@entry=true, originalQuery=0x55f74ace7cc0, query=0x55f74ace7dd8, boundParams=0x0, hasUnresolvedParams=hasUnresolvedParams@entry=false, plannerRestrictionContext=0x55f74acefe48) at planner/distributed_planner.c:1089
#36 0x00007faef1b7f402 in CreateDistributedPlannedStmt (planContext=planContext@entry=0x7ffe2fbfc740) at planner/distributed_planner.c:794
#37 0x00007faef1b7f81d in PlanDistributedStmt (planContext=planContext@entry=0x7ffe2fbfc740, rteIdCounter=<optimized out>, rteIdCounter@entry=4) at planner/distributed_planner.c:730
#38 0x00007faef1b802c3 in distributed_planner (parse=0x55f74ace7dd8, query_string=<optimized out>, cursorOptions=<optimized out>, boundParams=0x0) at planner/distributed_planner.c:264
#39 0x00007faef0f617ec in pgss_planner (parse=0x55f74ace7dd8, query_string=0x55f74ab29200 "SELECT avg(avgsub.id) FROM  (  SELECT  table_0.id  FROM  (  SELECT  table_1.id  FROM  (  SELECT  table_2.id  FROM  (  SELECT  table_3.id  FROM  ( VALUES(838 ) )  AS  table_3(id)  FULL JOIN dist0  AS  "..., cursorOptions=2048, boundParams=0x0) at pg_stat_statements.c:953
#40 0x000055f748ddc633 in planner (parse=parse@entry=0x55f74ace7dd8, query_string=query_string@entry=0x55f74ab29200 "SELECT avg(avgsub.id) FROM  (  SELECT  table_0.id  FROM  (  SELECT  table_1.id  FROM  (  SELECT  table_2.id  FROM  (  SELECT  table_3.id  FROM  ( VALUES(838 ) )  AS  table_3(id)  FULL JOIN dist0  AS  "..., cursorOptions=cursorOptions@entry=2048, boundParams=boundParams@entry=0x0) at planner.c:275
#41 0x000055f748ec91df in pg_plan_query (querytree=querytree@entry=0x55f74ace7dd8, query_string=query_string@entry=0x55f74ab29200 "SELECT avg(avgsub.id) FROM  (  SELECT  table_0.id  FROM  (  SELECT  table_1.id  FROM  (  SELECT  table_2.id  FROM  (  SELECT  table_3.id  FROM  ( VALUES(838 ) )  AS  table_3(id)  FULL JOIN dist0  AS  "..., cursorOptions=cursorOptions@entry=2048, boundParams=boundParams@entry=0x0) at postgres.c:883
#42 0x000055f748ec929c in pg_plan_queries (querytrees=0x55f74acebab0, query_string=query_string@entry=0x55f74ab29200 "SELECT avg(avgsub.id) FROM  (  SELECT  table_0.id  FROM  (  SELECT  table_1.id  FROM  (  SELECT  table_2.id  FROM  (  SELECT  table_3.id  FROM  ( VALUES(838 ) )  AS  table_3(id)  FULL JOIN dist0  AS  "..., cursorOptions=cursorOptions@entry=2048, boundParams=boundParams@entry=0x0) at postgres.c:975
#43 0x000055f748ec97df in exec_simple_query (query_string=query_string@entry=0x55f74ab29200 "SELECT avg(avgsub.id) FROM  (  SELECT  table_0.id  FROM  (  SELECT  table_1.id  FROM  (  SELECT  table_2.id  FROM  (  SELECT  table_3.id  FROM  ( VALUES(838 ) )  AS  table_3(id)  FULL JOIN dist0  AS  "...) at postgres.c:1169
#44 0x000055f748ecb85f in PostgresMain (dbname=<optimized out>, username=<optimized out>) at postgres.c:4593
#45 0x000055f748e231e1 in BackendRun (port=port@entry=0x55f74abd7710) at postmaster.c:4511
#46 0x000055f748e26365 in BackendStartup (port=port@entry=0x55f74abd7710) at postmaster.c:4239
#47 0x000055f748e265a0 in ServerLoop () at postmaster.c:1806
#48 0x000055f748e27b78 in PostmasterMain (argc=argc@entry=5, argv=argv@entry=0x55f74aa90c60) at postmaster.c:1478
#49 0x000055f748d67be2 in main (argc=5, argv=0x55f74aa90c60) at main.c:202
```
