### ISSUE TITLE
Citus with auto_explain set to true is returning unwanted tuple data.

### ISSUE THREAD

**Issue by tejeswarm** [citusdata/citus#6777]
Executing a task with multiple queries is resulting in this unexpected behavior when processing query result(s).

```
CREATE TABLE ref_table (id int, nonid int);
SELECT create_reference_table('ref_table');
select * from ref_table;
┌────┬───────┐
│ id │ nonid │
├────┼───────┤
└────┴───────┘
(0 rows)

postgres=# set citus.log_remote_commands to true;
set citus.log_remote_commands to true;
SET
postgres=# set auto_explain.log_analyze to true; LOAD 'auto_explain';
set auto_explain.log_analyze to true;
SET
LOAD 'auto_explain';
LOAD
postgres=# select * from ref_table;
select * from ref_table;
NOTICE:  executing the command locally:
SELECT * FROM worker_save_query_explain_analyze('SELECT id, nonid FROM citus.ref_table_102012 ref_table', '{"verbose": false, "costs": false, "buffers": false, "wal": false, "timing": false, "summary": false, "format": "TEXT"}') AS (field_0 integer, field_1 integer);
SELECT explain_analyze_output, execution_duration FROM worker_last_saved_explain_analyze();
NOTICE:  issuing BEGIN TRANSACTION ISOLATION LEVEL READ COMMITTED;SELECT assign_distributed_transaction_id(0, 1, '2023-03-19 14:39:42.224534-07');
DETAIL:  on server citus@127.0.0.1:9000 connectionId: 1
NOTICE:  issuing SAVEPOINT citus_explain_savepoint
DETAIL:  on server citus@127.0.0.1:9000 connectionId: 1
NOTICE:  issuing EXPLAIN (ANALYZE TRUE, VERBOSE FALSE, COSTS TRUE, BUFFERS FALSE, WAL FALSE, TIMING TRUE, SUMMARY TRUE, FORMAT TEXT) SELECT id, nonid FROM citus.ref_table_102012 ref_table
DETAIL:  on server citus@127.0.0.1:9000 connectionId: 1
NOTICE:  issuing ROLLBACK TO SAVEPOINT citus_explain_savepoint
DETAIL:  on server citus@127.0.0.1:9000 connectionId: 1
NOTICE:  issuing COMMIT
DETAIL:  on server citus@127.0.0.1:9000 connectionId: 1
┌────────────┬────────────┐
│     id     │   nonid    │
├────────────┼────────────┤
│ 1902465921 │ 1633899296 │
└────────────┴────────────┘
(1 row)

```

**Comment by onderkalaci** [comment]
Marking https://github.com/citusdata/citus/issues/6448 as related. Note that we have several problems with auto_explain = on.

**Comment by emelsimsek** [comment]
I was able to repro this issue when I added the coordinator as a node and then created the reference table.  

SELECT 1 FROM master_add_node('localhost', 9700, groupId => 0);
SELECT citus_set_node_property('localhost', 9700, 'shouldhaveshards', true);

In this case, the reference table is replicated in the coordinator and the select query is executed locally. 

postgres=# select * from ref_table;
select * from ref_table;
**NOTICE:  executing the command locally:**

Also note that, the garbage tuple returned is actually memory overridden. This scenario actually ends up with a crash due to  Assert in debug builds.

```
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140688889345856) at ./nptl/pthread_kill.c:44 
#1  __pthread_kill_internal (signo=6, threadid=140688889345856) at ./nptl/pthread_kill.c:78 
#2  __GI___pthread_kill (threadid=140688889345856, signo=signo@entry=6) at ./nptl/pthread_kill.c:89 
#3  0x00007ff4b133b476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26 
#4  0x00007ff4b13217f3 in __GI_abort () at ./stdlib/abort.c:79 
#5  0x000056274147f2d2 in ExceptionalCondition ( 
    conditionName=conditionName@entry=0x7ff4af0b459b "task->queryCount == 1", 
    errorType=errorType@entry=0x7ff4af096081 "FailedAssertion", 
    fileName=fileName@entry=0x7ff4af0b457e "executor/tuple_destination.c", lineNumber=lineNumber@entry=280) 
    at assert.c:69 
#6  0x00007ff4aefff24a in TupleDestDestReceiverReceive (slot=<optimized out>, destReceiver=<optimized out>) 
    at executor/tuple_destination.c:280 
#7  0x0000562741164829 in ExecutePlan (estate=estate@entry=0x56274309fa20, planstate=0x56274309fc58, 
    use_parallel_mode=<optimized out>, operation=operation@entry=CMD_SELECT, sendTuples=sendTuples@entry=true, 
    numberTuples=numberTuples@entry=0, direction=ForwardScanDirection, dest=0x56274309da10, execute_once=true) 
    at execMain.c:1667 
#8  0x00005627411649d1 in standard_ExecutorRun (queryDesc=queryDesc@entry=0x56274309da68, 
    direction=direction@entry=ForwardScanDirection, count=count@entry=0, execute_once=execute_once@entry=true) 
    at execMain.c:363 
#9  0x00007ff4aeffb78f in CitusExecutorRun (queryDesc=0x56274309da68, direction=ForwardScanDirection, count=0, 
    execute_once=<optimized out>) at executor/multi_executor.c:238 
#10 0x00007ff4ae40ae92 in pgss_ExecutorRun (queryDesc=0x56274309da68, direction=ForwardScanDirection, count=0, 
    execute_once=<optimized out>) at pg_stat_statements.c:1008 
#11 0x00007ff4aef328a0 in explain_ExecutorRun (queryDesc=0x56274309da68, direction=ForwardScanDirection, count=0, 
    execute_once=<optimized out>) at auto_explain.c:320 
#12 0x0000562741164a91 in ExecutorRun (queryDesc=queryDesc@entry=0x56274309da68, 
    direction=direction@entry=ForwardScanDirection, count=count@entry=0, execute_once=execute_once@entry=true) 
    at execMain.c:305 
#13 0x00007ff4aeffa1ee in ExecuteTaskPlan (taskPlan=taskPlan@entry=0x5627430a96d8, 
    queryString=queryString@entry=0x56274308b7e8 "SELECT explain_analyze_output, execution_duration FROM worker_last_saved_explain_analyze()", tupleDest=tupleDest@entry=0x56274308ab40, task=task@entry=0x56274308f708, 
    paramListInfo=paramListInfo@entry=0x0) at executor/local_executor.c:762 
#14 0x00007ff4aeffa37e in LocallyExecuteTaskPlan (taskPlan=0x5627430a96d8, 
    queryString=queryString@entry=0x56274308b7e8 "SELECT explain_analyze_output, execution_duration FROM worker_last_saved_explain_analyze()", tupleDest=tupleDest@entry=0x56274308ab40, task=task@entry=0x56274308f708, 
    paramListInfo=paramListInfo@entry=0x0) at executor/local_executor.c:696 
#15 0x00007ff4aeffa485 in LocallyPlanAndExecuteMultipleQueries (queryStrings=0x56274308f840, 
    tupleDest=tupleDest@entry=0x56274308ab40, task=task@entry=0x56274308f708) at executor/local_executor.c:422 
#16 0x00007ff4aeffacba in ExecuteLocalTaskListExtended (taskList=0x56274308fbd8, orig_paramListInfo=<optimized out>, 
    distributedPlan=0x56274305e278, defaultTupleDest=0x562743081b80, isUtilityCommand=isUtilityCommand@entry=false) 
    at executor/local_executor.c:333 
#17 0x00007ff4aeff12eb in RunLocalExecution (scanState=scanState@entry=0x56274304aaf0, 
    execution=execution@entry=0x56274308af20) at executor/adaptive_executor.c:915 
#18 0x00007ff4aeff4389 in AdaptiveExecutor (scanState=0x56274304aaf0) at executor/adaptive_executor.c:882 
#19 0x00007ff4aeff4cd7 in CitusExecScan (node=0x56274304aaf0) at executor/citus_custom_scan.c:244 
#20 0x0000562741182227 in ExecCustomScan (pstate=0x56274304aaf0) at nodeCustom.c:115 
#21 0x000056274116c483 in ExecProcNodeInstr (node=0x56274304aaf0) at execProcnode.c:480 
#22 0x000056274116c456 in ExecProcNodeFirst (node=0x56274304aaf0) at execProcnode.c:464 
#23 0x00005627411647f8 in ExecProcNode (node=0x56274304aaf0) at ../../../src/include/executor/executor.h:259 
#24 ExecutePlan (estate=estate@entry=0x56274304a8b0, planstate=0x56274304aaf0, use_parallel_mode=<optimized out>, 
    operation=operation@entry=CMD_SELECT, sendTuples=sendTuples@entry=true, numberTuples=numberTuples@entry=0, 
    direction=ForwardScanDirection, dest=0x562743060ff0, execute_once=true) at execMain.c:1636 
#25 0x00005627411649d1 in standard_ExecutorRun (queryDesc=queryDesc@entry=0x562742f71fa0, 
    direction=direction@entry=ForwardScanDirection, count=count@entry=0, execute_once=execute_once@entry=true) 
    at execMain.c:363 
#26 0x00007ff4aeffb78f in CitusExecutorRun (queryDesc=0x562742f71fa0, direction=ForwardScanDirection, count=0, 
    execute_once=<optimized out>) at executor/multi_executor.c:238 
#27 0x00007ff4ae40ae92 in pgss_ExecutorRun (queryDesc=0x562742f71fa0, direction=ForwardScanDirection, count=0,  
```
