### ISSUE TITLE
Server crashes when trying to execute SELECT unnest(activate_node_snapshot());

### ISSUE THREAD

**Issue by saygoodbyye** [citusdata/citus#7551]
Hello! I have got a server crash when executing the following SQL-script (test.sql). I have postgres on REL_16_STABLE branch and citus on main branch. 
Postgres build:
```
CFLAGS="-Og" ./configure \
        --enable-cassert \
        --enable-tap-tests \
        --enable-debug \
        --with-icu \
        --with-lz4 \
        --with-libxml \
        --with-openssl \
        --prefix=$DATA \
        --quiet
```
Citus build:
```
PG_CONFIG=$PG_CONFIG ./configure --without-lz4 --without-zstd
```
postgresql.conf:
```
shared_preload_libraries='citus'
```
test.sql:
```sql
CREATE EXTENSION citus;
CREATE FUNCTION activate_node_snapshot()
    RETURNS text[]
    LANGUAGE C STRICT
    AS 'citus';
SELECT unnest(activate_node_snapshot()) order by 1;
```
backtrace:
```
#0  NodeIsPrimary (worker=worker@entry=0x0) at metadata/node_metadata.c:846
#1  0x00007f35aa327fc3 in SetMetadataSyncNodesFromNodeList (context=context@entry=0x55f7372d5af8, nodeList=nodeList@entry=0x55f7372d5aa8)
    at metadata/metadata_sync.c:4368
#2  0x00007f35aa3281bd in CreateMetadataSyncContext (nodeList=0x55f7372d5aa8, collectCommands=collectCommands@entry=true,
    nodesAddedInSameTransaction=nodesAddedInSameTransaction@entry=false) at metadata/metadata_sync.c:4447
#3  0x00007f35aa3864dd in activate_node_snapshot (fcinfo=<optimized out>) at test/metadata_sync.c:61
#4  0x000055f7366c0596 in ExecInterpExpr (state=0x55f7373193b0, econtext=0x55f737318920, isnull=0x55f737319af8) at execExprInterp.c:734
#5  0x000055f7366bc9a7 in ExecInterpExprStillValid (state=0x55f7373193b0, econtext=0x55f737318920, isNull=0x55f737319af8) at execExprInterp.c:1870
#6  0x000055f7366cf4bf in ExecEvalExpr (isNull=0x55f737319af8, econtext=0x55f737318920, state=<optimized out>)
    at ../../../src/include/executor/executor.h:336
#7  ExecEvalFuncArgs (fcinfo=fcinfo@entry=0x55f737319ad0, argList=0x55f737319a80, econtext=econtext@entry=0x55f737318920) at execSRF.c:847
#8  0x000055f7366d0523 in ExecMakeFunctionResultSet (fcache=0x55f737319320, econtext=econtext@entry=0x55f737318920, argContext=0x55f7372d5990,
    isNull=0x55f7373192b0, isDone=isDone@entry=0x55f737319308) at execSRF.c:577
#9  0x000055f7366fd465 in ExecProjectSRF (node=node@entry=0x55f737318810, continuing=continuing@entry=false) at nodeProjectSet.c:183
#10 0x000055f7366fd584 in ExecProjectSet (pstate=0x55f737318810) at nodeProjectSet.c:107
#11 0x000055f7366cd63c in ExecProcNodeFirst (node=0x55f737318810) at execProcnode.c:464
#12 0x000055f7366ffa6e in ExecProcNode (node=0x55f737318810) at ../../../src/include/executor/executor.h:273
#13 ExecSort (pstate=0x55f737318600) at nodeSort.c:135
#14 0x000055f7366cd63c in ExecProcNodeFirst (node=0x55f737318600) at execProcnode.c:464
#15 0x000055f7366c5bff in ExecProcNode (node=0x55f737318600) at ../../../src/include/executor/executor.h:273
#16 ExecutePlan (estate=estate@entry=0x55f7373183d8, planstate=0x55f737318600, use_parallel_mode=<optimized out>, operation=operation@entry=CMD_SELECT,
    sendTuples=sendTuples@entry=true, numberTuples=numberTuples@entry=0, direction=ForwardScanDirection, dest=0x55f73741a378, execute_once=true)
    at execMain.c:1670
#17 0x000055f7366c5dc2 in standard_ExecutorRun (queryDesc=queryDesc@entry=0x55f737289b38, direction=direction@entry=ForwardScanDirection,
    count=count@entry=0, execute_once=execute_once@entry=true) at execMain.c:365
#18 0x00007f35aa313dec in CitusExecutorRun (queryDesc=0x55f737289b38, direction=ForwardScanDirection, count=0, execute_once=<optimized out>)
    at executor/multi_executor.c:238
#19 0x000055f7366c5e8f in ExecutorRun (queryDesc=queryDesc@entry=0x55f737289b38, direction=direction@entry=ForwardScanDirection, count=count@entry=0,
    execute_once=<optimized out>) at execMain.c:307
#20 0x000055f7368afbd1 in PortalRunSelect (portal=portal@entry=0x55f7371b2208, forward=forward@entry=true, count=0, count@entry=9223372036854775807,
    dest=dest@entry=0x55f73741a378) at pquery.c:924
#21 0x000055f7368b1572 in PortalRun (portal=portal@entry=0x55f7371b2208, count=count@entry=9223372036854775807, isTopLevel=isTopLevel@entry=true, run_once=run_once@entry=true, dest=dest@entry=0x55f73741a378, altdest=altdest@entry=0x55f73741a378, qc=0x7ffdf3a07500) at pquery.c:768
#22 0x000055f7368ad689 in exec_simple_query (query_string=query_string@entry=0x55f7370e1f18 "SELECT unnest(activate_node_snapshot()) order by 1;") at postgres.c:1274
#23 0x000055f7368af50a in PostgresMain (dbname=<optimized out>, username=<optimized out>) at postgres.c:4637
#24 0x000055f736806a3b in BackendRun (port=port@entry=0x55f737163f30) at postmaster.c:4464
#25 0x000055f736809b23 in BackendStartup (port=port@entry=0x55f737163f30) at postmaster.c:4192
#26 0x000055f736809cc1 in ServerLoop () at postmaster.c:1782
#27 0x000055f73680b1f1 in PostmasterMain (argc=argc@entry=3, argv=argv@entry=0x55f737049ad0) at postmaster.c:1466
#28 0x000055f7367286ac in main (argc=3, argv=0x55f737049ad0) at main.c:198
```

Best regards,
Egor Chindyaskin
Postgres Professional: http://postgrespro.com/

**Comment by JelteF** [comment]
It seems that this happens when there are no workers in your cluster. I would probably accept a fix for this crash, but I don't consider it an actual problem. `activate_node_snapshot` is a function that is only meant to be used when running tests, it's not meant to be executed by end-users. That's why the SQL side of the function is not created by default.

**Comment by JelteF** [comment]
Also it's no security issue, since only superuser can create functions with LANGUAGE C.
