### ISSUE TITLE
Wrong assert in ruleutils_xx.c

### ISSUE THREAD

**Issue by Green-Chan** [citusdata/citus#7591]
In #7379 assert in ruleutils_15.c was changed from
```
	while (i < colinfo->num_cols && colinfo->colnames[i] == NULL)
		i++;
	Assert(i == colinfo->num_cols);
```
to
```
	for (int col_index = 0; col_index < colinfo->num_cols; col_index++)
	{
		/*
		 * In the above processing-loops, "i" advances only if
		 * the column is not new, check if this is a new column.
		 */
		if (colinfo->is_new_col[col_index])
			i++;
	}
	Assert(i == colinfo->num_cols);
```
(later ruleutils_14.c and ruleutils_16.c were also changed).
But that is still wrong. The following script leads to assert failure:
```
CREATE EXTENSION citus;
CREATE TABLE t1 (a int, b int);
CREATE TABLE t2 (x int, y int);
INSERT INTO t1 VALUES (1, 2), (4, 5);
INSERT INTO t2 VALUES (1, 1), (5, 5);
SELECT create_distributed_table('t2','x');
CREATE VIEW v AS SELECT * FROM t2 JOIN t1 on (t1.a=t2.x);
ALTER TABLE t2 ADD COLUMN z int;
SELECT * FROM v;
```

Here is the explanation of why assert was changed: https://github.com/citusdata/citus/pull/7379#discussion_r1437366160
It is wrong. `is_new_col` has nothing to do with `colnames`. If you take a look at the `deparse_columns` definition and comments there as a whole, you'll see that `is_new_col` actually about columns described by `new_colnames`. Yes, may be that comment should be changed to
> Entries with is_new_col false must match the non-NULL new_colnames entries one-for-one.
I also spent some time exploring what `set_join_column_names()` does, and that confirms that `is_new_col` is about `new_colnames`, not `colnames`.

So you should probably return the old assert back and reinvestigate why it fails. One of examples of failure is from `multi_alter_table_statements` test:
```
-- Create a reference table
CREATE TABLE tbl_ref_mats(row_id integer primary key);
INSERT INTO tbl_ref_mats VALUES (1), (2);
SELECT create_reference_table('tbl_ref_mats');

-- Create a distributed table
CREATE TABLE tbl_dist_mats(series_id integer);
INSERT INTO tbl_dist_mats VALUES (1), (1), (2), (2);
SELECT create_distributed_table('tbl_dist_mats', 'series_id');

-- Create a view that joins the distributed table with the reference table on the distribution key.
CREATE VIEW vw_citus_views as
SELECT d.series_id FROM tbl_dist_mats d JOIN tbl_ref_mats r ON d.series_id = r.row_id;

-- The view initially works fine
SELECT * FROM vw_citus_views ORDER BY 1;
-- Now, alter the table
ALTER TABLE tbl_ref_mats ADD COLUMN category1 varchar(50);
SELECT * FROM vw_citus_views ORDER BY 1;
```
From what I could understand, `set_join_column_names()` initialises `colinfo->colnames` and `noldcolumns` from `rte->eref->colnames`, and it expects that this list contains only old columns (meaning "columns that existed when the query was parsed"). For the above example `rte->eref->colnames` consists of `"series_id"`, `"row_id"` and `"category1"`.
If you comment out
```
SELECT create_reference_table('tbl_ref_mats');
```
then  `rte->eref->colnames` consists of `"series_id"` and `"row_id"`, as expected.

Looks like `rte->eref->colnames` is formed wrong for reference table

**Comment by Green-Chan** [comment]
I'm not sure what has changed, but I get this assertion failure just running tests now.
I have Ubuntu 22.04, gcc 11.4.0, PostgreSQL REL_16_3 configured with options `CFLAGS=" -Og" --enable-tap-tests --enable-debug --with-openssl --with-libxml --enable-cassert --with-icu --with-lz4`, Citus main (9e1852ea).
When running `make check-enterprise` I get single_node_enterprise test failed and line
```
TRAP: failed Assert("i == colinfo->num_cols"), File: "deparser/ruleutils_16.c", Line: 1592, PID: 58606
```
in `tmp_check/master/log/postmater.log`

**Comment by m3hm3t** [comment]
I was able to reproduce the issue in the devcontainer environment. 

When querying a view that was created before altering the schema of the underlying tables (specifically, after adding a new column), the server crashes with an assertion failure in the `set_join_column_names` function in `ruleutils_16.c`. 

Here’s a link to the relevant test case:
https://github.com/citusdata/citus/blob/f6959715dc49404510f2f3340b9719b33ddd152b/src/test/regress/sql/single_node_enterprise.sql#L291

### These are the columns related to the view:

```sql
SELECT * FROM (test JOIN colocated_table USING (x)) foo(x, y, z)
LEFT JOIN ref ON foo.x = ref.a;

 x  |  y  |      z       |  y  |    z     | a  |  b
---------------------------------------------------------------------
```

### Here’s the relevant part of the server log:

```
LOG:  colinfo->num_cols: 6, i: 7, j: 7, nnewcolumns: 7
TRAP: failed Assert("i == colinfo->num_cols"), File: "deparser/ruleutils_16.c", Line: 1614
```

- `colinfo->num_cols` represents the number of columns in the join at the time the view was created (which is 6).
- After adding a new column `z` to `colocated_table`, the actual number of columns becomes 7.
- When the deparser tries to reconstruct the view, it expects `i` (the index of processed columns) to match `colinfo->num_cols`.
- Since `i` increments to 7 due to the new column, but `colinfo->num_cols` remains at 6, the assertion `Assert(i == colinfo->num_cols)` fails, causing the crash.

The deparser doesn't seem to handle schema changes in underlying tables that affect views.

After recreating the view, the assertion no longer fails.

```
CREATE OR REPLACE VIEW view_created_before_shard_moves AS
SELECT count(*) AS count
FROM (test JOIN colocated_table USING (x)) AS foo
LEFT JOIN ref ON (foo.x = ref.a);
```

**Comment by onurctirtir** [comment]
Since we enable asserts during valgrind testing, this also affects our valgrind tests. This is because, when the asserts are enabled, then an assertion failure translates to `abort()` and this causes postmaster to kill all other children.

To be clearer, this is probably the reason why we're getting such core dumps during execution of `check-multi-1-vg` & `check-enterprise-vg` test targets:
```
Program terminated with signal SIGABRT, Aborted.
#0  0x0000000004f5eb2c in ?? ()
#0  0x0000000004f5eb2c in ?? ()
#1  0xffffffffffffffd0 in ?? ()
#2  0x691dcec20e659900 in ?? ()
#3  0x0000001fff000c83 in ?? ()
#4  0x0000000000000006 in ?? ()
#5  0x00000000070dfd80 in ?? ()
#6  0x0000000000000642 in ?? ()
#7  0x0000000000000006 in ?? ()
#8  0x0000000012a5cae8 in ?? ()
#9  0x0000001ffeffe480 in ?? ()
#10 0x0000000004f0527e in ?? ()
#11 0x0000000000167189 in doPickSplit (index=0x0, state=0x1fff0009f8,
    current=0x0, parent=0x1ffeffe188, newLeafTuple=<optimized out>,
    level=<optimized out>, isNulls=137, isNew=80) at spgdoinsert.c:1350
```

Andres is thinking that these core dumps possibly don't indicate anything wrong with `doPickSplit()` itself but that it takes a huge amount of time to execute `doPickSplit()` and this increases the chances of getting the kill signal sent by the postmaster due to the assertion failure described in this issue.

**Comment by ihalatci** [comment]
closed by #8136
