### ISSUE TITLE
Router executor crashes on subqueries in WHERE clause

### ISSUE THREAD

**Issue by onderkalaci** [citusdata/citus#893]
Steps to reproduce:

```SQL

CREATE TABLE raw_events_first (user_id int, time timestamp, value_1 int, value_2 int, value_3 float, value_4 bigint, UNIQUE(user_id, value_1));
SELECT master_create_distributed_table('raw_events_first', 'user_id', 'hash');
SELECT master_create_worker_shards('raw_events_first', 4, 2);

CREATE TABLE raw_events_second (user_id int, time timestamp, value_1 int, value_2 int, value_3 float, value_4 bigint, UNIQUE(user_id, value_1));
SELECT master_create_distributed_table('raw_events_second', 'user_id', 'hash');
SELECT master_create_worker_shards('raw_events_second', 4, 2);


SELECT * FROM raw_events_first WHERE user_id IN (SELECT user_id FROM raw_events_second WHERE user_id  = 2);
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
!> 
```

GDB backtrace on 9.5:
```
Program received signal SIGABRT, Aborted.
0x00007fff8d59f0ae in __pthread_kill ()
(gdb) bt
#0  0x00007fff8d59f0ae in __pthread_kill ()
#1  0x00007fff992f3500 in pthread_kill ()
#2  0x00007fff8cb7537b in abort ()
#3  0x00000001044234d9 in ExceptionalCondition (conditionName=0x104b20982 "!(!contain_mutable_functions((Node *) (query->jointree->quals)))", errorType=0x104b17c64 "FailedAssertion", fileName=0x104b209c3 "utils/citus_clauses.c", lineNumber=98) at assert.c:54
#4  0x0000000104ae59c9 in ExecuteMasterEvaluableFunctions (query=0x7feca4030ab0) at utils/citus_clauses.c:98
#5  0x0000000104aab44c in RouterExecutorRun (queryDesc=0x7feca4010038, direction=ForwardScanDirection, count=0) at executor/multi_router_executor.c:492
#6  0x0000000104aa94a6 in multi_ExecutorRun (queryDesc=0x7feca4010038, direction=ForwardScanDirection, count=0) at executor/multi_executor.c:210
#7  0x00000001040b95a8 in ExecutorRun (queryDesc=0x7feca4010038, direction=ForwardScanDirection, count=0) at execMain.c:283
#8  0x0000000104284623 in PortalRunSelect (portal=0x7feca4014838, forward=1 '\001', count=0, dest=0x7feca4021150) at pquery.c:942
#9  0x0000000104283ffa in PortalRun (portal=0x7feca4014838, count=9223372036854775807, isTopLevel=1 '\001', dest=0x7feca4021150, altdest=0x7feca4021150, completionTag=0x7fff5bdc1380 "") at pquery.c:786
#10 0x000000010427f79a in exec_simple_query (query_string=0x7feca4012838 "SELECT * FROM raw_events_first WHERE user_id IN (SELECT user_id FROM raw_events_second WHERE user_id  = 2);") at postgres.c:1104
#11 0x000000010427ea9e in PostgresMain (argc=1, argv=0x7feca3803aa0, dbname=0x7feca3803900 "postgres", username=0x7feca38038d8 "onderkalaci") at postgres.c:4030
#12 0x00000001041e0d09 in BackendRun (port=0x7feca3405570) at postmaster.c:4239
#13 0x00000001041dff49 in BackendStartup (port=0x7feca3405570) at postmaster.c:3913
#14 0x00000001041def4f in ServerLoop () at postmaster.c:1684
#15 0x00000001041dc71b in PostmasterMain (argc=3, argv=0x7feca34035c0) at postmaster.c:1292
#16 0x000000010411b5a0 in main (argc=3, argv=0x7feca34035c0) at main.c:223
```

**Comment by mtuncer** [comment]
It seems like this crash started when PR #855 is merged

**Comment by marcocitus** [comment]
Thanks @mtuncer , that changes accidentally triggered master evaluation for SELECTs, which works ok, but doesn't pass the assert. Will send out a fix.
